/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernIr from "../../../index";

export interface InferredAuthSchemeTokenEndpoint {
    endpoint: FernIr.EndpointReference;
    expiryProperty: FernIr.ResponseProperty | undefined;
    authenticatedRequestHeaders: FernIr.InferredAuthenticatedRequestHeader[];
}
