// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/unknown/fern/core"
	internal "github.com/unknown/fern/internal"
	option "github.com/unknown/fern/option"
	unknown "github.com/unknown/fern/unknown"
	http "net/http"
)

type Client struct {
	Unknown *unknown.Client
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Unknown: unknown.NewClient(opts...),
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}
