# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.send_response import SendResponse
from .requests.a_top_level_literal import ATopLevelLiteralParams
from .types.some_aliased_literal import SomeAliasedLiteral

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawInlinedClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def send(
        self,
        *,
        prompt: typing.Literal["You are a helpful assistant"] = "You are a helpful assistant",
        query: str,
        stream: typing.Literal[False] = False,
        aliased_context: SomeAliasedLiteral = "You're super wise",
        object_with_literal: ATopLevelLiteralParams,
        context: typing.Optional[typing.Literal["You're super wise"]] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        maybe_context: typing.Optional[SomeAliasedLiteral] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SendResponse]:
        """
        Parameters
        ----------
        prompt : typing.Literal["You are a helpful assistant"]

        query : str

        stream : typing.Literal[False]

        aliased_context : SomeAliasedLiteral

        object_with_literal : ATopLevelLiteralParams

        context : typing.Optional[typing.Literal["You're super wise"]]

        temperature : typing.Optional[float]

        maybe_context : typing.Optional[SomeAliasedLiteral]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SendResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            "inlined",
            method="POST",
            json={
                "prompt": "You are a helpful assistant",
                "context": context,
                "query": query,
                "temperature": temperature,
                "stream": False,
                "aliasedContext": "You're super wise",
                "maybeContext": maybe_context,
                "objectWithLiteral": convert_and_respect_annotation_metadata(
                    object_=object_with_literal, annotation=ATopLevelLiteralParams, direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SendResponse,
                    parse_obj_as(
                        type_=SendResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawInlinedClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def send(
        self,
        *,
        prompt: typing.Literal["You are a helpful assistant"] = "You are a helpful assistant",
        query: str,
        stream: typing.Literal[False] = False,
        aliased_context: SomeAliasedLiteral = "You're super wise",
        object_with_literal: ATopLevelLiteralParams,
        context: typing.Optional[typing.Literal["You're super wise"]] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        maybe_context: typing.Optional[SomeAliasedLiteral] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SendResponse]:
        """
        Parameters
        ----------
        prompt : typing.Literal["You are a helpful assistant"]

        query : str

        stream : typing.Literal[False]

        aliased_context : SomeAliasedLiteral

        object_with_literal : ATopLevelLiteralParams

        context : typing.Optional[typing.Literal["You're super wise"]]

        temperature : typing.Optional[float]

        maybe_context : typing.Optional[SomeAliasedLiteral]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SendResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "inlined",
            method="POST",
            json={
                "prompt": "You are a helpful assistant",
                "context": context,
                "query": query,
                "temperature": temperature,
                "stream": False,
                "aliasedContext": "You're super wise",
                "maybeContext": maybe_context,
                "objectWithLiteral": convert_and_respect_annotation_metadata(
                    object_=object_with_literal, annotation=ATopLevelLiteralParams, direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SendResponse,
                    parse_obj_as(
                        type_=SendResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
