// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const UserCountry: core.serialization.Schema<
    serializers.csharpSystemCollision.UserCountry.Raw,
    SeedApi.csharpSystemCollision.UserCountry
> = core.serialization.forwardCompatibleEnum_(["USA"]);

export declare namespace UserCountry {
    export type Raw = "USA";
}
