/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as FernOpenapiIr from "../../../../api";
import * as core from "../../../../core";

export const WebsocketMessageExample: core.serialization.ObjectSchema<
    serializers.WebsocketMessageExample.Raw,
    FernOpenapiIr.WebsocketMessageExample
> = core.serialization
    .objectWithoutOptionalProperties({
        messageType: core.serialization.string(),
        payload: core.serialization.lazy(async () => (await import("../../..")).FullExample),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).WithDescription));

export declare namespace WebsocketMessageExample {
    interface Raw extends serializers.WithDescription.Raw {
        messageType: string;
        payload: serializers.FullExample.Raw;
    }
}
