"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./AliasInlineValue.js"), exports);
__exportStar(require("./AliasListInline.js"), exports);
__exportStar(require("./AliasMapInline.js"), exports);
__exportStar(require("./AliasProperty.js"), exports);
__exportStar(require("./AliasPropertyType.js"), exports);
__exportStar(require("./AliasSetInline.js"), exports);
__exportStar(require("./AliasVariant.js"), exports);
__exportStar(require("./AliasVariantType.js"), exports);
__exportStar(require("./DiscriminatedUnion1.js"), exports);
__exportStar(require("./DiscriminatedUnion1InlineType1.js"), exports);
__exportStar(require("./DiscriminatedUnion1InlineType1InlineType1.js"), exports);
__exportStar(require("./DiscriminatedUnion1InlineType2.js"), exports);
__exportStar(require("./InlineEnum1.js"), exports);
__exportStar(require("./NonAliasVariant.js"), exports);
__exportStar(require("./ObjectTypeWithAliasType.js"), exports);
__exportStar(require("./ObjectTypeWithListAliasType.js"), exports);
__exportStar(require("./ObjectTypeWithMapAliasTypeBoth.js"), exports);
__exportStar(require("./ObjectTypeWithMapAliasTypeKey.js"), exports);
__exportStar(require("./ObjectTypeWithMapAliasTypeValue.js"), exports);
__exportStar(require("./ObjectTypeWithSetAliasType.js"), exports);
__exportStar(require("./OtherAliasProperty.js"), exports);
__exportStar(require("./OtherAliasPropertyType.js"), exports);
__exportStar(require("./OtherAliasVariant.js"), exports);
__exportStar(require("./OtherAliasVariantType.js"), exports);
__exportStar(require("./ReferenceType.js"), exports);
__exportStar(require("./RequestTypeInlineType1.js"), exports);
__exportStar(require("./RootType1.js"), exports);
__exportStar(require("./RootType1FooListItem.js"), exports);
__exportStar(require("./RootType1FooMapValue.js"), exports);
__exportStar(require("./RootType1FooSetItem.js"), exports);
__exportStar(require("./RootType1InlineType1.js"), exports);
__exportStar(require("./RootType1InlineType1NestedInlineType1.js"), exports);
__exportStar(require("./TypesPropertyCollisionBaseParent.js"), exports);
__exportStar(require("./TypesPropertyCollisionChild.js"), exports);
__exportStar(require("./TypesPropertyCollisionExtendsChild.js"), exports);
__exportStar(require("./TypesPropertyCollisionExtendsParent.js"), exports);
__exportStar(require("./TypesPropertyCollisionParent.js"), exports);
__exportStar(require("./UndiscriminatedUnion1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1DiscriminatedUnion1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1DiscriminatedUnion1InlineType1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1DiscriminatedUnion1InlineType1InlineType1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1DiscriminatedUnion1InlineType2.js"), exports);
__exportStar(require("./UndiscriminatedUnion1InlineEnum1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1InlineListItem1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1InlineMapItem1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1InlineSetItem1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1InlineType1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1InlineType1InlineType1.js"), exports);
__exportStar(require("./UndiscriminatedUnion1InlineType2.js"), exports);
__exportStar(require("./UndiscriminatedUnionTypeWithAliasListVariant.js"), exports);
__exportStar(require("./UndiscriminatedUnionTypeWithAliasMapVariant.js"), exports);
__exportStar(require("./UndiscriminatedUnionTypeWithAliasSetVariant.js"), exports);
__exportStar(require("./UndiscriminatedUnionTypeWithAliasVariant.js"), exports);
__exportStar(require("./UnionTypeWithAliasListVariant.js"), exports);
__exportStar(require("./UnionTypeWithAliasMapVariant.js"), exports);
__exportStar(require("./UnionTypeWithAliasSetVariant.js"), exports);
__exportStar(require("./UnionTypeWithAliasVariant.js"), exports);
__exportStar(require("./UnionWithTypesVariant.js"), exports);
__exportStar(require("./UnionWithTypesVariantInlineType1.js"), exports);
__exportStar(require("./UnionWithTypesVariantOtherInlineType1.js"), exports);
__exportStar(require("./UserId.js"), exports);
