/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FernDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { UnionSettingsSchema } from "./UnionSettingsSchema";
import { MessageNamingSettingsSchema } from "./MessageNamingSettingsSchema";
import { RemoveDiscriminantsFromSchemas } from "./RemoveDiscriminantsFromSchemas";

export const ApiDefinitionSettingsSchema: core.serialization.ObjectSchema<
    serializers.ApiDefinitionSettingsSchema.Raw,
    FernDefinition.ApiDefinitionSettingsSchema
> = core.serialization.object({
    "use-title": core.serialization.boolean().optional(),
    unions: UnionSettingsSchema.optional(),
    "message-naming": MessageNamingSettingsSchema.optional(),
    "respect-nullable-schemas": core.serialization.boolean().optional(),
    "only-include-referenced-schemas": core.serialization.boolean().optional(),
    "inline-path-parameters": core.serialization.boolean().optional(),
    "idiomatic-request-names": core.serialization.boolean().optional(),
    "wrap-references-to-nullable-in-optional": core.serialization.boolean().optional(),
    "coerce-optional-schemas-to-nullable": core.serialization.boolean().optional(),
    "group-environments-by-host": core.serialization.boolean().optional(),
    "remove-discriminants-from-schemas": RemoveDiscriminantsFromSchemas.optional(),
});

export declare namespace ApiDefinitionSettingsSchema {
    export interface Raw {
        "use-title"?: boolean | null;
        unions?: UnionSettingsSchema.Raw | null;
        "message-naming"?: MessageNamingSettingsSchema.Raw | null;
        "respect-nullable-schemas"?: boolean | null;
        "only-include-referenced-schemas"?: boolean | null;
        "inline-path-parameters"?: boolean | null;
        "idiomatic-request-names"?: boolean | null;
        "wrap-references-to-nullable-in-optional"?: boolean | null;
        "coerce-optional-schemas-to-nullable"?: boolean | null;
        "group-environments-by-host"?: boolean | null;
        "remove-discriminants-from-schemas"?: RemoveDiscriminantsFromSchemas.Raw | null;
    }
}
