name: ci

on: [push]

env:
  CI: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  MSBUILDTERMINALLOGGER: off

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.x
            8.x

      - name: Install tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        id: build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true

      - name: Test
        run: dotnet test --no-restore --no-build -c Release /p:ContinuousIntegrationBuild=true

      - name: Pack
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && steps.build.outcome == 'success'
        run: dotnet pack src/SeedCsharpReadonlyRequest/SeedCsharpReadonlyRequest.csproj --no-build --no-restore -c Release

      - name: Publish to NuGet.org
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && steps.build.outcome == 'success'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_TOKEN }}
        run: dotnet nuget push src/SeedCsharpReadonlyRequest/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source "nuget.org"
