// This file was auto-generated by Fern from our API Definition.

import type * as acme from "../../../index.js";

export interface V2BasicCustomFiles {
    methodName: string;
    signature: acme.trace.V2NonVoidFunctionSignature;
    additionalFiles: Record<string, acme.trace.V2Files>;
    basicTestCaseTemplate: acme.trace.V2BasicTestCaseTemplate;
}
