import {
    WithBaseContextMixin,
    WithEndpointErrorUnionContextMixin,
    WithEndpointTypeSchemasContextMixin,
    WithEnvironmentsContextMixin,
    WithGenericAPISdkErrorContextMixin,
    WithInlinedRequestBodySchemaContextMixin,
    WithRequestWrapperContextMixin,
    WithSdkClientClassContextMixin,
    WithSdkErrorContextMixin,
    WithSdkErrorSchemaContextMixin,
    WithTimeoutSdkErrorContextMixin,
    WithTypeContextMixin,
    WithTypeSchemaContextMixin,
} from "./mixins";

export interface SdkClientClassContext
    extends WithBaseContextMixin,
        WithTypeContextMixin,
        WithTypeSchemaContextMixin,
        WithSdkErrorContextMixin,
        WithSdkErrorSchemaContextMixin,
        WithSdkClientClassContextMixin,
        WithEndpointErrorUnionContextMixin,
        WithRequestWrapperContextMixin,
        WithEndpointTypeSchemasContextMixin,
        WithEnvironmentsContextMixin,
        WithGenericAPISdkErrorContextMixin,
        WithTimeoutSdkErrorContextMixin,
        WithInlinedRequestBodySchemaContextMixin {}
