/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SeedUnions from "../../../../api/index";
import * as core from "../../../../core";

export const HastyPain: core.serialization.ObjectSchema<serializers.HastyPain.Raw, SeedUnions.HastyPain> =
    core.serialization.object({
        value: core.serialization.string(),
    });

export declare namespace HastyPain {
    export interface Raw {
        value: string;
    }
}
