// This file was auto-generated by Fern from our API Definition.

import type * as SeedTrace from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import type { TraceResponse } from "./TraceResponse.js";

export const TraceResponsesPage: core.serialization.ObjectSchema<
    serializers.TraceResponsesPage.Raw,
    SeedTrace.TraceResponsesPage
> = core.serialization.object({
    offset: core.serialization.number().optional(),
    traceResponses: core.serialization.list(TraceResponse),
});

export declare namespace TraceResponsesPage {
    export interface Raw {
        offset?: number | null;
        traceResponses: TraceResponse.Raw[];
    }
}
