import { FernGeneratorExec } from "@fern-fern/generator-exec-sdk";
import { IntermediateRepresentation } from "@fern-fern/ir-sdk/api";
import { JavaScriptRuntime } from "@fern-typescript/commons";
import { ts } from "ts-morph";
import { ModelContext } from "../model-context/ModelContext";
import { EndpointErrorUnionContext } from "./endpoint-error-union";
import { EnvironmentsContext } from "./environments";
import { GenericAPISdkErrorContext } from "./generic-api-sdk-error";
import { RequestWrapperContext } from "./request-wrapper";
import { SdkClientClassContext } from "./sdk-client-class";
import { SdkEndpointTypeSchemasContext } from "./sdk-endpoint-type-schemas";
import { SdkErrorContext } from "./sdk-error";
import { SdkErrorSchemaContext } from "./sdk-error-schema";
import { SdkInlinedRequestBodySchemaContext } from "./sdk-inlined-request-body-schema";
import { TimeoutSdkErrorContext } from "./timeout-sdk-error";
import { VersionContext } from "./version";

export interface SdkContext extends ModelContext {
    ir: IntermediateRepresentation;
    config: FernGeneratorExec.GeneratorConfig;
    sdkInstanceReferenceForSnippet: ts.Identifier;
    namespaceExport: string;
    endpointErrorUnion: EndpointErrorUnionContext;
    environments: EnvironmentsContext;
    genericAPISdkError: GenericAPISdkErrorContext;
    sdkEndpointTypeSchemas: SdkEndpointTypeSchemasContext;
    sdkError: SdkErrorContext;
    sdkErrorSchema: SdkErrorSchemaContext;
    sdkInlinedRequestBodySchema: SdkInlinedRequestBodySchemaContext;
    timeoutSdkError: TimeoutSdkErrorContext;
    requestWrapper: RequestWrapperContext;
    sdkClientClass: SdkClientClassContext;
    version: VersionContext;
    targetRuntime: JavaScriptRuntime;
    includeSerdeLayer: boolean;
    retainOriginalCasing: boolean;
    generateOAuthClients: boolean;
    inlineFileProperties: boolean;
    omitUndefined: boolean;
}
