name: Artifact Seed Metrics
description: Artifact the seed test start and end times found during seed jobs, as well as the generator's determinism

inputs:
  sdk-name:
    description: The name of the SDK to get the test matrix for
    required: true
  job-index:
    description: The index of the job (when parallelized in a matrix strategy)
    required: true
  start-time:
    description: The start time of the seed tests
    required: true
  end-time:
    description: The end time of the seed tests
    required: true
  deterministic:
    description: Whether the run portion of seed generation is deterministic or not (will reproduce the same results on repeated runs)
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Metrics File
      id: create-metrics
      shell: bash
      run: |
        METRICS_FILE_NAME="seed-metrics-${INPUTS_SDK_NAME}-${INPUTS_JOB_INDEX}.json"
        echo "file_name=$METRICS_FILE_NAME" >> $GITHUB_OUTPUT
        echo "{\"index\":\"${INPUTS_JOB_INDEX}\",\"startTimeSeconds\":\"${INPUTS_START_TIME}\",\"endTimeSeconds\":\"${INPUTS_END_TIME}\",\"deterministic\":\"${INPUTS_DETERMINISTIC}\"}" > $METRICS_FILE_NAME
      env:
        INPUTS_SDK_NAME: ${{ inputs.sdk-name }}
        INPUTS_JOB_INDEX: ${{ inputs.job-index }}
        INPUTS_START_TIME: ${{ inputs.start-time }}
        INPUTS_END_TIME: ${{ inputs.end-time }}
        INPUTS_DETERMINISTIC: ${{ inputs.deterministic }}

    # Save for at least a week to help track slowdowns if/when they show up
    - name: Upload Metrics File
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: ${{ steps.create-metrics.outputs.file_name }}
        path: ${{ steps.create-metrics.outputs.file_name }}
        if-no-files-found: error
        retention-days: 7
