/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.inferredAuthImplicitApiKey.resources.simple;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.seed.inferredAuthImplicitApiKey.core.ClientOptions;
import com.seed.inferredAuthImplicitApiKey.core.ObjectMappers;
import com.seed.inferredAuthImplicitApiKey.core.RequestOptions;
import com.seed.inferredAuthImplicitApiKey.core.RetryInterceptor;
import com.seed.inferredAuthImplicitApiKey.core.SeedInferredAuthImplicitApiKeyApiException;
import com.seed.inferredAuthImplicitApiKey.core.SeedInferredAuthImplicitApiKeyException;
import com.seed.inferredAuthImplicitApiKey.core.SeedInferredAuthImplicitApiKeyHttpResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawSimpleClient {
    protected final ClientOptions clientOptions;

    public RawSimpleClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public SeedInferredAuthImplicitApiKeyHttpResponse<Void> getSomething() {
        return getSomething(null);
    }

    public SeedInferredAuthImplicitApiKeyHttpResponse<Void> getSomething(RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("get-something");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new SeedInferredAuthImplicitApiKeyHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new SeedInferredAuthImplicitApiKeyApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new SeedInferredAuthImplicitApiKeyException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new SeedInferredAuthImplicitApiKeyException("Network error executing HTTP request", e);
        }
    }
}
