// This file was auto-generated by Fern from our API Definition.

import { AcmeClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("PathClient", () => {
    test("send", async () => {
        const server = mockServerPool.createServer();
        const client = new AcmeClient({
            maxRetries: 0,
            token: "test",
            apiVersion: "test",
            apiKey: "test",
            environment: { base: server.baseUrl, auth: server.baseUrl, upload: server.baseUrl },
        });

        const rawResponseBody = { message: "The weather is sunny", status: 200, success: true };

        server.mockEndpoint().post("/path/123").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.literal.path.send({
            id: "123",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
