/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernDefinition from "../../../index";

export interface OAuthGetTokenEndpoint {
    /** The endpoint to get the access token, such as 'auth.get_token */
    endpoint: string;
    "request-properties"?: FernDefinition.OAuthAccessTokenRequestPropertiesSchema;
    "response-properties"?: FernDefinition.OAuthAccessTokenResponsePropertiesSchema;
}
