// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../index.js";

export interface KeyValuePair {
    key: SeedApi.trace.VariableValue;
    value: SeedApi.trace.VariableValue;
}

export namespace KeyValuePair {
    export type Request = Omit<KeyValuePair, "key" | "value"> & {
        key: SeedApi.trace.VariableValue;
        value: SeedApi.trace.VariableValue;
    };
    export type Response = Omit<KeyValuePair, "key" | "value"> & {
        key: SeedApi.trace.VariableValue;
        value: SeedApi.trace.VariableValue;
    };
}
