// This file was auto-generated by Fern from our API Definition.

export interface TracedFile {
    filename: string;
    directory: string;
}

export namespace TracedFile {
    export type Request = Omit<TracedFile, "filename" | "directory"> & {
        filename: string;
        directory: string;
    };
    export type Response = Omit<TracedFile, "filename" | "directory"> & {
        filename: string;
        directory: string;
    };
}
