// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../index.js";

export interface V2V3TestCaseImplementation {
    description: SeedApi.trace.V2V3TestCaseImplementationDescription;
    function: SeedApi.trace.V2V3TestCaseFunction;
}

export namespace V2V3TestCaseImplementation {
    export type Request = Omit<V2V3TestCaseImplementation, "description" | '"function"'> & {
        description: SeedApi.trace.V2V3TestCaseImplementationDescription;
        function: SeedApi.trace.V2V3TestCaseFunction;
    };
    export type Response = Omit<V2V3TestCaseImplementation, "description" | '"function"'> & {
        description: SeedApi.trace.V2V3TestCaseImplementationDescription;
        function: SeedApi.trace.V2V3TestCaseFunction;
    };
}
