// This file was auto-generated by Fern from our API Definition.
import { normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.mjs";
import * as core from "../../../../../../core/index.mjs";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.mjs";
import * as errors from "../../../../../../errors/index.mjs";
export class ContentTypeClient {
    constructor(options) {
        var _a;
        this._options = normalizeClientOptionsWithAuth(options);
        this._requestFn =
            (_a = options._requestFn) !== null && _a !== void 0 ? _a : core.createRequestFn(Object.assign(Object.assign({}, this._options), { createStatusCodeError: (args) => new errors.SeedExhaustiveError(args), handleNonStatusCodeError: handleNonStatusCodeError }));
    }
    /**
     * @param {SeedExhaustive.types.ObjectWithOptionalField} request
     * @param {ContentTypeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.endpoints.contentType.postJsonPatchContentType({
     *         string: "string",
     *         integer: 1,
     *         long: 1000000,
     *         double: 1.1,
     *         bool: true,
     *         datetime: "2024-01-15T09:30:00Z",
     *         date: "2023-01-15",
     *         uuid: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
     *         base64: "SGVsbG8gd29ybGQh",
     *         list: ["list", "list"],
     *         set: ["set"],
     *         map: {
     *             1: "map"
     *         },
     *         bigint: "1000000"
     *     })
     */
    postJsonPatchContentType(request, requestOptions) {
        return this._requestFn({
            method: "POST",
            path: "/foo/bar",
            body: request,
            contentType: "application/json-patch+json",
            requestType: "json",
            queryParameters: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.queryParams,
            requestOptions,
        });
    }
    /**
     * @param {SeedExhaustive.types.ObjectWithOptionalField} request
     * @param {ContentTypeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.endpoints.contentType.postJsonPatchContentWithCharsetType({
     *         string: "string",
     *         integer: 1,
     *         long: 1000000,
     *         double: 1.1,
     *         bool: true,
     *         datetime: "2024-01-15T09:30:00Z",
     *         date: "2023-01-15",
     *         uuid: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
     *         base64: "SGVsbG8gd29ybGQh",
     *         list: ["list", "list"],
     *         set: ["set"],
     *         map: {
     *             1: "map"
     *         },
     *         bigint: "1000000"
     *     })
     */
    postJsonPatchContentWithCharsetType(request, requestOptions) {
        return this._requestFn({
            method: "POST",
            path: "/foo/baz",
            body: request,
            contentType: "application/json-patch+json; charset=utf-8",
            requestType: "json",
            queryParameters: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.queryParams,
            requestOptions,
        });
    }
}
