// This file was auto-generated by Fern from our API Definition.

import { AcmeClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("FoldersClient", () => {
    test("foo", async () => {
        const server = mockServerPool.createServer();
        const client = new AcmeClient({
            maxRetries: 0,
            token: "test",
            apiVersion: "test",
            apiKey: "test",
            environment: { base: server.baseUrl, auth: server.baseUrl, upload: server.baseUrl },
        });

        server.mockEndpoint().post("/").respondWith().statusCode(200).build();

        const response = await client.folders.folders.foo();
        expect(response).toEqual(undefined);
    });
});
