// Generated by Fern. Do not edit.

package api

import (
	context "context"
	errors "errors"
	fmt "fmt"
	core "github.com/fern-api/fern-go/internal/testdata/sdk/path-params/fixtures/core"
	io "io"
	http "net/http"
)

type getUserV2Endpoint struct {
	url        string
	httpClient core.HTTPClient
	header     http.Header
}

func newGetUserV2Endpoint(url string, httpClient core.HTTPClient, clientOptions *core.ClientOptions) *getUserV2Endpoint {
	return &getUserV2Endpoint{
		url:        url,
		httpClient: httpClient,
		header:     clientOptions.ToHeader(),
	}
}

func (g *getUserV2Endpoint) decodeError(statusCode int, body io.Reader) error {
	bytes, err := io.ReadAll(body)
	if err != nil {
		return err
	}
	return errors.New(string(bytes))
}

func (g *getUserV2Endpoint) Call(ctx context.Context, userId string) (string, error) {
	endpointURL := fmt.Sprintf(g.url, userId)
	var response string
	if err := core.DoRequest(
		ctx,
		g.httpClient,
		endpointURL,
		http.MethodGet,
		nil,
		&response,
		g.header,
		g.decodeError,
	); err != nil {
		return response, err
	}
	return response, nil
}
