/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as SeedIdempotencyHeaders from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const Currency: core.serialization.Schema<serializers.Currency.Raw, SeedIdempotencyHeaders.Currency> =
    core.serialization.enum_(["USD", "YEN"]);

export declare namespace Currency {
    export type Raw = "USD" | "YEN";
}
