// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../core/index.js";
import type * as SeedApi from "../../../index.js";

export type Error =
    | SeedApi.playlist.getplaylist.Error.UnauthorizedError
    | SeedApi.playlist.getplaylist.Error.NotFoundError
    | SeedApi.playlist.getplaylist.Error._Unknown;

export namespace Error {
    export interface UnauthorizedError {
        statusCode: 401;
        content: SeedApi.UnauthorizedErrorBody;
    }

    export interface NotFoundError {
        statusCode: 404;
        content?: unknown;
    }

    export interface _Unknown {
        statusCode: void;
        content: core.Fetcher.Error;
    }

    export interface _Visitor<_Result> {
        unauthorizedError: (value: SeedApi.UnauthorizedErrorBody) => _Result;
        notFoundError: (value: unknown) => _Result;
        _other: (value: core.Fetcher.Error) => _Result;
    }
}

export const Error = {
    unauthorizedError: (value: SeedApi.UnauthorizedErrorBody): SeedApi.playlist.getplaylist.Error.UnauthorizedError => {
        return {
            content: value,
            statusCode: 401,
        };
    },

    notFoundError: (value?: unknown): SeedApi.playlist.getplaylist.Error.NotFoundError => {
        return {
            content: value,
            statusCode: 404,
        };
    },

    _unknown: (fetcherError: core.Fetcher.Error): SeedApi.playlist.getplaylist.Error._Unknown => {
        return {
            statusCode: undefined,
            content: fetcherError,
        };
    },

    _visit: <_Result>(
        value: SeedApi.playlist.getplaylist.Error,
        visitor: SeedApi.playlist.getplaylist.Error._Visitor<_Result>,
    ): _Result => {
        switch (value.statusCode) {
            case 401:
                return visitor.unauthorizedError(value.content);
            case 404:
                return visitor.notFoundError(value.content);
            default:
                return visitor._other(value.content);
        }
    },
} as const;
