/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.bigunion.types;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UnwillingSmoke.Builder.class
)
public final class UnwillingSmoke {
  private final String value;

  private UnwillingSmoke(String value) {
    this.value = value;
  }

  @JsonProperty("value")
  public String getValue() {
    return value;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UnwillingSmoke && equalTo((UnwillingSmoke) other);
  }

  private boolean equalTo(UnwillingSmoke other) {
    return value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ValueStage builder() {
    return new Builder();
  }

  public interface ValueStage {
    _FinalStage value(@NotNull String value);

    Builder from(UnwillingSmoke other);
  }

  public interface _FinalStage {
    UnwillingSmoke build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ValueStage, _FinalStage {
    private String value;

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UnwillingSmoke other) {
      value(other.getValue());
      return this;
    }

    @java.lang.Override
    @JsonSetter("value")
    public _FinalStage value(@NotNull String value) {
      this.value = Objects.requireNonNull(value, "value must not be null");
      return this;
    }

    @java.lang.Override
    public UnwillingSmoke build() {
      return new UnwillingSmoke(value);
    }
  }
}
