import { AcceptHeaderClient } from "./api/resources/acceptHeader/client/Client.mjs";
import { AliasClient } from "./api/resources/alias/client/Client.mjs";
import { AliasExtendsClient } from "./api/resources/aliasExtends/client/Client.mjs";
import { AllofClient } from "./api/resources/allof/client/Client.mjs";
import { AnyAuthClient } from "./api/resources/anyAuth/client/Client.mjs";
import { ApiWideBasePathClient } from "./api/resources/apiWideBasePath/client/Client.mjs";
import { AudiencesClient } from "./api/resources/audiences/client/Client.mjs";
import { BasicAuthClient } from "./api/resources/basicAuth/client/Client.mjs";
import { BasicAuthEnvironmentVariablesClient } from "./api/resources/basicAuthEnvironmentVariables/client/Client.mjs";
import { BasicAuthPwOmittedClient } from "./api/resources/basicAuthPwOmitted/client/Client.mjs";
import { BearerTokenEnvironmentVariableClient } from "./api/resources/bearerTokenEnvironmentVariable/client/Client.mjs";
import { BytesDownloadClient } from "./api/resources/bytesDownload/client/Client.mjs";
import { BytesUploadClient } from "./api/resources/bytesUpload/client/Client.mjs";
import { ClientSideParamsClient } from "./api/resources/clientSideParams/client/Client.mjs";
import { ContentTypeClient } from "./api/resources/contentType/client/Client.mjs";
import { CrossPackageTypeNamesClient } from "./api/resources/crossPackageTypeNames/client/Client.mjs";
import { CsharpInlineTypesClient } from "./api/resources/csharpInlineTypes/client/Client.mjs";
import { CsharpNamespaceConflictClient } from "./api/resources/csharpNamespaceConflict/client/Client.mjs";
import { CsharpPropertyNameCollisionClient } from "./api/resources/csharpPropertyNameCollision/client/Client.mjs";
import { CsharpReadonlyRequestClient } from "./api/resources/csharpReadonlyRequest/client/Client.mjs";
import { CsharpSystemCollisionClient } from "./api/resources/csharpSystemCollision/client/Client.mjs";
import { CsharpXmlEntitiesClient } from "./api/resources/csharpXmlEntities/client/Client.mjs";
import { EndpointSecurityAuthClient } from "./api/resources/endpointSecurityAuth/client/Client.mjs";
import { EnumClient } from "./api/resources/enum/client/Client.mjs";
import { ErrorPropertyClient } from "./api/resources/errorProperty/client/Client.mjs";
import { ErrorsClient } from "./api/resources/errors/client/Client.mjs";
import { ExamplesClient } from "./api/resources/examples/client/Client.mjs";
import { ExhaustiveClient } from "./api/resources/exhaustive/client/Client.mjs";
import { ExtendsClient } from "./api/resources/extends/client/Client.mjs";
import { ExtraPropertiesClient } from "./api/resources/extraProperties/client/Client.mjs";
import { FileDownloadClient } from "./api/resources/fileDownload/client/Client.mjs";
import { FileUploadClient } from "./api/resources/fileUpload/client/Client.mjs";
import { FoldersClient } from "./api/resources/folders/client/Client.mjs";
import { GoBytesRequestClient } from "./api/resources/goBytesRequest/client/Client.mjs";
import { GoContentTypeClient } from "./api/resources/goContentType/client/Client.mjs";
import { GoDeterministicOrderingClient } from "./api/resources/goDeterministicOrdering/client/Client.mjs";
import { GoOptionalLiteralAliasClient } from "./api/resources/goOptionalLiteralAlias/client/Client.mjs";
import { GoUndiscriminatedUnionWireTestsClient } from "./api/resources/goUndiscriminatedUnionWireTests/client/Client.mjs";
import { HttpHeadClient } from "./api/resources/httpHead/client/Client.mjs";
import { IdempotencyHeadersClient } from "./api/resources/idempotencyHeaders/client/Client.mjs";
import { ImdbClient } from "./api/resources/imdb/client/Client.mjs";
import { InferredAuthExplicitClient } from "./api/resources/inferredAuthExplicit/client/Client.mjs";
import { InferredAuthImplicitClient } from "./api/resources/inferredAuthImplicit/client/Client.mjs";
import { InferredAuthImplicitApiKeyClient } from "./api/resources/inferredAuthImplicitApiKey/client/Client.mjs";
import { InferredAuthImplicitNoExpiryClient } from "./api/resources/inferredAuthImplicitNoExpiry/client/Client.mjs";
import { InferredAuthImplicitReferenceClient } from "./api/resources/inferredAuthImplicitReference/client/Client.mjs";
import { JavaBuilderExtensionClient } from "./api/resources/javaBuilderExtension/client/Client.mjs";
import { JavaCustomPackagePrefixClient } from "./api/resources/javaCustomPackagePrefix/client/Client.mjs";
import { JavaDefaultTimeoutClient } from "./api/resources/javaDefaultTimeout/client/Client.mjs";
import { JavaInlineTypesClient } from "./api/resources/javaInlineTypes/client/Client.mjs";
import { JavaOptionalNullableQueryParamsClient } from "./api/resources/javaOptionalNullableQueryParams/client/Client.mjs";
import { JavaOptionalQueryParamsOverloadsClient } from "./api/resources/javaOptionalQueryParamsOverloads/client/Client.mjs";
import { JavaOutputDirectoryClient } from "./api/resources/javaOutputDirectory/client/Client.mjs";
import { JavaPaginationDeepCursorPathClient } from "./api/resources/javaPaginationDeepCursorPath/client/Client.mjs";
import { JavaPathParamKeyConflictClient } from "./api/resources/javaPathParamKeyConflict/client/Client.mjs";
import { JavaRequiredBodyOptionalHeadersClient } from "./api/resources/javaRequiredBodyOptionalHeaders/client/Client.mjs";
import { JavaSinglePropertyEndpointClient } from "./api/resources/javaSinglePropertyEndpoint/client/Client.mjs";
import { JavaStagedBuilderOrderingClient } from "./api/resources/javaStagedBuilderOrdering/client/Client.mjs";
import { JavaStreamingAcceptHeaderClient } from "./api/resources/javaStreamingAcceptHeader/client/Client.mjs";
import { LicenseClient } from "./api/resources/license/client/Client.mjs";
import { LiteralClient } from "./api/resources/literal/client/Client.mjs";
import { LiteralUserAgentClient } from "./api/resources/literalUserAgent/client/Client.mjs";
import { MixedCaseClient } from "./api/resources/mixedCase/client/Client.mjs";
import { MixedFileDirectoryClient } from "./api/resources/mixedFileDirectory/client/Client.mjs";
import { MultiLineDocsClient } from "./api/resources/multiLineDocs/client/Client.mjs";
import { MultipleRequestBodiesClient } from "./api/resources/multipleRequestBodies/client/Client.mjs";
import { MultiUrlEnvironmentClient } from "./api/resources/multiUrlEnvironment/client/Client.mjs";
import { MultiUrlEnvironmentNoDefaultClient } from "./api/resources/multiUrlEnvironmentNoDefault/client/Client.mjs";
import { MultiUrlEnvironmentReferenceClient } from "./api/resources/multiUrlEnvironmentReference/client/Client.mjs";
import { NoContentResponseClient } from "./api/resources/noContentResponse/client/Client.mjs";
import { NoEnvironmentClient } from "./api/resources/noEnvironment/client/Client.mjs";
import { NoRetriesClient } from "./api/resources/noRetries/client/Client.mjs";
import { NullableClient } from "./api/resources/nullable/client/Client.mjs";
import { NullableAllofExtendsClient } from "./api/resources/nullableAllofExtends/client/Client.mjs";
import { NullableOptionalClient } from "./api/resources/nullableOptional/client/Client.mjs";
import { NullableRequestBodyClient } from "./api/resources/nullableRequestBody/client/Client.mjs";
import { NullTypeClient } from "./api/resources/nullType/client/Client.mjs";
import { OauthClientCredentialsClient } from "./api/resources/oauthClientCredentials/client/Client.mjs";
import { OauthClientCredentialsCustomClient } from "./api/resources/oauthClientCredentialsCustom/client/Client.mjs";
import { OauthClientCredentialsDefaultClient } from "./api/resources/oauthClientCredentialsDefault/client/Client.mjs";
import { OauthClientCredentialsEnvironmentVariablesClient } from "./api/resources/oauthClientCredentialsEnvironmentVariables/client/Client.mjs";
import { OauthClientCredentialsMandatoryAuthClient } from "./api/resources/oauthClientCredentialsMandatoryAuth/client/Client.mjs";
import { OauthClientCredentialsNestedRootClient } from "./api/resources/oauthClientCredentialsNestedRoot/client/Client.mjs";
import { OauthClientCredentialsOpenapiClient } from "./api/resources/oauthClientCredentialsOpenapi/client/Client.mjs";
import { OauthClientCredentialsReferenceClient } from "./api/resources/oauthClientCredentialsReference/client/Client.mjs";
import { OauthClientCredentialsWithVariablesClient } from "./api/resources/oauthClientCredentialsWithVariables/client/Client.mjs";
import { OpenapiRequestBodyRefClient } from "./api/resources/openapiRequestBodyRef/client/Client.mjs";
import { OptionalClient } from "./api/resources/optional/client/Client.mjs";
import { PaginationClient } from "./api/resources/pagination/client/Client.mjs";
import { PaginationCustomClient } from "./api/resources/paginationCustom/client/Client.mjs";
import { PaginationUriPathClient } from "./api/resources/paginationUriPath/client/Client.mjs";
import { PathParametersClient } from "./api/resources/pathParameters/client/Client.mjs";
import { PlainTextClient } from "./api/resources/plainText/client/Client.mjs";
import { PropertyAccessClient } from "./api/resources/propertyAccess/client/Client.mjs";
import { PublicObjectClient } from "./api/resources/publicObject/client/Client.mjs";
import { PythonBackslashEscapeClient } from "./api/resources/pythonBackslashEscape/client/Client.mjs";
import { PythonPositionalSinglePropertyClient } from "./api/resources/pythonPositionalSingleProperty/client/Client.mjs";
import { PythonReservedKeywordSubpackagesClient } from "./api/resources/pythonReservedKeywordSubpackages/client/Client.mjs";
import { QueryParametersClient } from "./api/resources/queryParameters/client/Client.mjs";
import { QueryParametersOpenapiClient } from "./api/resources/queryParametersOpenapi/client/Client.mjs";
import { RequestParametersClient } from "./api/resources/requestParameters/client/Client.mjs";
import { RequiredNullableClient } from "./api/resources/requiredNullable/client/Client.mjs";
import { ReservedKeywordsClient } from "./api/resources/reservedKeywords/client/Client.mjs";
import { ResponsePropertyClient } from "./api/resources/responseProperty/client/Client.mjs";
import { RubyReservedWordPropertiesClient } from "./api/resources/rubyReservedWordProperties/client/Client.mjs";
import { SchemalessRequestBodyExamplesClient } from "./api/resources/schemalessRequestBodyExamples/client/Client.mjs";
import { ServerSentEventExamplesClient } from "./api/resources/serverSentEventExamples/client/Client.mjs";
import { ServerSentEventsClient } from "./api/resources/serverSentEvents/client/Client.mjs";
import { ServerUrlTemplatingClient } from "./api/resources/serverUrlTemplating/client/Client.mjs";
import { SimpleApiClient } from "./api/resources/simpleApi/client/Client.mjs";
import { SimpleFhirClient } from "./api/resources/simpleFhir/client/Client.mjs";
import { SingleUrlEnvironmentDefaultClient } from "./api/resources/singleUrlEnvironmentDefault/client/Client.mjs";
import { SingleUrlEnvironmentNoDefaultClient } from "./api/resources/singleUrlEnvironmentNoDefault/client/Client.mjs";
import { StreamingClient } from "./api/resources/streaming/client/Client.mjs";
import { StreamingParameterClient } from "./api/resources/streamingParameter/client/Client.mjs";
import { TraceClient } from "./api/resources/trace/client/Client.mjs";
import { TsExpressCasingClient } from "./api/resources/tsExpressCasing/client/Client.mjs";
import { TsExtraPropertiesClient } from "./api/resources/tsExtraProperties/client/Client.mjs";
import { TsInlineTypesClient } from "./api/resources/tsInlineTypes/client/Client.mjs";
import { UndiscriminatedUnionsClient } from "./api/resources/undiscriminatedUnions/client/Client.mjs";
import { UndiscriminatedUnionWithResponsePropertyClient } from "./api/resources/undiscriminatedUnionWithResponseProperty/client/Client.mjs";
import { UnionQueryParametersClient } from "./api/resources/unionQueryParameters/client/Client.mjs";
import { UnionsClient } from "./api/resources/unions/client/Client.mjs";
import { UnionsWithLocalDateClient } from "./api/resources/unionsWithLocalDate/client/Client.mjs";
import { UnknownClient } from "./api/resources/unknown/client/Client.mjs";
import { UrlFormEncodedClient } from "./api/resources/urlFormEncoded/client/Client.mjs";
import { ValidationClient } from "./api/resources/validation/client/Client.mjs";
import { VariablesClient } from "./api/resources/variables/client/Client.mjs";
import { VersionClient } from "./api/resources/version/client/Client.mjs";
import { VersionNoDefaultClient } from "./api/resources/versionNoDefault/client/Client.mjs";
import { WebsocketInferredAuthClient } from "./api/resources/websocketInferredAuth/client/Client.mjs";
import { XFernDefaultClient } from "./api/resources/xFernDefault/client/Client.mjs";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.mjs";
import { type NormalizedClientOptionsWithAuth } from "./BaseClient.mjs";
import * as core from "./core/index.mjs";
export declare namespace SeedApiClient {
    type Options = BaseClientOptions;
    interface RequestOptions extends BaseRequestOptions {
    }
}
export declare class SeedApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SeedApiClient.Options>;
    protected _acceptHeader: AcceptHeaderClient | undefined;
    protected _alias: AliasClient | undefined;
    protected _aliasExtends: AliasExtendsClient | undefined;
    protected _allof: AllofClient | undefined;
    protected _anyAuth: AnyAuthClient | undefined;
    protected _apiWideBasePath: ApiWideBasePathClient | undefined;
    protected _audiences: AudiencesClient | undefined;
    protected _basicAuth: BasicAuthClient | undefined;
    protected _basicAuthEnvironmentVariables: BasicAuthEnvironmentVariablesClient | undefined;
    protected _basicAuthPwOmitted: BasicAuthPwOmittedClient | undefined;
    protected _bearerTokenEnvironmentVariable: BearerTokenEnvironmentVariableClient | undefined;
    protected _bytesDownload: BytesDownloadClient | undefined;
    protected _bytesUpload: BytesUploadClient | undefined;
    protected _clientSideParams: ClientSideParamsClient | undefined;
    protected _contentType: ContentTypeClient | undefined;
    protected _crossPackageTypeNames: CrossPackageTypeNamesClient | undefined;
    protected _csharpInlineTypes: CsharpInlineTypesClient | undefined;
    protected _csharpPropertyNameCollision: CsharpPropertyNameCollisionClient | undefined;
    protected _csharpReadonlyRequest: CsharpReadonlyRequestClient | undefined;
    protected _csharpSystemCollision: CsharpSystemCollisionClient | undefined;
    protected _csharpXmlEntities: CsharpXmlEntitiesClient | undefined;
    protected _csharpNamespaceConflict: CsharpNamespaceConflictClient | undefined;
    protected _endpointSecurityAuth: EndpointSecurityAuthClient | undefined;
    protected _enum: EnumClient | undefined;
    protected _errorProperty: ErrorPropertyClient | undefined;
    protected _errors: ErrorsClient | undefined;
    protected _examples: ExamplesClient | undefined;
    protected _exhaustive: ExhaustiveClient | undefined;
    protected _extends: ExtendsClient | undefined;
    protected _extraProperties: ExtraPropertiesClient | undefined;
    protected _fileDownload: FileDownloadClient | undefined;
    protected _fileUpload: FileUploadClient | undefined;
    protected _folders: FoldersClient | undefined;
    protected _goOptionalLiteralAlias: GoOptionalLiteralAliasClient | undefined;
    protected _goBytesRequest: GoBytesRequestClient | undefined;
    protected _goContentType: GoContentTypeClient | undefined;
    protected _goDeterministicOrdering: GoDeterministicOrderingClient | undefined;
    protected _goUndiscriminatedUnionWireTests: GoUndiscriminatedUnionWireTestsClient | undefined;
    protected _httpHead: HttpHeadClient | undefined;
    protected _idempotencyHeaders: IdempotencyHeadersClient | undefined;
    protected _imdb: ImdbClient | undefined;
    protected _inferredAuthExplicit: InferredAuthExplicitClient | undefined;
    protected _inferredAuthImplicit: InferredAuthImplicitClient | undefined;
    protected _inferredAuthImplicitApiKey: InferredAuthImplicitApiKeyClient | undefined;
    protected _inferredAuthImplicitNoExpiry: InferredAuthImplicitNoExpiryClient | undefined;
    protected _inferredAuthImplicitReference: InferredAuthImplicitReferenceClient | undefined;
    protected _javaDefaultTimeout: JavaDefaultTimeoutClient | undefined;
    protected _javaInlineTypes: JavaInlineTypesClient | undefined;
    protected _javaOptionalNullableQueryParams: JavaOptionalNullableQueryParamsClient | undefined;
    protected _javaOptionalQueryParamsOverloads: JavaOptionalQueryParamsOverloadsClient | undefined;
    protected _javaPathParamKeyConflict: JavaPathParamKeyConflictClient | undefined;
    protected _javaRequiredBodyOptionalHeaders: JavaRequiredBodyOptionalHeadersClient | undefined;
    protected _javaBuilderExtension: JavaBuilderExtensionClient | undefined;
    protected _javaCustomPackagePrefix: JavaCustomPackagePrefixClient | undefined;
    protected _javaOutputDirectory: JavaOutputDirectoryClient | undefined;
    protected _javaPaginationDeepCursorPath: JavaPaginationDeepCursorPathClient | undefined;
    protected _javaSinglePropertyEndpoint: JavaSinglePropertyEndpointClient | undefined;
    protected _javaStagedBuilderOrdering: JavaStagedBuilderOrderingClient | undefined;
    protected _javaStreamingAcceptHeader: JavaStreamingAcceptHeaderClient | undefined;
    protected _license: LicenseClient | undefined;
    protected _literal: LiteralClient | undefined;
    protected _literalUserAgent: LiteralUserAgentClient | undefined;
    protected _mixedCase: MixedCaseClient | undefined;
    protected _mixedFileDirectory: MixedFileDirectoryClient | undefined;
    protected _multiUrlEnvironmentReference: MultiUrlEnvironmentReferenceClient | undefined;
    protected _multiLineDocs: MultiLineDocsClient | undefined;
    protected _multiUrlEnvironment: MultiUrlEnvironmentClient | undefined;
    protected _multiUrlEnvironmentNoDefault: MultiUrlEnvironmentNoDefaultClient | undefined;
    protected _multipleRequestBodies: MultipleRequestBodiesClient | undefined;
    protected _noContentResponse: NoContentResponseClient | undefined;
    protected _noEnvironment: NoEnvironmentClient | undefined;
    protected _noRetries: NoRetriesClient | undefined;
    protected _nullType: NullTypeClient | undefined;
    protected _nullable: NullableClient | undefined;
    protected _nullableAllofExtends: NullableAllofExtendsClient | undefined;
    protected _nullableOptional: NullableOptionalClient | undefined;
    protected _nullableRequestBody: NullableRequestBodyClient | undefined;
    protected _oauthClientCredentials: OauthClientCredentialsClient | undefined;
    protected _oauthClientCredentialsCustom: OauthClientCredentialsCustomClient | undefined;
    protected _oauthClientCredentialsDefault: OauthClientCredentialsDefaultClient | undefined;
    protected _oauthClientCredentialsEnvironmentVariables: OauthClientCredentialsEnvironmentVariablesClient | undefined;
    protected _oauthClientCredentialsMandatoryAuth: OauthClientCredentialsMandatoryAuthClient | undefined;
    protected _oauthClientCredentialsNestedRoot: OauthClientCredentialsNestedRootClient | undefined;
    protected _oauthClientCredentialsOpenapi: OauthClientCredentialsOpenapiClient | undefined;
    protected _oauthClientCredentialsReference: OauthClientCredentialsReferenceClient | undefined;
    protected _oauthClientCredentialsWithVariables: OauthClientCredentialsWithVariablesClient | undefined;
    protected _openapiRequestBodyRef: OpenapiRequestBodyRefClient | undefined;
    protected _optional: OptionalClient | undefined;
    protected _pagination: PaginationClient | undefined;
    protected _paginationCustom: PaginationCustomClient | undefined;
    protected _paginationUriPath: PaginationUriPathClient | undefined;
    protected _pathParameters: PathParametersClient | undefined;
    protected _plainText: PlainTextClient | undefined;
    protected _propertyAccess: PropertyAccessClient | undefined;
    protected _publicObject: PublicObjectClient | undefined;
    protected _pythonPositionalSingleProperty: PythonPositionalSinglePropertyClient | undefined;
    protected _pythonBackslashEscape: PythonBackslashEscapeClient | undefined;
    protected _pythonReservedKeywordSubpackages: PythonReservedKeywordSubpackagesClient | undefined;
    protected _queryParametersOpenapi: QueryParametersOpenapiClient | undefined;
    protected _queryParameters: QueryParametersClient | undefined;
    protected _requestParameters: RequestParametersClient | undefined;
    protected _requiredNullable: RequiredNullableClient | undefined;
    protected _reservedKeywords: ReservedKeywordsClient | undefined;
    protected _responseProperty: ResponsePropertyClient | undefined;
    protected _rubyReservedWordProperties: RubyReservedWordPropertiesClient | undefined;
    protected _schemalessRequestBodyExamples: SchemalessRequestBodyExamplesClient | undefined;
    protected _serverUrlTemplating: ServerUrlTemplatingClient | undefined;
    protected _serverSentEventExamples: ServerSentEventExamplesClient | undefined;
    protected _serverSentEvents: ServerSentEventsClient | undefined;
    protected _simpleFhir: SimpleFhirClient | undefined;
    protected _simpleApi: SimpleApiClient | undefined;
    protected _singleUrlEnvironmentDefault: SingleUrlEnvironmentDefaultClient | undefined;
    protected _singleUrlEnvironmentNoDefault: SingleUrlEnvironmentNoDefaultClient | undefined;
    protected _streaming: StreamingClient | undefined;
    protected _streamingParameter: StreamingParameterClient | undefined;
    protected _trace: TraceClient | undefined;
    protected _tsExtraProperties: TsExtraPropertiesClient | undefined;
    protected _tsInlineTypes: TsInlineTypesClient | undefined;
    protected _tsExpressCasing: TsExpressCasingClient | undefined;
    protected _undiscriminatedUnionWithResponseProperty: UndiscriminatedUnionWithResponsePropertyClient | undefined;
    protected _undiscriminatedUnions: UndiscriminatedUnionsClient | undefined;
    protected _unionQueryParameters: UnionQueryParametersClient | undefined;
    protected _unions: UnionsClient | undefined;
    protected _unionsWithLocalDate: UnionsWithLocalDateClient | undefined;
    protected _unknown: UnknownClient | undefined;
    protected _urlFormEncoded: UrlFormEncodedClient | undefined;
    protected _validation: ValidationClient | undefined;
    protected _variables: VariablesClient | undefined;
    protected _version: VersionClient | undefined;
    protected _versionNoDefault: VersionNoDefaultClient | undefined;
    protected _websocketInferredAuth: WebsocketInferredAuthClient | undefined;
    protected _xFernDefault: XFernDefaultClient | undefined;
    constructor(options: SeedApiClient.Options);
    get acceptHeader(): AcceptHeaderClient;
    get alias(): AliasClient;
    get aliasExtends(): AliasExtendsClient;
    get allof(): AllofClient;
    get anyAuth(): AnyAuthClient;
    get apiWideBasePath(): ApiWideBasePathClient;
    get audiences(): AudiencesClient;
    get basicAuth(): BasicAuthClient;
    get basicAuthEnvironmentVariables(): BasicAuthEnvironmentVariablesClient;
    get basicAuthPwOmitted(): BasicAuthPwOmittedClient;
    get bearerTokenEnvironmentVariable(): BearerTokenEnvironmentVariableClient;
    get bytesDownload(): BytesDownloadClient;
    get bytesUpload(): BytesUploadClient;
    get clientSideParams(): ClientSideParamsClient;
    get contentType(): ContentTypeClient;
    get crossPackageTypeNames(): CrossPackageTypeNamesClient;
    get csharpInlineTypes(): CsharpInlineTypesClient;
    get csharpPropertyNameCollision(): CsharpPropertyNameCollisionClient;
    get csharpReadonlyRequest(): CsharpReadonlyRequestClient;
    get csharpSystemCollision(): CsharpSystemCollisionClient;
    get csharpXmlEntities(): CsharpXmlEntitiesClient;
    get csharpNamespaceConflict(): CsharpNamespaceConflictClient;
    get endpointSecurityAuth(): EndpointSecurityAuthClient;
    get enum(): EnumClient;
    get errorProperty(): ErrorPropertyClient;
    get errors(): ErrorsClient;
    get examples(): ExamplesClient;
    get exhaustive(): ExhaustiveClient;
    get extends(): ExtendsClient;
    get extraProperties(): ExtraPropertiesClient;
    get fileDownload(): FileDownloadClient;
    get fileUpload(): FileUploadClient;
    get folders(): FoldersClient;
    get goOptionalLiteralAlias(): GoOptionalLiteralAliasClient;
    get goBytesRequest(): GoBytesRequestClient;
    get goContentType(): GoContentTypeClient;
    get goDeterministicOrdering(): GoDeterministicOrderingClient;
    get goUndiscriminatedUnionWireTests(): GoUndiscriminatedUnionWireTestsClient;
    get httpHead(): HttpHeadClient;
    get idempotencyHeaders(): IdempotencyHeadersClient;
    get imdb(): ImdbClient;
    get inferredAuthExplicit(): InferredAuthExplicitClient;
    get inferredAuthImplicit(): InferredAuthImplicitClient;
    get inferredAuthImplicitApiKey(): InferredAuthImplicitApiKeyClient;
    get inferredAuthImplicitNoExpiry(): InferredAuthImplicitNoExpiryClient;
    get inferredAuthImplicitReference(): InferredAuthImplicitReferenceClient;
    get javaDefaultTimeout(): JavaDefaultTimeoutClient;
    get javaInlineTypes(): JavaInlineTypesClient;
    get javaOptionalNullableQueryParams(): JavaOptionalNullableQueryParamsClient;
    get javaOptionalQueryParamsOverloads(): JavaOptionalQueryParamsOverloadsClient;
    get javaPathParamKeyConflict(): JavaPathParamKeyConflictClient;
    get javaRequiredBodyOptionalHeaders(): JavaRequiredBodyOptionalHeadersClient;
    get javaBuilderExtension(): JavaBuilderExtensionClient;
    get javaCustomPackagePrefix(): JavaCustomPackagePrefixClient;
    get javaOutputDirectory(): JavaOutputDirectoryClient;
    get javaPaginationDeepCursorPath(): JavaPaginationDeepCursorPathClient;
    get javaSinglePropertyEndpoint(): JavaSinglePropertyEndpointClient;
    get javaStagedBuilderOrdering(): JavaStagedBuilderOrderingClient;
    get javaStreamingAcceptHeader(): JavaStreamingAcceptHeaderClient;
    get license(): LicenseClient;
    get literal(): LiteralClient;
    get literalUserAgent(): LiteralUserAgentClient;
    get mixedCase(): MixedCaseClient;
    get mixedFileDirectory(): MixedFileDirectoryClient;
    get multiUrlEnvironmentReference(): MultiUrlEnvironmentReferenceClient;
    get multiLineDocs(): MultiLineDocsClient;
    get multiUrlEnvironment(): MultiUrlEnvironmentClient;
    get multiUrlEnvironmentNoDefault(): MultiUrlEnvironmentNoDefaultClient;
    get multipleRequestBodies(): MultipleRequestBodiesClient;
    get noContentResponse(): NoContentResponseClient;
    get noEnvironment(): NoEnvironmentClient;
    get noRetries(): NoRetriesClient;
    get nullType(): NullTypeClient;
    get nullable(): NullableClient;
    get nullableAllofExtends(): NullableAllofExtendsClient;
    get nullableOptional(): NullableOptionalClient;
    get nullableRequestBody(): NullableRequestBodyClient;
    get oauthClientCredentials(): OauthClientCredentialsClient;
    get oauthClientCredentialsCustom(): OauthClientCredentialsCustomClient;
    get oauthClientCredentialsDefault(): OauthClientCredentialsDefaultClient;
    get oauthClientCredentialsEnvironmentVariables(): OauthClientCredentialsEnvironmentVariablesClient;
    get oauthClientCredentialsMandatoryAuth(): OauthClientCredentialsMandatoryAuthClient;
    get oauthClientCredentialsNestedRoot(): OauthClientCredentialsNestedRootClient;
    get oauthClientCredentialsOpenapi(): OauthClientCredentialsOpenapiClient;
    get oauthClientCredentialsReference(): OauthClientCredentialsReferenceClient;
    get oauthClientCredentialsWithVariables(): OauthClientCredentialsWithVariablesClient;
    get openapiRequestBodyRef(): OpenapiRequestBodyRefClient;
    get optional(): OptionalClient;
    get pagination(): PaginationClient;
    get paginationCustom(): PaginationCustomClient;
    get paginationUriPath(): PaginationUriPathClient;
    get pathParameters(): PathParametersClient;
    get plainText(): PlainTextClient;
    get propertyAccess(): PropertyAccessClient;
    get publicObject(): PublicObjectClient;
    get pythonPositionalSingleProperty(): PythonPositionalSinglePropertyClient;
    get pythonBackslashEscape(): PythonBackslashEscapeClient;
    get pythonReservedKeywordSubpackages(): PythonReservedKeywordSubpackagesClient;
    get queryParametersOpenapi(): QueryParametersOpenapiClient;
    get queryParameters(): QueryParametersClient;
    get requestParameters(): RequestParametersClient;
    get requiredNullable(): RequiredNullableClient;
    get reservedKeywords(): ReservedKeywordsClient;
    get responseProperty(): ResponsePropertyClient;
    get rubyReservedWordProperties(): RubyReservedWordPropertiesClient;
    get schemalessRequestBodyExamples(): SchemalessRequestBodyExamplesClient;
    get serverUrlTemplating(): ServerUrlTemplatingClient;
    get serverSentEventExamples(): ServerSentEventExamplesClient;
    get serverSentEvents(): ServerSentEventsClient;
    get simpleFhir(): SimpleFhirClient;
    get simpleApi(): SimpleApiClient;
    get singleUrlEnvironmentDefault(): SingleUrlEnvironmentDefaultClient;
    get singleUrlEnvironmentNoDefault(): SingleUrlEnvironmentNoDefaultClient;
    get streaming(): StreamingClient;
    get streamingParameter(): StreamingParameterClient;
    get trace(): TraceClient;
    get tsExtraProperties(): TsExtraPropertiesClient;
    get tsInlineTypes(): TsInlineTypesClient;
    get tsExpressCasing(): TsExpressCasingClient;
    get undiscriminatedUnionWithResponseProperty(): UndiscriminatedUnionWithResponsePropertyClient;
    get undiscriminatedUnions(): UndiscriminatedUnionsClient;
    get unionQueryParameters(): UnionQueryParametersClient;
    get unions(): UnionsClient;
    get unionsWithLocalDate(): UnionsWithLocalDateClient;
    get unknown(): UnknownClient;
    get urlFormEncoded(): UrlFormEncodedClient;
    get validation(): ValidationClient;
    get variables(): VariablesClient;
    get version(): VersionClient;
    get versionNoDefault(): VersionNoDefaultClient;
    get websocketInferredAuth(): WebsocketInferredAuthClient;
    get xFernDefault(): XFernDefaultClient;
    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    fetch(input: Request | string | URL, init?: RequestInit, requestOptions?: core.PassthroughRequest.RequestOptions): Promise<Response>;
}
