// Code generated by Fern. DO NOT EDIT.

package users

import (
	context "context"
	http "net/http"

	fern "github.com/go-request-body-pagination/fern"
	core "github.com/go-request-body-pagination/fern/core"
	internal "github.com/go-request-body-pagination/fern/internal"
	option "github.com/go-request-body-pagination/fern/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Pagination endpoint with a top-level cursor field in the request body.
//
// Example:
//
//	request := &fern.ListUsersBodyCursorPaginationRequest{
//	    Cursor: fern.String(
//	        "cursor",
//	    ),
//	    Filter: fern.String(
//	        "filter",
//	    ),
//	}
//	client.Users.ListWithBodyCursorPagination(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListWithBodyCursorPagination(
	ctx context.Context,
	request *fern.ListUsersBodyCursorPaginationRequest,
	opts ...option.RequestOption,
) (*core.Page[*string, *fern.User, *fern.ListUsersResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"",
	)
	endpointURL := baseURL + "/users"
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		nextRequest := *request
		nextRequest.Cursor = pageRequest.Cursor
		nextURL := endpointURL
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         &nextRequest,
			Response:        pageRequest.Response,
		}
	}
	readPageResponse := func(response *fern.ListUsersResponse) *core.PageResponse[*string, *fern.User, *fern.ListUsersResponse] {
		var zeroValue *string
		next := response.GetNextCursor()
		results := response.GetData()
		return &core.PageResponse[*string, *fern.User, *fern.ListUsersResponse]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue,
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.Cursor)
}

// Pagination endpoint with a required top-level cursor field in the request body.
//
// Example:
//
//	request := &fern.ListUsersRequiredBodyCursorPaginationRequest{
//	    Cursor: "cursor",
//	}
//	client.Users.ListWithRequiredBodyCursorPagination(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListWithRequiredBodyCursorPagination(
	ctx context.Context,
	request *fern.ListUsersRequiredBodyCursorPaginationRequest,
	opts ...option.RequestOption,
) (*core.Page[string, *fern.User, *fern.ListUsersRequiredCursorResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"",
	)
	endpointURL := baseURL + "/users/required-cursor"
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[string]) *internal.CallParams {
		nextRequest := *request
		nextRequest.Cursor = pageRequest.Cursor
		nextURL := endpointURL
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         &nextRequest,
			Response:        pageRequest.Response,
		}
	}
	readPageResponse := func(response *fern.ListUsersRequiredCursorResponse) *core.PageResponse[string, *fern.User, *fern.ListUsersRequiredCursorResponse] {
		var zeroValue string
		next := response.GetNextCursor()
		results := response.GetData()
		return &core.PageResponse[string, *fern.User, *fern.ListUsersRequiredCursorResponse]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue,
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.Cursor)
}

// Pagination endpoint with a top-level page field in the request body.
//
// Example:
//
//	request := &fern.ListUsersBodyOffsetPaginationRequest{
//	    Page: fern.Int(
//	        1,
//	    ),
//	    Limit: fern.Int(
//	        1,
//	    ),
//	}
//	client.Users.ListWithBodyOffsetPagination(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListWithBodyOffsetPagination(
	ctx context.Context,
	request *fern.ListUsersBodyOffsetPaginationRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *fern.User, *fern.ListUsersResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"",
	)
	endpointURL := baseURL + "/users/offset"
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		nextRequest := *request
		nextRequest.Page = pageRequest.Cursor
		nextURL := endpointURL
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         &nextRequest,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if request.Page != nil {
		next = *request.Page
	}

	readPageResponse := func(response *fern.ListUsersResponse) *core.PageResponse[*int, *fern.User, *fern.ListUsersResponse] {
		next += 1
		results := response.GetData()
		return &core.PageResponse[*int, *fern.User, *fern.ListUsersResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Pagination endpoint with a nested cursor field in the request body. Nested page properties are
// not supported, so this endpoint is generated without a pager.
//
// Example:
//
//	request := &fern.ListUsersNestedBodyCursorPaginationRequest{
//	    Pagination: &fern.WithCursor{
//	        Cursor: fern.String(
//	            "cursor",
//	        ),
//	    },
//	}
//	client.Users.ListWithNestedBodyCursorPagination(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListWithNestedBodyCursorPagination(
	ctx context.Context,
	request *fern.ListUsersNestedBodyCursorPaginationRequest,
	opts ...option.RequestOption,
) (*fern.ListUsersResponse, error) {
	response, err := c.WithRawResponse.ListWithNestedBodyCursorPagination(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
