# frozen_string_literal: true

require "json"
require "net/http"
require "securerandom"

require_relative "fern_license/internal/json/serializable"
require_relative "fern_license/internal/types/type"
require_relative "fern_license/internal/types/utils"
require_relative "fern_license/internal/types/union"
require_relative "fern_license/internal/errors/constraint_error"
require_relative "fern_license/internal/errors/type_error"
require_relative "fern_license/internal/http/base_request"
require_relative "fern_license/internal/json/request"
require_relative "fern_license/internal/http/raw_client"
require_relative "fern_license/internal/multipart/multipart_encoder"
require_relative "fern_license/internal/multipart/multipart_form_data_part"
require_relative "fern_license/internal/multipart/multipart_form_data"
require_relative "fern_license/internal/multipart/multipart_request"
require_relative "fern_license/internal/types/model/field"
require_relative "fern_license/internal/types/model"
require_relative "fern_license/internal/types/array"
require_relative "fern_license/internal/types/boolean"
require_relative "fern_license/internal/types/enum"
require_relative "fern_license/internal/types/hash"
require_relative "fern_license/internal/types/unknown"
require_relative "fern_license/errors/api_error"
require_relative "fern_license/errors/response_error"
require_relative "fern_license/errors/client_error"
require_relative "fern_license/errors/redirect_error"
require_relative "fern_license/errors/server_error"
require_relative "fern_license/errors/timeout_error"
require_relative "fern_license/internal/iterators/item_iterator"
require_relative "fern_license/internal/iterators/cursor_item_iterator"
require_relative "fern_license/internal/iterators/offset_item_iterator"
require_relative "fern_license/internal/iterators/cursor_page_iterator"
require_relative "fern_license/internal/iterators/offset_page_iterator"
require_relative "fern_license/types/type"
