// This file was auto-generated by Fern from our API Definition.

export type DiscriminatedLiteral =
    | DiscriminatedLiteral.CustomName
    | DiscriminatedLiteral.DefaultName
    | DiscriminatedLiteral.George
    | DiscriminatedLiteral.LiteralGeorge;

export namespace DiscriminatedLiteral {
    export interface CustomName {
        type: "customName";
        value: string;
    }

    export interface DefaultName {
        type: "defaultName";
        value: "Bob";
    }

    export interface George {
        type: "george";
        value: boolean;
    }

    export interface LiteralGeorge {
        type: "literalGeorge";
        value: true;
    }
}
