// This file was auto-generated by Fern from our API Definition.

import type * as FernDefinition from "../../../index.js";

export interface HttpRequestSchema extends FernDefinition.WithName, FernDefinition.WithDocsSchema {
    "content-type"?: string;
    "path-parameters"?: Record<string, FernDefinition.HttpPathParameterSchema>;
    "query-parameters"?: Record<string, FernDefinition.HttpQueryParameterSchema>;
    headers?: Record<string, FernDefinition.HttpHeaderSchema>;
    body?: FernDefinition.HttpRequestBodySchema;
}
