export declare const SpecialEnum: {
    readonly Empty: "";
    readonly HelloWorld: "Hello \\\"World\\\"";
    readonly HelloNWorld: "Hello\\nWorld";
    readonly HelloRWorld: "Hello\\rWorld";
    readonly HelloTWorld: "Hello\\tWorld";
    readonly HelloFWorld: "Hello\\fWorld";
    readonly HelloU0008World: "Hello\\u0008World";
    readonly HelloVWorld: "Hello\\vWorld";
    readonly HelloX00World: "Hello\\x00World";
    readonly HelloU0007World: "Hello\\u0007World";
    readonly HelloU0001World: "Hello\\u0001World";
    readonly HelloU0002World: "Hello\\u0002World";
    readonly HelloU001FWorld: "Hello\\u001FWorld";
    readonly HelloU007FWorld: "Hello\\u007FWorld";
    readonly HelloU009FWorld: "Hello\\u009FWorld";
    readonly Line1NQuoteTTabBackslashRnLine20Null: "Line 1\\n\"Quote\"\\tTab\\\\Backslash\\r\\nLine 2\\0Null";
    readonly Nrtx00U0008Fvu0007: "\\n\\r\\t\\x00\\u0008\\f\\v\\u0007";
    readonly Hello世界: "Hello 世界";
    readonly Cafe: "café";
    readonly "\uD83D\uDE80": "🚀";
    readonly N: "\\\\n";
    readonly "": "\\\\";
    readonly NameJohnAge30CityNewYork: "{\"name\": \"John\", \"age\": 30, \"city\": \"New York\"}";
    readonly SelectFromUsersWhereNameJohnOReilly: "SELECT * FROM users WHERE name = 'John O\\\\'Reilly'";
    readonly CUsersJohnDocumentsFileTxt: "C:\\\\Users\\\\John\\\\Documents\\\\file.txt";
    readonly UsrLocalBinApp: "/usr/local/bin/app";
    readonly D3D2D4: "\\\\d{3}-\\\\d{2}-\\\\d{4}";
    readonly Azaz09Azaz09Azaz2: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}";
    readonly TranscriptTranscriptTypeFinal: "transcript[transcriptType=\"final\"]";
};
export type SpecialEnum = (typeof SpecialEnum)[keyof typeof SpecialEnum];
