/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.exhaustive.resources.types.object.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seed.exhaustive.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ObjectWithRequiredNestedObject.Builder.class)
public final class ObjectWithRequiredNestedObject {
    private final String requiredString;

    private final NestedObjectWithRequiredField requiredObject;

    private final Map<String, Object> additionalProperties;

    private ObjectWithRequiredNestedObject(
            String requiredString,
            NestedObjectWithRequiredField requiredObject,
            Map<String, Object> additionalProperties) {
        this.requiredString = requiredString;
        this.requiredObject = requiredObject;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("requiredString")
    public String getRequiredString() {
        return requiredString;
    }

    @JsonProperty("requiredObject")
    public NestedObjectWithRequiredField getRequiredObject() {
        return requiredObject;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ObjectWithRequiredNestedObject && equalTo((ObjectWithRequiredNestedObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ObjectWithRequiredNestedObject other) {
        return requiredString.equals(other.requiredString) && requiredObject.equals(other.requiredObject);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.requiredString, this.requiredObject);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RequiredStringStage builder() {
        return new Builder();
    }

    public interface RequiredStringStage {
        RequiredObjectStage requiredString(@NotNull String requiredString);

        Builder from(ObjectWithRequiredNestedObject other);
    }

    public interface RequiredObjectStage {
        _FinalStage requiredObject(@NotNull NestedObjectWithRequiredField requiredObject);
    }

    public interface _FinalStage {
        ObjectWithRequiredNestedObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements RequiredStringStage, RequiredObjectStage, _FinalStage {
        private String requiredString;

        private NestedObjectWithRequiredField requiredObject;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ObjectWithRequiredNestedObject other) {
            requiredString(other.getRequiredString());
            requiredObject(other.getRequiredObject());
            return this;
        }

        @java.lang.Override
        @JsonSetter("requiredString")
        public RequiredObjectStage requiredString(@NotNull String requiredString) {
            this.requiredString = Objects.requireNonNull(requiredString, "requiredString must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("requiredObject")
        public _FinalStage requiredObject(@NotNull NestedObjectWithRequiredField requiredObject) {
            this.requiredObject = Objects.requireNonNull(requiredObject, "requiredObject must not be null");
            return this;
        }

        @java.lang.Override
        public ObjectWithRequiredNestedObject build() {
            return new ObjectWithRequiredNestedObject(requiredString, requiredObject, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
