/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.seed.api.model;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.seed.api.core.ObjectMappers;
import java.io.IOException;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;

@JsonDeserialize(
    using = V2V3CustomFiles.Deserializer.class
)
public final class V2V3CustomFiles {
  private final Object value;

  private final int type;

  private V2V3CustomFiles(Object value, int type) {
    this.value = value;
    this.type = type;
  }

  @JsonValue
  public Object get() {
    return this.value;
  }

  @SuppressWarnings("unchecked")
  public <T> T visit(Visitor<T> visitor) {
    if(this.type == 0) {
      return visitor.visit((V2V3CustomFilesZero) this.value);
    } else if(this.type == 1) {
      return visitor.visit((V2V3CustomFilesType) this.value);
    }
    throw new IllegalStateException("Failed to visit value. This should never happen.");
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof V2V3CustomFiles && equalTo((V2V3CustomFiles) other);
  }

  private boolean equalTo(V2V3CustomFiles other) {
    return value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @java.lang.Override
  public String toString() {
    return this.value.toString();
  }

  public static V2V3CustomFiles of(V2V3CustomFilesZero value) {
    return new V2V3CustomFiles(value, 0);
  }

  public static V2V3CustomFiles of(V2V3CustomFilesType value) {
    return new V2V3CustomFiles(value, 1);
  }

  public interface Visitor<T> {
    T visit(V2V3CustomFilesZero value);

    T visit(V2V3CustomFilesType value);
  }

  static final class Deserializer extends StdDeserializer<V2V3CustomFiles> {
    Deserializer() {
      super(V2V3CustomFiles.class);
    }

    @java.lang.Override
    public V2V3CustomFiles deserialize(JsonParser p, DeserializationContext context) throws
        IOException {
      Object value = p.readValueAs(Object.class);
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, V2V3CustomFilesZero.class));
      } catch(RuntimeException e) {
      }
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, V2V3CustomFilesType.class));
      } catch(RuntimeException e) {
      }
      throw new JsonParseException(p, "Failed to deserialize");
    }
  }
}
