// This file was auto-generated by Fern from our API Definition.

/**
 * Tests that unknown/any values containing backslashes in map keys
 * are properly escaped in Go string literals.
 */
export interface TypesObjectWithUnknownField {
    unknown?: unknown | undefined;
}

export namespace TypesObjectWithUnknownField {
    export type Request = Omit<TypesObjectWithUnknownField, "unknown"> & {
        unknown: unknown | undefined;
    };
    export type Response = Omit<TypesObjectWithUnknownField, "unknown"> & {
        unknown: unknown | undefined;
    };
}
