// This file was auto-generated by Fern from our API Definition.

import type * as FernDocsConfig from "../../../index.js";

export interface FolderConfiguration extends FernDocsConfig.WithPermissions, FernDocsConfig.WithFeatureFlags {
    /** The relative path to a folder containing markdown files. Fern will automatically discover and add all markdown files from this folder to the navigation. */
    folder: string;
    /** The title to display for this folder section. If not provided, the folder name will be used. */
    title?: string;
    /** Determines how page titles are derived for files in this folder. Options are `frontmatter` (use the `title` field from the file's frontmatter) or `filename` (derive title from the file name). Defaults to `filename`. */
    titleSource?: FernDocsConfig.TitleSource;
    slug?: string;
    icon?: string;
    hidden?: boolean;
    skipSlug?: boolean;
    /** Deprecated. Use `collapsible` and `collapsed-by-default` instead. */
    collapsed?: boolean;
    /** Whether the section can be expanded/collapsed by the user. */
    collapsible?: boolean;
    /** Whether the section starts collapsed. Only meaningful when `collapsible` is true. Defaults to false (starts open). */
    collapsedByDefault?: boolean;
    availability?: FernDocsConfig.Availability;
}
