// This file was auto-generated by Fern from our API Definition.

/**
 * Configuration for fetching library source from a Git repository.
 */
export interface GitLibraryInputSchema {
    /**
     * GitHub URL to the repository containing the library source code.
     * Example: https://github.com/django/django
     */
    git: string;
    /**
     * Optional path within the repository to the library source.
     * Example: django/core
     */
    subpath?: string;
}
