export * from "./headers/client/requests/index.js";
export * as headers from "./headers/index.js";
export * from "./inlinedrequest/client/requests/index.js";
export * as inlinedrequest from "./inlinedrequest/index.js";
export * from "./multipartform/client/requests/index.js";
export * as multipartform from "./multipartform/index.js";
export * from "./pathparam/client/requests/index.js";
export * as pathparam from "./pathparam/index.js";
export * from "./queryparam/client/requests/index.js";
export * as queryparam from "./queryparam/index.js";
