// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Circle } from "./Circle.js";
import { ShapeZeroType } from "./ShapeZeroType.js";

export const ShapeZero: core.serialization.ObjectSchema<serializers.ShapeZero.Raw, SeedApi.ShapeZero> =
    core.serialization
        .object({
            type: ShapeZeroType,
        })
        .extend(Circle);

export declare namespace ShapeZero {
    export interface Raw extends Circle.Raw {
        type: ShapeZeroType.Raw;
    }
}
