openapi: 3.1.0
info:
  title: Java Nullable Named Request Types API
  version: 0.0.0
paths:
  /postWithNullableNamedRequestBodyType/{id}:
    post:
      operationId: _postWithNullableNamedRequestBodyType
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          examples:
            Example1:
              value: id
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBody'
              examples:
                Example1:
                  value:
                    success: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/NullableObject'
                - type: 'null'
            examples:
              Example1:
                value: {}
  /postWithNonNullableNamedRequestBodyType/{id}:
    post:
      operationId: _postWithNonNullableNamedRequestBodyType
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          examples:
            Example1:
              value: id
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBody'
              examples:
                Example1:
                  value:
                    success: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type:
                    - string
                    - 'null'
                name:
                  type:
                    - string
                    - 'null'
                age:
                  type:
                    - integer
                    - 'null'
            examples:
              Example1:
                value: {}
components:
  schemas:
    NullableObject:
      title: NullableObject
      type: object
      properties:
        id:
          type:
            - string
            - 'null'
        name:
          type:
            - string
            - 'null'
        age:
          type:
            - integer
            - 'null'
    ResponseBody:
      title: ResponseBody
      type: object
      properties:
        success:
          type:
            - boolean
            - 'null'
  securitySchemes: {}
