"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UndiscriminatedUnionWithResponsePropertyClient = void 0;
const BaseClient_js_1 = require("../../../../BaseClient.js");
const Client_js_1 = require("../resources/undiscriminatedUnionWithResponseProperty/client/Client.js");
class UndiscriminatedUnionWithResponsePropertyClient {
    constructor(options) {
        this._options = (0, BaseClient_js_1.normalizeClientOptions)(options);
    }
    get undiscriminatedUnionWithResponseProperty() {
        var _a;
        return ((_a = this._undiscriminatedUnionWithResponseProperty) !== null && _a !== void 0 ? _a : (this._undiscriminatedUnionWithResponseProperty = new Client_js_1.UndiscriminatedUnionWithResponsePropertyClient(this._options)));
    }
}
exports.UndiscriminatedUnionWithResponsePropertyClient = UndiscriminatedUnionWithResponsePropertyClient;
