/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FernDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { GithubLicenseSchema } from "../../license/types/GithubLicenseSchema";
import { ReviewersSchema } from "../../reviewers/types/ReviewersSchema";

export const GithubPullRequestSchema: core.serialization.ObjectSchema<
    serializers.GithubPullRequestSchema.Raw,
    FernDefinition.GithubPullRequestSchema
> = core.serialization.object({
    repository: core.serialization.string(),
    branch: core.serialization.string().optional(),
    license: GithubLicenseSchema.optional(),
    mode: core.serialization.stringLiteral("pull-request"),
    reviewers: ReviewersSchema.optional(),
});

export declare namespace GithubPullRequestSchema {
    export interface Raw {
        repository: string;
        branch?: string | null;
        license?: GithubLicenseSchema.Raw | null;
        mode: "pull-request";
        reviewers?: ReviewersSchema.Raw | null;
    }
}
