# frozen_string_literal: true

require_relative "seed_response_property_client/types/string_response"
require_relative "seed_response_property_client/types/optional_string_response"
require_relative "seed_response_property_client/types/with_metadata"
require_relative "seed_response_property_client/service/types/with_docs"
require_relative "seed_response_property_client/service/types/optional_with_docs"
require_relative "seed_response_property_client/service/types/movie"
require_relative "seed_response_property_client/service/types/response"
