# This file was auto-generated by Fern from our API Definition.

from seed import SeedAliasExtends
from seed import AsyncSeedAliasExtends


async def test_extended_inline_request_body(
    client: SeedAliasExtends, async_client: AsyncSeedAliasExtends
) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert client.extended_inline_request_body(child="string", parent="string") is None  # type: ignore[func-returns-value]

    assert (
        await async_client.extended_inline_request_body(child="string", parent="string")
        is None
    )  # type: ignore[func-returns-value]
