// This file was auto-generated by Fern from our API Definition.

export const UnionWithBasePropertiesOneType = {
    String: "string",
} as const;
export type UnionWithBasePropertiesOneType =
    (typeof UnionWithBasePropertiesOneType)[keyof typeof UnionWithBasePropertiesOneType];
