// service_service
"/"
"/just-file"
"/just-file-with-query-params"
"/just-file-with-optional-query-params"
"/with-content-type"
"/with-form-encoding"
"/"
"/optional-args"
"/inline-type"
"/with-json-property"
"/snippet"
"/with-literal-enum"