/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.inferredAuthExplicit.resources.auth;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.seed.inferredAuthExplicit.core.ClientOptions;
import com.seed.inferredAuthExplicit.core.MediaTypes;
import com.seed.inferredAuthExplicit.core.ObjectMappers;
import com.seed.inferredAuthExplicit.core.RequestOptions;
import com.seed.inferredAuthExplicit.core.SeedInferredAuthExplicitApiException;
import com.seed.inferredAuthExplicit.core.SeedInferredAuthExplicitException;
import com.seed.inferredAuthExplicit.core.SeedInferredAuthExplicitHttpResponse;
import com.seed.inferredAuthExplicit.resources.auth.requests.GetTokenRequest;
import com.seed.inferredAuthExplicit.resources.auth.requests.RefreshTokenRequest;
import com.seed.inferredAuthExplicit.resources.auth.types.TokenResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawAuthClient {
    protected final ClientOptions clientOptions;

    public RawAuthClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public SeedInferredAuthExplicitHttpResponse<TokenResponse> getTokenWithClientCredentials(GetTokenRequest request) {
        return getTokenWithClientCredentials(request, null);
    }

    public SeedInferredAuthExplicitHttpResponse<TokenResponse> getTokenWithClientCredentials(
            GetTokenRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("token")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new SeedInferredAuthExplicitException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new SeedInferredAuthExplicitHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), TokenResponse.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new SeedInferredAuthExplicitApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new SeedInferredAuthExplicitException("Network error executing HTTP request", e);
        }
    }

    public SeedInferredAuthExplicitHttpResponse<TokenResponse> refreshToken(RefreshTokenRequest request) {
        return refreshToken(request, null);
    }

    public SeedInferredAuthExplicitHttpResponse<TokenResponse> refreshToken(
            RefreshTokenRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("token/refresh")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new SeedInferredAuthExplicitException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new SeedInferredAuthExplicitHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), TokenResponse.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new SeedInferredAuthExplicitApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new SeedInferredAuthExplicitException("Network error executing HTTP request", e);
        }
    }
}
