export const FERN_DIRECTORY = "fern"
export const DEFINITION_DIRECTORY = "definition"
export const OPENAPI_DIRECTORY = "openapi"
export const CHANGELOG_DIRECTORY = "changelog"
export const ASYNCAPI_DIRECTORY = "asyncapi"
export const ROOT_API_FILENAME = "api.yml"
export const FERN_PACKAGE_MARKER_FILENAME_NO_EXTENSION = "__package__"
export const FERN_PACKAGE_MARKER_FILENAME = `${FERN_PACKAGE_MARKER_FILENAME_NO_EXTENSION}.yml`
export const DEPENDENCIES_FILENAME = "dependencies.yml"
export const GENERATORS_CONFIGURATION_FILENAME = "generators.yml"
export const DEPENDENCIES_CONFIGURATION_FILENAME = "dependencies.yml"
export const DOCS_CONFIGURATION_FILENAME = "docs.yml"
export const PROJECT_CONFIG_FILENAME = "fern.config.json"
export const DEFAULT_API_WORKSPACE_FOLDER_NAME = "api"
export const FERNIGNORE_FILENAME = ".fernignore"
export const SNIPPET_JSON_FILENAME = "snippet.json"
export const SNIPPET_TEMPLATES_JSON_FILENAME = "snippet-templates.json"
export const RESOLVED_SNIPPET_TEMPLATES_MD = "resolved-snippet-templates.md"
export const DEFAULT_GROUP_GENERATORS_CONFIG_KEY = "default-group"

export const DOCS_DIRECTORY = "docs"
export const APIS_DIRECTORY = "apis"

export const DEFAULT_GROUP_NAME = "local"
