# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

JsonLikeWithNullAndUndefined = typing.Union[
    typing.List["JsonLikeWithNullAndUndefined"],
    typing.Dict[str, "JsonLikeWithNullAndUndefined"],
    typing.Optional[str],
    typing.Optional[int],
    typing.Optional[bool],
]
