// This file was auto-generated by Fern from our API Definition.

export const AuthGetTokenWithClientCredentialsRequestAudience = {
    HttpsApiExampleCom: "https://api.example.com",
} as const;
export type AuthGetTokenWithClientCredentialsRequestAudience =
    (typeof AuthGetTokenWithClientCredentialsRequestAudience)[keyof typeof AuthGetTokenWithClientCredentialsRequestAudience];
