openapi: 3.0.1
info:
  title: property-access
  version: ''
paths:
  /users:
    post:
      operationId: createUser
      tags:
        - ''
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Example1:
                  value:
                    id: id
                    email: email
                    password: password
                    profile:
                      name: name
                      verification:
                        verified: verified
                      ssn: ssn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              Example1:
                value:
                  password: password
                  profile:
                    name: name
                    verification: {}
                    ssn: ssn
components:
  schemas:
    User:
      title: User
      type: object
      description: User object
      properties:
        id:
          type: string
          nullable: true
          description: The unique identifier for the user.
        email:
          type: string
          nullable: true
          description: The email address of the user.
        password:
          type: string
          description: The password for the user.
          example: password
        profile:
          $ref: '#/components/schemas/UserProfile'
          description: User profile object
      required:
        - password
        - profile
    UserProfile:
      title: UserProfile
      type: object
      description: User profile object
      properties:
        name:
          type: string
          description: The name of the user.
        verification:
          $ref: '#/components/schemas/UserProfileVerification'
          description: User profile verification object
        ssn:
          type: string
          description: The social security number of the user.
      required:
        - name
        - verification
        - ssn
    UserProfileVerification:
      title: UserProfileVerification
      type: object
      description: User profile verification object
      properties:
        verified:
          type: string
          nullable: true
          description: User profile verification status
    UserOrAdmin:
      title: UserOrAdmin
      oneOf:
        - $ref: '#/components/schemas/User'
        - $ref: '#/components/schemas/Admin'
      description: Example of an undiscriminated union
    Admin:
      title: Admin
      type: object
      description: Admin user object
      properties:
        adminLevel:
          type: string
          description: The level of admin privileges.
      required:
        - adminLevel
      allOf:
        - $ref: '#/components/schemas/User'
    UserOrAdminDiscriminatedZeroType:
      title: UserOrAdminDiscriminatedZeroType
      type: string
      enum:
        - user
    UserOrAdminDiscriminatedZero:
      title: UserOrAdminDiscriminatedZero
      type: object
      properties:
        type:
          $ref: '#/components/schemas/UserOrAdminDiscriminatedZeroType'
      required:
        - type
      allOf:
        - $ref: '#/components/schemas/User'
    UserOrAdminDiscriminatedAdminType:
      title: UserOrAdminDiscriminatedAdminType
      type: string
      enum:
        - admin
    UserOrAdminDiscriminatedAdmin:
      title: UserOrAdminDiscriminatedAdmin
      type: object
      properties:
        type:
          $ref: '#/components/schemas/UserOrAdminDiscriminatedAdminType'
        admin:
          $ref: '#/components/schemas/Admin'
          nullable: true
      required:
        - type
    UserOrAdminDiscriminatedTwoType:
      title: UserOrAdminDiscriminatedTwoType
      type: string
      enum:
        - empty
    UserOrAdminDiscriminatedTwo:
      title: UserOrAdminDiscriminatedTwo
      type: object
      properties:
        type:
          $ref: '#/components/schemas/UserOrAdminDiscriminatedTwoType'
      required:
        - type
    UserOrAdminDiscriminated:
      title: UserOrAdminDiscriminated
      oneOf:
        - $ref: '#/components/schemas/UserOrAdminDiscriminatedZero'
        - $ref: '#/components/schemas/UserOrAdminDiscriminatedAdmin'
        - $ref: '#/components/schemas/UserOrAdminDiscriminatedTwo'
      description: Example of an discriminated union
    Foo:
      title: Foo
      type: object
      properties:
        normal:
          type: string
        read:
          type: string
          nullable: true
        write:
          type: string
      required:
        - normal
        - write
  securitySchemes: {}
