# frozen_string_literal: true

module SeedTraceClient
  class Submission
    class RunningSubmissionState
      QUEUEING_SUBMISSION = "QUEUEING_SUBMISSION"
      KILLING_HISTORICAL_SUBMISSIONS = "KILLING_HISTORICAL_SUBMISSIONS"
      WRITING_SUBMISSION_TO_FILE = "WRITING_SUBMISSION_TO_FILE"
      COMPILING_SUBMISSION = "COMPILING_SUBMISSION"
      RUNNING_SUBMISSION = "RUNNING_SUBMISSION"
    end
  end
end
