/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernIr from "../../../index";

export interface ListType {
    itemType: FernIr.TypeReference;
    validation: FernIr.ListValidationRules | undefined;
}
