// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../index.js";

export interface Script extends SeedApi.simpleFhir.BaseResource {
    resource_type: Script.ResourceType;
    name: string;
}

export namespace Script {
    export const ResourceType = {
        Script: "Script",
    } as const;
    export type ResourceType = (typeof ResourceType)[keyof typeof ResourceType];
    export type Request = Omit<Script, "resource_type" | "name"> & {
        resource_type: Script.ResourceType;
        name: string;
    };
    export type Response = Omit<Script, "resource_type" | "name"> & {
        resource_type: Script.ResourceType;
        name: string;
    };
}
