# frozen_string_literal: true

require_relative "seed_request_parameters_client/user/types/user"
require_relative "seed_request_parameters_client/user/types/nested_user"
require_relative "seed_request_parameters_client/user/types/create_username_body"
require_relative "seed_request_parameters_client/user/types/create_username_body_optional_properties"
