// This file was auto-generated by Fern from our API Definition.

import type * as FernIr from "../../../../../index.js";

export interface Name {
    originalName: string;
    camelCase: FernIr.dynamic.SafeAndUnsafeString | undefined;
    pascalCase: FernIr.dynamic.SafeAndUnsafeString | undefined;
    snakeCase: FernIr.dynamic.SafeAndUnsafeString | undefined;
    screamingSnakeCase: FernIr.dynamic.SafeAndUnsafeString | undefined;
}
