export { serialization as V36 } from "@fern-api/ir-sdk";
export * as V23 from "@fern-fern/ir-v23-sdk/serialization";
export * as V24 from "@fern-fern/ir-v24-sdk/serialization";
export * as V25 from "@fern-fern/ir-v25-sdk/serialization";
export * as V26 from "@fern-fern/ir-v26-sdk/serialization";
export * as V27 from "@fern-fern/ir-v27-sdk/serialization";
export * as V28 from "@fern-fern/ir-v28-sdk/serialization";
export * as V29 from "@fern-fern/ir-v29-sdk/serialization";
export * as V30 from "@fern-fern/ir-v30-sdk/serialization";
export * as V31 from "@fern-fern/ir-v31-sdk/serialization";
export * as V32 from "@fern-fern/ir-v32-sdk/serialization";
export * as V33 from "@fern-fern/ir-v33-sdk/serialization";
export * as V34 from "@fern-fern/ir-v34-sdk/serialization";
export * as V35 from "@fern-fern/ir-v35-sdk/serialization";
