/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.api;

import com.seed.api.core.ClientOptions;
import com.seed.api.core.RequestOptions;
import com.seed.api.requests.NonNullableObject;
import com.seed.api.requests.PostWithNullableNamedRequestBodyTypeRequest;
import com.seed.api.types.ResponseBody;

public class SeedApiClient {
    protected final ClientOptions clientOptions;

    private final RawSeedApiClient rawClient;

    public SeedApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSeedApiClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSeedApiClient withRawResponse() {
        return this.rawClient;
    }

    public ResponseBody postWithNullableNamedRequestBodyType(
            String id, PostWithNullableNamedRequestBodyTypeRequest request) {
        return this.rawClient.postWithNullableNamedRequestBodyType(id, request).body();
    }

    public ResponseBody postWithNullableNamedRequestBodyType(
            String id, PostWithNullableNamedRequestBodyTypeRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .postWithNullableNamedRequestBodyType(id, request, requestOptions)
                .body();
    }

    public ResponseBody postWithNonNullableNamedRequestBodyType(String id) {
        return this.rawClient.postWithNonNullableNamedRequestBodyType(id).body();
    }

    public ResponseBody postWithNonNullableNamedRequestBodyType(String id, NonNullableObject request) {
        return this.rawClient
                .postWithNonNullableNamedRequestBodyType(id, request)
                .body();
    }

    public ResponseBody postWithNonNullableNamedRequestBodyType(
            String id, NonNullableObject request, RequestOptions requestOptions) {
        return this.rawClient
                .postWithNonNullableNamedRequestBodyType(id, request, requestOptions)
                .body();
    }

    public static SeedApiClientBuilder builder() {
        return new SeedApiClientBuilder();
    }
}
