openapi: 3.1.0
info:
  title: java-websocket-shared-discriminator
  version: 0.0.0
paths: {}
components:
  schemas:
    SendEvent:
      title: SendEvent
      type: object
      properties:
        text:
          type: string
      required:
        - text
    ConversationHistoryMessage:
      title: ConversationHistoryMessage
      type: object
      properties:
        type:
          type: string
          const: History
        role:
          type: string
        content:
          type: string
      required:
        - type
        - role
        - content
    FunctionCallHistoryMessage:
      title: FunctionCallHistoryMessage
      type: object
      properties:
        type:
          type: string
          const: History
        function_calls:
          type: array
          items:
            $ref: '#/components/schemas/FunctionCall'
      required:
        - type
        - function_calls
    ConversationTextMessage:
      title: ConversationTextMessage
      type: object
      properties:
        type:
          type: string
          const: ConversationText
        text:
          type: string
        confidence:
          type: number
          format: double
      required:
        - type
        - text
        - confidence
    FunctionCall:
      title: FunctionCall
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        arguments:
          type: string
      required:
        - id
        - name
        - arguments
  securitySchemes: {}
