"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.inferredAuthImplicit = exports.inferredAuthExplicit = exports.imdb = exports.idempotencyHeaders = exports.httpHead = exports.goUndiscriminatedUnionWireTests = exports.goSubpackageCollision = exports.goOptionalLiteralAlias = exports.goNestedCrossPackage = exports.goDeterministicOrdering = exports.goContentType = exports.goBytesRequest = exports.folders = exports.fileUpload = exports.fileDownload = exports.extraProperties = exports.extends_ = exports.exhaustive = exports.examples = exports.errors = exports.errorProperty = exports.enum_ = exports.endpointSecurityAuth = exports.emptyClients = exports.dollarStringExamples = exports.csharpXmlEntities = exports.csharpSystemCollision = exports.csharpReadonlyRequest = exports.csharpPropertyNameCollision = exports.csharpNamespaceConflict = exports.csharpInlineTypes = exports.crossPackageTypeNames = exports.contentType = exports.clientSideParams = exports.circularReferencesExtends = exports.circularReferencesAdvanced = exports.circularReferences = exports.bytesUpload = exports.bytesDownload = exports.bearerTokenEnvironmentVariable = exports.basicAuthPwOmitted = exports.basicAuthEnvironmentVariables = exports.basicAuth = exports.audiences = exports.apiWideBasePath = exports.anyAuth = exports.allof = exports.aliasExtends = exports.alias = exports.acceptHeader = void 0;
exports.openapiRequestBodyRef = exports.objectsWithImports = exports.object = exports.oauthClientCredentialsWithVariables = exports.oauthClientCredentialsReference = exports.oauthClientCredentialsOpenapi = exports.oauthClientCredentialsNestedRoot = exports.oauthClientCredentialsMandatoryAuth = exports.oauthClientCredentialsEnvironmentVariables = exports.oauthClientCredentialsDefault = exports.oauthClientCredentialsCustom = exports.oauthClientCredentials = exports.nullType = exports.nullableRequestBody = exports.nullableOptional = exports.nullableAllofExtends = exports.nullable = exports.noRetries = exports.noEnvironment = exports.noContentResponse = exports.multiUrlEnvironmentReference = exports.multiUrlEnvironmentNoDefault = exports.multiUrlEnvironment = exports.multipleRequestBodies = exports.multiLineDocs = exports.mixedFileDirectory = exports.mixedCase = exports.literalUserAgent = exports.literalsUnions = exports.literal = exports.license = exports.javaWithPropertyConflict = exports.javaWebsocketSharedDiscriminator = exports.javaStreamingAcceptHeader = exports.javaStagedBuilderOrdering = exports.javaSinglePropertyEndpoint = exports.javaRequiredBodyOptionalHeaders = exports.javaPathParamKeyConflict = exports.javaPaginationDeepCursorPath = exports.javaOutputDirectory = exports.javaOptionalQueryParamsOverloads = exports.javaOptionalNullableQueryParams = exports.javaManyProperties = exports.javaInlineTypes = exports.javaDefaultTimeout = exports.javaCustomPackagePrefix = exports.javaBuilderExtension = exports.inferredAuthImplicitReference = exports.inferredAuthImplicitNoExpiry = exports.inferredAuthImplicitApiKey = void 0;
exports.xFernDefault = exports.websocketMultiUrl = exports.websocketInferredAuth = exports.websocketBearerAuth = exports.websocket = exports.webhooks = exports.webhookAudience = exports.versionNoDefault = exports.version = exports.variables = exports.validation = exports.urlFormEncoded = exports.unknown = exports.unionsWithLocalDate = exports.unions = exports.unionQueryParameters = exports.undiscriminatedUnionWithResponseProperty = exports.undiscriminatedUnions = exports.tsInlineTypes = exports.tsExtraProperties = exports.tsExpressCasing = exports.trace = exports.streamingParameter = exports.streaming = exports.singleUrlEnvironmentNoDefault = exports.singleUrlEnvironmentDefault = exports.simpleFhir = exports.simpleApi = exports.serverUrlTemplating = exports.serverSentEvents = exports.serverSentEventExamples = exports.schemalessRequestBodyExamples = exports.rubyReservedWordProperties = exports.responseProperty = exports.reservedKeywords = exports.requiredNullable = exports.requestParameters = exports.queryParametersOpenapi = exports.queryParameters = exports.pythonReservedKeywordSubpackages = exports.pythonPositionalSingleProperty = exports.pythonBackslashEscape = exports.publicObject = exports.propertyAccess = exports.plainText = exports.pathParameters = exports.paginationUriPath = exports.paginationCustom = exports.pagination = exports.optional = void 0;
exports.acceptHeader = __importStar(require("./acceptHeader/index.js"));
exports.alias = __importStar(require("./alias/index.js"));
exports.aliasExtends = __importStar(require("./aliasExtends/index.js"));
exports.allof = __importStar(require("./allof/index.js"));
exports.anyAuth = __importStar(require("./anyAuth/index.js"));
exports.apiWideBasePath = __importStar(require("./apiWideBasePath/index.js"));
exports.audiences = __importStar(require("./audiences/index.js"));
exports.basicAuth = __importStar(require("./basicAuth/index.js"));
exports.basicAuthEnvironmentVariables = __importStar(require("./basicAuthEnvironmentVariables/index.js"));
exports.basicAuthPwOmitted = __importStar(require("./basicAuthPwOmitted/index.js"));
exports.bearerTokenEnvironmentVariable = __importStar(require("./bearerTokenEnvironmentVariable/index.js"));
exports.bytesDownload = __importStar(require("./bytesDownload/index.js"));
exports.bytesUpload = __importStar(require("./bytesUpload/index.js"));
exports.circularReferences = __importStar(require("./circularReferences/index.js"));
exports.circularReferencesAdvanced = __importStar(require("./circularReferencesAdvanced/index.js"));
exports.circularReferencesExtends = __importStar(require("./circularReferencesExtends/index.js"));
exports.clientSideParams = __importStar(require("./clientSideParams/index.js"));
exports.contentType = __importStar(require("./contentType/index.js"));
exports.crossPackageTypeNames = __importStar(require("./crossPackageTypeNames/index.js"));
exports.csharpInlineTypes = __importStar(require("./csharpInlineTypes/index.js"));
exports.csharpNamespaceConflict = __importStar(require("./csharpNamespaceConflict/index.js"));
exports.csharpPropertyNameCollision = __importStar(require("./csharpPropertyNameCollision/index.js"));
exports.csharpReadonlyRequest = __importStar(require("./csharpReadonlyRequest/index.js"));
exports.csharpSystemCollision = __importStar(require("./csharpSystemCollision/index.js"));
exports.csharpXmlEntities = __importStar(require("./csharpXmlEntities/index.js"));
exports.dollarStringExamples = __importStar(require("./dollarStringExamples/index.js"));
exports.emptyClients = __importStar(require("./emptyClients/index.js"));
exports.endpointSecurityAuth = __importStar(require("./endpointSecurityAuth/index.js"));
exports.enum_ = __importStar(require("./enum/index.js"));
exports.errorProperty = __importStar(require("./errorProperty/index.js"));
exports.errors = __importStar(require("./errors/index.js"));
exports.examples = __importStar(require("./examples/index.js"));
exports.exhaustive = __importStar(require("./exhaustive/index.js"));
exports.extends_ = __importStar(require("./extends/index.js"));
exports.extraProperties = __importStar(require("./extraProperties/index.js"));
exports.fileDownload = __importStar(require("./fileDownload/index.js"));
exports.fileUpload = __importStar(require("./fileUpload/index.js"));
exports.folders = __importStar(require("./folders/index.js"));
exports.goBytesRequest = __importStar(require("./goBytesRequest/index.js"));
exports.goContentType = __importStar(require("./goContentType/index.js"));
exports.goDeterministicOrdering = __importStar(require("./goDeterministicOrdering/index.js"));
exports.goNestedCrossPackage = __importStar(require("./goNestedCrossPackage/index.js"));
exports.goOptionalLiteralAlias = __importStar(require("./goOptionalLiteralAlias/index.js"));
exports.goSubpackageCollision = __importStar(require("./goSubpackageCollision/index.js"));
exports.goUndiscriminatedUnionWireTests = __importStar(require("./goUndiscriminatedUnionWireTests/index.js"));
exports.httpHead = __importStar(require("./httpHead/index.js"));
exports.idempotencyHeaders = __importStar(require("./idempotencyHeaders/index.js"));
exports.imdb = __importStar(require("./imdb/index.js"));
exports.inferredAuthExplicit = __importStar(require("./inferredAuthExplicit/index.js"));
exports.inferredAuthImplicit = __importStar(require("./inferredAuthImplicit/index.js"));
exports.inferredAuthImplicitApiKey = __importStar(require("./inferredAuthImplicitApiKey/index.js"));
exports.inferredAuthImplicitNoExpiry = __importStar(require("./inferredAuthImplicitNoExpiry/index.js"));
exports.inferredAuthImplicitReference = __importStar(require("./inferredAuthImplicitReference/index.js"));
exports.javaBuilderExtension = __importStar(require("./javaBuilderExtension/index.js"));
exports.javaCustomPackagePrefix = __importStar(require("./javaCustomPackagePrefix/index.js"));
exports.javaDefaultTimeout = __importStar(require("./javaDefaultTimeout/index.js"));
exports.javaInlineTypes = __importStar(require("./javaInlineTypes/index.js"));
exports.javaManyProperties = __importStar(require("./javaManyProperties/index.js"));
exports.javaOptionalNullableQueryParams = __importStar(require("./javaOptionalNullableQueryParams/index.js"));
exports.javaOptionalQueryParamsOverloads = __importStar(require("./javaOptionalQueryParamsOverloads/index.js"));
exports.javaOutputDirectory = __importStar(require("./javaOutputDirectory/index.js"));
exports.javaPaginationDeepCursorPath = __importStar(require("./javaPaginationDeepCursorPath/index.js"));
exports.javaPathParamKeyConflict = __importStar(require("./javaPathParamKeyConflict/index.js"));
exports.javaRequiredBodyOptionalHeaders = __importStar(require("./javaRequiredBodyOptionalHeaders/index.js"));
exports.javaSinglePropertyEndpoint = __importStar(require("./javaSinglePropertyEndpoint/index.js"));
exports.javaStagedBuilderOrdering = __importStar(require("./javaStagedBuilderOrdering/index.js"));
exports.javaStreamingAcceptHeader = __importStar(require("./javaStreamingAcceptHeader/index.js"));
exports.javaWebsocketSharedDiscriminator = __importStar(require("./javaWebsocketSharedDiscriminator/index.js"));
exports.javaWithPropertyConflict = __importStar(require("./javaWithPropertyConflict/index.js"));
exports.license = __importStar(require("./license/index.js"));
exports.literal = __importStar(require("./literal/index.js"));
exports.literalsUnions = __importStar(require("./literalsUnions/index.js"));
exports.literalUserAgent = __importStar(require("./literalUserAgent/index.js"));
exports.mixedCase = __importStar(require("./mixedCase/index.js"));
exports.mixedFileDirectory = __importStar(require("./mixedFileDirectory/index.js"));
exports.multiLineDocs = __importStar(require("./multiLineDocs/index.js"));
exports.multipleRequestBodies = __importStar(require("./multipleRequestBodies/index.js"));
exports.multiUrlEnvironment = __importStar(require("./multiUrlEnvironment/index.js"));
exports.multiUrlEnvironmentNoDefault = __importStar(require("./multiUrlEnvironmentNoDefault/index.js"));
exports.multiUrlEnvironmentReference = __importStar(require("./multiUrlEnvironmentReference/index.js"));
exports.noContentResponse = __importStar(require("./noContentResponse/index.js"));
exports.noEnvironment = __importStar(require("./noEnvironment/index.js"));
exports.noRetries = __importStar(require("./noRetries/index.js"));
exports.nullable = __importStar(require("./nullable/index.js"));
exports.nullableAllofExtends = __importStar(require("./nullableAllofExtends/index.js"));
exports.nullableOptional = __importStar(require("./nullableOptional/index.js"));
exports.nullableRequestBody = __importStar(require("./nullableRequestBody/index.js"));
exports.nullType = __importStar(require("./nullType/index.js"));
exports.oauthClientCredentials = __importStar(require("./oauthClientCredentials/index.js"));
exports.oauthClientCredentialsCustom = __importStar(require("./oauthClientCredentialsCustom/index.js"));
exports.oauthClientCredentialsDefault = __importStar(require("./oauthClientCredentialsDefault/index.js"));
exports.oauthClientCredentialsEnvironmentVariables = __importStar(require("./oauthClientCredentialsEnvironmentVariables/index.js"));
exports.oauthClientCredentialsMandatoryAuth = __importStar(require("./oauthClientCredentialsMandatoryAuth/index.js"));
exports.oauthClientCredentialsNestedRoot = __importStar(require("./oauthClientCredentialsNestedRoot/index.js"));
exports.oauthClientCredentialsOpenapi = __importStar(require("./oauthClientCredentialsOpenapi/index.js"));
exports.oauthClientCredentialsReference = __importStar(require("./oauthClientCredentialsReference/index.js"));
exports.oauthClientCredentialsWithVariables = __importStar(require("./oauthClientCredentialsWithVariables/index.js"));
exports.object = __importStar(require("./object/index.js"));
exports.objectsWithImports = __importStar(require("./objectsWithImports/index.js"));
exports.openapiRequestBodyRef = __importStar(require("./openapiRequestBodyRef/index.js"));
exports.optional = __importStar(require("./optional/index.js"));
exports.pagination = __importStar(require("./pagination/index.js"));
exports.paginationCustom = __importStar(require("./paginationCustom/index.js"));
exports.paginationUriPath = __importStar(require("./paginationUriPath/index.js"));
exports.pathParameters = __importStar(require("./pathParameters/index.js"));
exports.plainText = __importStar(require("./plainText/index.js"));
exports.propertyAccess = __importStar(require("./propertyAccess/index.js"));
exports.publicObject = __importStar(require("./publicObject/index.js"));
exports.pythonBackslashEscape = __importStar(require("./pythonBackslashEscape/index.js"));
exports.pythonPositionalSingleProperty = __importStar(require("./pythonPositionalSingleProperty/index.js"));
exports.pythonReservedKeywordSubpackages = __importStar(require("./pythonReservedKeywordSubpackages/index.js"));
exports.queryParameters = __importStar(require("./queryParameters/index.js"));
exports.queryParametersOpenapi = __importStar(require("./queryParametersOpenapi/index.js"));
exports.requestParameters = __importStar(require("./requestParameters/index.js"));
exports.requiredNullable = __importStar(require("./requiredNullable/index.js"));
exports.reservedKeywords = __importStar(require("./reservedKeywords/index.js"));
exports.responseProperty = __importStar(require("./responseProperty/index.js"));
exports.rubyReservedWordProperties = __importStar(require("./rubyReservedWordProperties/index.js"));
exports.schemalessRequestBodyExamples = __importStar(require("./schemalessRequestBodyExamples/index.js"));
exports.serverSentEventExamples = __importStar(require("./serverSentEventExamples/index.js"));
exports.serverSentEvents = __importStar(require("./serverSentEvents/index.js"));
exports.serverUrlTemplating = __importStar(require("./serverUrlTemplating/index.js"));
exports.simpleApi = __importStar(require("./simpleApi/index.js"));
exports.simpleFhir = __importStar(require("./simpleFhir/index.js"));
exports.singleUrlEnvironmentDefault = __importStar(require("./singleUrlEnvironmentDefault/index.js"));
exports.singleUrlEnvironmentNoDefault = __importStar(require("./singleUrlEnvironmentNoDefault/index.js"));
exports.streaming = __importStar(require("./streaming/index.js"));
exports.streamingParameter = __importStar(require("./streamingParameter/index.js"));
exports.trace = __importStar(require("./trace/index.js"));
exports.tsExpressCasing = __importStar(require("./tsExpressCasing/index.js"));
exports.tsExtraProperties = __importStar(require("./tsExtraProperties/index.js"));
exports.tsInlineTypes = __importStar(require("./tsInlineTypes/index.js"));
exports.undiscriminatedUnions = __importStar(require("./undiscriminatedUnions/index.js"));
exports.undiscriminatedUnionWithResponseProperty = __importStar(require("./undiscriminatedUnionWithResponseProperty/index.js"));
exports.unionQueryParameters = __importStar(require("./unionQueryParameters/index.js"));
exports.unions = __importStar(require("./unions/index.js"));
exports.unionsWithLocalDate = __importStar(require("./unionsWithLocalDate/index.js"));
exports.unknown = __importStar(require("./unknown/index.js"));
exports.urlFormEncoded = __importStar(require("./urlFormEncoded/index.js"));
exports.validation = __importStar(require("./validation/index.js"));
exports.variables = __importStar(require("./variables/index.js"));
exports.version = __importStar(require("./version/index.js"));
exports.versionNoDefault = __importStar(require("./versionNoDefault/index.js"));
exports.webhookAudience = __importStar(require("./webhookAudience/index.js"));
exports.webhooks = __importStar(require("./webhooks/index.js"));
exports.websocket = __importStar(require("./websocket/index.js"));
exports.websocketBearerAuth = __importStar(require("./websocketBearerAuth/index.js"));
exports.websocketInferredAuth = __importStar(require("./websocketInferredAuth/index.js"));
exports.websocketMultiUrl = __importStar(require("./websocketMultiUrl/index.js"));
exports.xFernDefault = __importStar(require("./xFernDefault/index.js"));
