// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/fern-api/empty/core"
	imdb "github.com/fern-api/empty/imdb"
	internal "github.com/fern-api/empty/internal"
	option "github.com/fern-api/empty/option"
)

type Client struct {
	Imdb *imdb.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Imdb:    imdb.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
