/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.seed.api.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seed.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = NotificationMethodZero.Builder.class
)
public final class NotificationMethodZero implements IEmailNotification {
  private final String emailAddress;

  private final String subject;

  private final Optional<String> htmlContent;

  private final NotificationMethodZeroType type;

  private NotificationMethodZero(String emailAddress, String subject, Optional<String> htmlContent,
      NotificationMethodZeroType type) {
    this.emailAddress = emailAddress;
    this.subject = subject;
    this.htmlContent = htmlContent;
    this.type = type;
  }

  @JsonProperty("emailAddress")
  @java.lang.Override
  public String getEmailAddress() {
    return emailAddress;
  }

  @JsonProperty("subject")
  @java.lang.Override
  public String getSubject() {
    return subject;
  }

  @JsonProperty("htmlContent")
  @java.lang.Override
  public Optional<String> getHtmlContent() {
    return htmlContent;
  }

  @JsonProperty("type")
  public NotificationMethodZeroType getType() {
    return type;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof NotificationMethodZero && equalTo((NotificationMethodZero) other);
  }

  private boolean equalTo(NotificationMethodZero other) {
    return emailAddress.equals(other.emailAddress) && subject.equals(other.subject) && htmlContent.equals(other.htmlContent) && type.equals(other.type);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.emailAddress, this.subject, this.htmlContent, this.type);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EmailAddressStage builder() {
    return new Builder();
  }

  public interface EmailAddressStage {
    SubjectStage emailAddress(String emailAddress);

    Builder from(NotificationMethodZero other);
  }

  public interface SubjectStage {
    TypeStage subject(String subject);
  }

  public interface TypeStage {
    _FinalStage type(NotificationMethodZeroType type);
  }

  public interface _FinalStage {
    NotificationMethodZero build();

    _FinalStage htmlContent(Optional<String> htmlContent);

    _FinalStage htmlContent(String htmlContent);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EmailAddressStage, SubjectStage, TypeStage, _FinalStage {
    private String emailAddress;

    private String subject;

    private NotificationMethodZeroType type;

    private Optional<String> htmlContent = Optional.empty();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(NotificationMethodZero other) {
      emailAddress(other.getEmailAddress());
      subject(other.getSubject());
      htmlContent(other.getHtmlContent());
      type(other.getType());
      return this;
    }

    @java.lang.Override
    @JsonSetter("emailAddress")
    public SubjectStage emailAddress(String emailAddress) {
      this.emailAddress = Objects.requireNonNull(emailAddress, "emailAddress must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("subject")
    public TypeStage subject(String subject) {
      this.subject = Objects.requireNonNull(subject, "subject must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(NotificationMethodZeroType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage htmlContent(String htmlContent) {
      this.htmlContent = Optional.ofNullable(htmlContent);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "htmlContent",
        nulls = Nulls.SKIP
    )
    public _FinalStage htmlContent(Optional<String> htmlContent) {
      this.htmlContent = htmlContent;
      return this;
    }

    @java.lang.Override
    public NotificationMethodZero build() {
      return new NotificationMethodZero(emailAddress, subject, htmlContent, type);
    }
  }
}
