import { FernIr } from "@fern-api/ir-sdk";
import { AbstractConverter, AbstractConverterContext, ExampleConverter } from "@fern-api/v3-importer-commons";

import { FernGlobalHeadersExtension } from "../extensions/x-fern-global-headers.js";

function convertDefaultToLiteral(defaultValue: unknown): FernIr.Literal | undefined {
    if (defaultValue == null) {
        return undefined;
    }
    if (typeof defaultValue === "string") {
        return FernIr.Literal.string(defaultValue);
    }
    if (typeof defaultValue === "boolean") {
        return FernIr.Literal.boolean(defaultValue);
    }
    // Non-string/non-boolean defaults (e.g., numbers) are not representable as
    // Literal values, so we silently skip them here.
    return undefined;
}

export function convertGlobalHeadersExtension({
    globalHeaders,
    context
}: {
    globalHeaders: FernGlobalHeadersExtension.GlobalHeaderExtension[];
    context: AbstractConverterContext<object>;
}): FernIr.HttpHeader[] {
    return globalHeaders.map((header) => ({
        name: context.casingsGenerator.generateNameAndWireValue({
            name: header.name ?? "",
            wireValue: header.header
        }),
        valueType: header.optional ? AbstractConverter.OPTIONAL_STRING : AbstractConverter.STRING,
        env: header.env,
        v2Examples: header.optional ? undefined : constructGlobalHeaderExample({ header, context }),
        availability: undefined,
        docs: undefined,
        clientDefault: convertDefaultToLiteral(header["x-fern-default"])
    }));
}

function constructGlobalHeaderExample({
    header,
    context
}: {
    header: FernGlobalHeadersExtension.GlobalHeaderExtension;
    context: AbstractConverterContext<object>;
}): FernIr.V2SchemaExamples {
    const globalHeaderExampleConverter = new ExampleConverter({
        breadcrumbs: [],
        context,
        schema: { type: "string" },
        example: header.header
    });
    const { validExample: example } = globalHeaderExampleConverter.convert();
    return {
        userSpecifiedExamples: {},
        autogeneratedExamples: {
            globalHeaderExample: example
        }
    };
}
