// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../index.js";

export interface V2V3GetGeneratedTestCaseTemplateFileRequest {
    template: SeedApi.V2V3TestCaseTemplate;
}
