// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FlushedEventType } from "./FlushedEventType.js";

export const FlushedEvent: core.serialization.ObjectSchema<serializers.FlushedEvent.Raw, SeedApi.FlushedEvent> =
    core.serialization.object({
        type: FlushedEventType,
    });

export declare namespace FlushedEvent {
    export interface Raw {
        type: FlushedEventType.Raw;
    }
}
