*
!generators/typescript/sdk/cli/browser-docker/cache_heavy_dependencies.sh
!generators/typescript/asIs/
!generators/typescript/utils/core-utilities/
!generators/typescript/sdk/cli/browser-docker/dist/browserCli.cjs