// This file was auto-generated by Fern from our API Definition.

import * as FernIr from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { BytesRequest } from "./BytesRequest.js";
import { FileUploadRequest } from "./FileUploadRequest.js";
import { HttpRequestBodyReference } from "./HttpRequestBodyReference.js";
import { InlinedRequestBody } from "./InlinedRequestBody.js";

export const HttpRequestBody: core.serialization.Schema<serializers.HttpRequestBody.Raw, FernIr.HttpRequestBody> =
    core.serialization
        .union("type", {
            inlinedRequestBody: InlinedRequestBody,
            reference: HttpRequestBodyReference,
            fileUpload: FileUploadRequest,
            bytes: BytesRequest,
        })
        .transform<FernIr.HttpRequestBody>({
            transform: (value) => {
                switch (value.type) {
                    case "inlinedRequestBody":
                        return FernIr.HttpRequestBody.inlinedRequestBody(value);
                    case "reference":
                        return FernIr.HttpRequestBody.reference(value);
                    case "fileUpload":
                        return FernIr.HttpRequestBody.fileUpload(value);
                    case "bytes":
                        return FernIr.HttpRequestBody.bytes(value);
                    default:
                        return value as FernIr.HttpRequestBody;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace HttpRequestBody {
    export type Raw =
        | HttpRequestBody.InlinedRequestBody
        | HttpRequestBody.Reference
        | HttpRequestBody.FileUpload
        | HttpRequestBody.Bytes;

    export interface InlinedRequestBody extends InlinedRequestBody.Raw {
        type: "inlinedRequestBody";
    }

    export interface Reference extends HttpRequestBodyReference.Raw {
        type: "reference";
    }

    export interface FileUpload extends FileUploadRequest.Raw {
        type: "fileUpload";
    }

    export interface Bytes extends BytesRequest.Raw {
        type: "bytes";
    }
}
