use seed_nullable_optional::{ClientConfig, NullableOptionalClient};

#[tokio::main]
async fn main() {
    let config = ClientConfig {
        base_url: "https://api.fern.com".to_string(),
    };
    let client = NullableOptionalClient::new(config).expect("Failed to build client");
    client.nullable_optional_create_complex_profile(serde_json::json!({"id":"id","nullableRole":"ADMIN","optionalRole":"ADMIN","optionalNullableRole":"ADMIN","nullableStatus":"active","optionalStatus":"active","optionalNullableStatus":"active","nullableNotification":{"type":"email","emailAddress":"emailAddress","subject":"subject","htmlContent":"htmlContent"},"optionalNotification":{"type":"email","emailAddress":"emailAddress","subject":"subject","htmlContent":"htmlContent"},"optionalNullableNotification":{"type":"email","emailAddress":"emailAddress","subject":"subject","htmlContent":"htmlContent"},"nullableSearchResult":{"type":"user","id":"id","username":"username","email":"email","phone":"phone","createdAt":"2024-01-15T09:30:00Z","updatedAt":"2024-01-15T09:30:00Z","address":{"street":"street","city":"city","state":"state","zipCode":"zipCode","country":"country","buildingId":"buildingId","tenantId":"tenantId"}},"optionalSearchResult":{"type":"user","id":"id","username":"username","email":"email","phone":"phone","createdAt":"2024-01-15T09:30:00Z","updatedAt":"2024-01-15T09:30:00Z","address":{"street":"street","city":"city","state":"state","zipCode":"zipCode","country":"country","buildingId":"buildingId","tenantId":"tenantId"}},"nullableArray":["nullableArray","nullableArray"],"optionalArray":["optionalArray","optionalArray"],"optionalNullableArray":["optionalNullableArray","optionalNullableArray"],"nullableListOfNullables":["nullableListOfNullables","nullableListOfNullables"],"nullableMapOfNullables":{"nullableMapOfNullables":{"street":"street","city":"city","state":"state","zipCode":"zipCode","country":"country","buildingId":"buildingId","tenantId":"tenantId"}},"nullableListOfUnions":[{"type":"email","emailAddress":"emailAddress","subject":"subject","htmlContent":"htmlContent"},{"type":"email","emailAddress":"emailAddress","subject":"subject","htmlContent":"htmlContent"}],"optionalMapOfEnums":{"optionalMapOfEnums":"ADMIN"}})).await;
}
