// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { V2FunctionSignatureOneType } from "./V2FunctionSignatureOneType.js";
import { V2NonVoidFunctionSignature } from "./V2NonVoidFunctionSignature.js";

export const V2FunctionSignatureOne: core.serialization.ObjectSchema<
    serializers.V2FunctionSignatureOne.Raw,
    SeedApi.V2FunctionSignatureOne
> = core.serialization
    .object({
        type: V2FunctionSignatureOneType,
    })
    .extend(V2NonVoidFunctionSignature);

export declare namespace V2FunctionSignatureOne {
    export interface Raw extends V2NonVoidFunctionSignature.Raw {
        type: V2FunctionSignatureOneType.Raw;
    }
}
