/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.api.resources.testgroup.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seed.api.core.Nullable;
import com.seed.api.core.NullableNonemptyFilter;
import com.seed.api.core.ObjectMappers;
import com.seed.api.types.PlainObject;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TestMethodNameTestGroupRequest.Builder.class)
public final class TestMethodNameTestGroupRequest {
    private final Optional<PlainObject> queryParamObject;

    private final Optional<Integer> queryParamInteger;

    private final Optional<PlainObject> body;

    private final Map<String, Object> additionalProperties;

    private TestMethodNameTestGroupRequest(
            Optional<PlainObject> queryParamObject,
            Optional<Integer> queryParamInteger,
            Optional<PlainObject> body,
            Map<String, Object> additionalProperties) {
        this.queryParamObject = queryParamObject;
        this.queryParamInteger = queryParamInteger;
        this.body = body;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<PlainObject> getQueryParamObject() {
        if (queryParamObject == null) {
            return Optional.empty();
        }
        return queryParamObject;
    }

    @JsonIgnore
    public Optional<Integer> getQueryParamInteger() {
        if (queryParamInteger == null) {
            return Optional.empty();
        }
        return queryParamInteger;
    }

    @JsonIgnore
    public Optional<PlainObject> getBody() {
        if (body == null) {
            return Optional.empty();
        }
        return body;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("query_param_object")
    private Optional<PlainObject> _getQueryParamObject() {
        return queryParamObject;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("query_param_integer")
    private Optional<Integer> _getQueryParamInteger() {
        return queryParamInteger;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("body")
    private Optional<PlainObject> _getBody() {
        return body;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TestMethodNameTestGroupRequest && equalTo((TestMethodNameTestGroupRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TestMethodNameTestGroupRequest other) {
        return queryParamObject.equals(other.queryParamObject)
                && queryParamInteger.equals(other.queryParamInteger)
                && body.equals(other.body);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.queryParamObject, this.queryParamInteger, this.body);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<PlainObject> queryParamObject = Optional.empty();

        private Optional<Integer> queryParamInteger = Optional.empty();

        private Optional<PlainObject> body = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TestMethodNameTestGroupRequest other) {
            queryParamObject(other.getQueryParamObject());
            queryParamInteger(other.getQueryParamInteger());
            body(other.getBody());
            return this;
        }

        @JsonSetter(value = "query_param_object", nulls = Nulls.SKIP)
        public Builder queryParamObject(Optional<PlainObject> queryParamObject) {
            this.queryParamObject = queryParamObject;
            return this;
        }

        public Builder queryParamObject(PlainObject queryParamObject) {
            this.queryParamObject = Optional.ofNullable(queryParamObject);
            return this;
        }

        public Builder queryParamObject(Nullable<PlainObject> queryParamObject) {
            if (queryParamObject.isNull()) {
                this.queryParamObject = null;
            } else if (queryParamObject.isEmpty()) {
                this.queryParamObject = Optional.empty();
            } else {
                this.queryParamObject = Optional.of(queryParamObject.get());
            }
            return this;
        }

        @JsonSetter(value = "query_param_integer", nulls = Nulls.SKIP)
        public Builder queryParamInteger(Optional<Integer> queryParamInteger) {
            this.queryParamInteger = queryParamInteger;
            return this;
        }

        public Builder queryParamInteger(Integer queryParamInteger) {
            this.queryParamInteger = Optional.ofNullable(queryParamInteger);
            return this;
        }

        public Builder queryParamInteger(Nullable<Integer> queryParamInteger) {
            if (queryParamInteger.isNull()) {
                this.queryParamInteger = null;
            } else if (queryParamInteger.isEmpty()) {
                this.queryParamInteger = Optional.empty();
            } else {
                this.queryParamInteger = Optional.of(queryParamInteger.get());
            }
            return this;
        }

        @JsonSetter(value = "body", nulls = Nulls.SKIP)
        public Builder body(Optional<PlainObject> body) {
            this.body = body;
            return this;
        }

        public Builder body(PlainObject body) {
            this.body = Optional.ofNullable(body);
            return this;
        }

        public Builder body(Nullable<PlainObject> body) {
            if (body.isNull()) {
                this.body = null;
            } else if (body.isEmpty()) {
                this.body = Optional.empty();
            } else {
                this.body = Optional.of(body.get());
            }
            return this;
        }

        public TestMethodNameTestGroupRequest build() {
            return new TestMethodNameTestGroupRequest(queryParamObject, queryParamInteger, body, additionalProperties);
        }
    }
}
