// This file was auto-generated by Fern from our API Definition.

import type * as SeedTrace from "../../../../api/index";
import * as core from "../../../../core";
import * as serializers from "../../../index";

export const ErroredResponse: core.serialization.ObjectSchema<
    serializers.ErroredResponse.Raw,
    SeedTrace.ErroredResponse
> = core.serialization.object({
    submissionId: core.serialization.lazy(() => serializers.SubmissionId),
    errorInfo: core.serialization.lazy(() => serializers.ErrorInfo),
});

export declare namespace ErroredResponse {
    export interface Raw {
        submissionId: serializers.SubmissionId.Raw;
        errorInfo: serializers.ErrorInfo.Raw;
    }
}
