openapi: 3.0.1
info:
  title: path-parameters
  version: ''
paths:
  /{tenant_id}/organizations/{organization_id}/:
    get:
      operationId: organizations_getorganization
      tags:
        - Organizations
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          example: tenant_id
          examples:
            Example1:
              value: tenant_id
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
          example: organization_id
          examples:
            Example1:
              value: organization_id
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                Example1:
                  value:
                    name: name
                    tags:
                      - tags
  /{tenant_id}/organizations/{organization_id}/users/{user_id}:
    get:
      operationId: organizations_getorganizationuser
      tags:
        - Organizations
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          example: tenant_id
          examples:
            Example1:
              value: tenant_id
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
          example: organization_id
          examples:
            Example1:
              value: organization_id
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          example: user_id
          examples:
            Example1:
              value: user_id
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Example1:
                  value:
                    name: name
                    tags:
                      - tags
  /{tenant_id}/organizations/{organization_id}/search:
    get:
      operationId: organizations_searchorganizations
      tags:
        - Organizations
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          example: tenant_id
          examples:
            Example1:
              value: tenant_id
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
          example: organization_id
          examples:
            Example1:
              value: organization_id
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
              examples:
                Example1:
                  value:
                    - name: name
                      tags:
                        - tags
  /{tenant_id}/user/{user_id}:
    get:
      operationId: user_getuser
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          example: tenant_id
          examples:
            Example1:
              value: tenant_id
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          example: user_id
          examples:
            Example1:
              value: user_id
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Example1:
                  value:
                    name: name
                    tags:
                      - tags
    patch:
      operationId: user_updateuser
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          example: tenant_id
          examples:
            Example1:
              value: tenant_id
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          example: user_id
          examples:
            Example1:
              value: user_id
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Example1:
                  value:
                    name: name
                    tags:
                      - tags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              Example1:
                value:
                  name: name
                  tags:
                    - tags
  /{tenant_id}/user/:
    post:
      operationId: user_createuser
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          example: tenant_id
          examples:
            Example1:
              value: tenant_id
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Example1:
                  value:
                    name: name
                    tags:
                      - tags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              Example1:
                value:
                  name: name
                  tags:
                    - tags
  /{tenant_id}/user/{user_id}/search:
    get:
      operationId: user_searchusers
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          example: tenant_id
          examples:
            Example1:
              value: tenant_id
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          example: user_id
          examples:
            Example1:
              value: user_id
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples:
                Example1:
                  value:
                    - name: name
                      tags:
                        - tags
  /{tenant_id}/user/{user_id}/metadata/v{version}:
    get:
      description: Test endpoint with path parameter that has a text prefix (v{version})
      operationId: user_getusermetadata
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          example: tenant_id
          examples:
            Example1:
              value: tenant_id
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          example: user_id
          examples:
            Example1:
              value: user_id
        - name: version
          in: path
          required: true
          schema:
            type: integer
          example: 1
          examples:
            Example1:
              value: 1
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Example1:
                  value:
                    name: name
                    tags:
                      - tags
  /{tenant_id}/user/{user_id}/specifics/{version}/{thought}:
    get:
      description: >-
        Test endpoint with path parameters listed in different order than found
        in path
      operationId: user_getuserspecifics
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          example: tenant_id
          examples:
            Example1:
              value: tenant_id
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          example: user_id
          examples:
            Example1:
              value: user_id
        - name: version
          in: path
          required: true
          schema:
            type: integer
          example: 1
          examples:
            Example1:
              value: 1
        - name: thought
          in: path
          required: true
          schema:
            type: string
          example: thought
          examples:
            Example1:
              value: thought
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Example1:
                  value:
                    name: name
                    tags:
                      - tags
components:
  schemas:
    Organization:
      title: Organization
      type: object
      properties:
        name:
          type: string
          example: name
        tags:
          type: array
          items:
            type: string
          example:
            - tags
      required:
        - name
        - tags
    User:
      title: User
      type: object
      properties:
        name:
          type: string
          example: name
        tags:
          type: array
          items:
            type: string
          example:
            - tags
      required:
        - name
        - tags
  securitySchemes: {}
