// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../index.js";

export type SearchRequestNeighborRequired = SeedApi.User | SeedApi.NestedUser | string | number;
