pub use crate::prelude::*;

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SpecialEnum {
    Empty,
    HelloWorld,
    HelloNWorld,
    HelloRWorld,
    HelloTWorld,
    HelloFWorld,
    HelloU0008World,
    HelloVWorld,
    HelloX00World,
    HelloU0007World,
    HelloU0001World,
    HelloU0002World,
    HelloU001FWorld,
    HelloU007FWorld,
    HelloU009FWorld,
    Line1NQuoteTTabBackslashRnLine20Null,
    Nrtx00U0008Fvu0007,
    Hello世界,
    Cafe,
    🚀,
    N,
    ,
    NameJohnAge30CityNewYork,
    SelectFromUsersWhereNameJohnOReilly,
    CUsersJohnDocumentsFileTxt,
    UsrLocalBinApp,
    D3D2D4,
    Azaz09Azaz09Azaz2,
    TranscriptTranscriptTypeFinal,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for SpecialEnum {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Empty => serializer.serialize_str(""),
            Self::HelloWorld => serializer.serialize_str("Hello \\\"World\\\""),
            Self::HelloNWorld => serializer.serialize_str("Hello\\nWorld"),
            Self::HelloRWorld => serializer.serialize_str("Hello\\rWorld"),
            Self::HelloTWorld => serializer.serialize_str("Hello\\tWorld"),
            Self::HelloFWorld => serializer.serialize_str("Hello\\fWorld"),
            Self::HelloU0008World => serializer.serialize_str("Hello\\u0008World"),
            Self::HelloVWorld => serializer.serialize_str("Hello\\vWorld"),
            Self::HelloX00World => serializer.serialize_str("Hello\\x00World"),
            Self::HelloU0007World => serializer.serialize_str("Hello\\u0007World"),
            Self::HelloU0001World => serializer.serialize_str("Hello\\u0001World"),
            Self::HelloU0002World => serializer.serialize_str("Hello\\u0002World"),
            Self::HelloU001FWorld => serializer.serialize_str("Hello\\u001FWorld"),
            Self::HelloU007FWorld => serializer.serialize_str("Hello\\u007FWorld"),
            Self::HelloU009FWorld => serializer.serialize_str("Hello\\u009FWorld"),
            Self::Line1NQuoteTTabBackslashRnLine20Null => serializer.serialize_str("Line 1\\n\"Quote\"\\tTab\\\\Backslash\\r\\nLine 2\\0Null"),
            Self::Nrtx00U0008Fvu0007 => serializer.serialize_str("\\n\\r\\t\\x00\\u0008\\f\\v\\u0007"),
            Self::Hello世界 => serializer.serialize_str("Hello 世界"),
            Self::Cafe => serializer.serialize_str("café"),
            Self::🚀 => serializer.serialize_str("🚀"),
            Self::N => serializer.serialize_str("\\\\n"),
            Self:: => serializer.serialize_str("\\\\"),
            Self::NameJohnAge30CityNewYork => serializer.serialize_str("{\"name\": \"John\", \"age\": 30, \"city\": \"New York\"}"),
            Self::SelectFromUsersWhereNameJohnOReilly => serializer.serialize_str("SELECT * FROM users WHERE name = 'John O\\\\'Reilly'"),
            Self::CUsersJohnDocumentsFileTxt => serializer.serialize_str("C:\\\\Users\\\\John\\\\Documents\\\\file.txt"),
            Self::UsrLocalBinApp => serializer.serialize_str("/usr/local/bin/app"),
            Self::D3D2D4 => serializer.serialize_str("\\\\d{3}-\\\\d{2}-\\\\d{4}"),
            Self::Azaz09Azaz09Azaz2 => serializer.serialize_str("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}"),
            Self::TranscriptTranscriptTypeFinal => serializer.serialize_str("transcript[transcriptType=\"final\"]"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for SpecialEnum {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "" => Ok(Self::Empty),
            "Hello \\\"World\\\"" => Ok(Self::HelloWorld),
            "Hello\\nWorld" => Ok(Self::HelloNWorld),
            "Hello\\rWorld" => Ok(Self::HelloRWorld),
            "Hello\\tWorld" => Ok(Self::HelloTWorld),
            "Hello\\fWorld" => Ok(Self::HelloFWorld),
            "Hello\\u0008World" => Ok(Self::HelloU0008World),
            "Hello\\vWorld" => Ok(Self::HelloVWorld),
            "Hello\\x00World" => Ok(Self::HelloX00World),
            "Hello\\u0007World" => Ok(Self::HelloU0007World),
            "Hello\\u0001World" => Ok(Self::HelloU0001World),
            "Hello\\u0002World" => Ok(Self::HelloU0002World),
            "Hello\\u001FWorld" => Ok(Self::HelloU001FWorld),
            "Hello\\u007FWorld" => Ok(Self::HelloU007FWorld),
            "Hello\\u009FWorld" => Ok(Self::HelloU009FWorld),
            "Line 1\\n\"Quote\"\\tTab\\\\Backslash\\r\\nLine 2\\0Null" => Ok(Self::Line1NQuoteTTabBackslashRnLine20Null),
            "\\n\\r\\t\\x00\\u0008\\f\\v\\u0007" => Ok(Self::Nrtx00U0008Fvu0007),
            "Hello 世界" => Ok(Self::Hello世界),
            "café" => Ok(Self::Cafe),
            "🚀" => Ok(Self::🚀),
            "\\\\n" => Ok(Self::N),
            "\\\\" => Ok(Self::),
            "{\"name\": \"John\", \"age\": 30, \"city\": \"New York\"}" => Ok(Self::NameJohnAge30CityNewYork),
            "SELECT * FROM users WHERE name = 'John O\\\\'Reilly'" => Ok(Self::SelectFromUsersWhereNameJohnOReilly),
            "C:\\\\Users\\\\John\\\\Documents\\\\file.txt" => Ok(Self::CUsersJohnDocumentsFileTxt),
            "/usr/local/bin/app" => Ok(Self::UsrLocalBinApp),
            "\\\\d{3}-\\\\d{2}-\\\\d{4}" => Ok(Self::D3D2D4),
            "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}" => Ok(Self::Azaz09Azaz09Azaz2),
            "transcript[transcriptType=\"final\"]" => Ok(Self::TranscriptTranscriptTypeFinal),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for SpecialEnum {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Empty => write!(f, ""),
            Self::HelloWorld => write!(f, "Hello \\\"World\\\""),
            Self::HelloNWorld => write!(f, "Hello\\nWorld"),
            Self::HelloRWorld => write!(f, "Hello\\rWorld"),
            Self::HelloTWorld => write!(f, "Hello\\tWorld"),
            Self::HelloFWorld => write!(f, "Hello\\fWorld"),
            Self::HelloU0008World => write!(f, "Hello\\u0008World"),
            Self::HelloVWorld => write!(f, "Hello\\vWorld"),
            Self::HelloX00World => write!(f, "Hello\\x00World"),
            Self::HelloU0007World => write!(f, "Hello\\u0007World"),
            Self::HelloU0001World => write!(f, "Hello\\u0001World"),
            Self::HelloU0002World => write!(f, "Hello\\u0002World"),
            Self::HelloU001FWorld => write!(f, "Hello\\u001FWorld"),
            Self::HelloU007FWorld => write!(f, "Hello\\u007FWorld"),
            Self::HelloU009FWorld => write!(f, "Hello\\u009FWorld"),
            Self::Line1NQuoteTTabBackslashRnLine20Null => write!(f, "Line 1\\n\"Quote\"\\tTab\\\\Backslash\\r\\nLine 2\\0Null"),
            Self::Nrtx00U0008Fvu0007 => write!(f, "\\n\\r\\t\\x00\\u0008\\f\\v\\u0007"),
            Self::Hello世界 => write!(f, "Hello 世界"),
            Self::Cafe => write!(f, "café"),
            Self::🚀 => write!(f, "🚀"),
            Self::N => write!(f, "\\\\n"),
            Self:: => write!(f, "\\\\"),
            Self::NameJohnAge30CityNewYork => write!(f, "{\"name\": \"John\", \"age\": 30, \"city\": \"New York\"}"),
            Self::SelectFromUsersWhereNameJohnOReilly => write!(f, "SELECT * FROM users WHERE name = 'John O\\\\'Reilly'"),
            Self::CUsersJohnDocumentsFileTxt => write!(f, "C:\\\\Users\\\\John\\\\Documents\\\\file.txt"),
            Self::UsrLocalBinApp => write!(f, "/usr/local/bin/app"),
            Self::D3D2D4 => write!(f, "\\\\d{3}-\\\\d{2}-\\\\d{4}"),
            Self::Azaz09Azaz09Azaz2 => write!(f, "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}"),
            Self::TranscriptTranscriptTypeFinal => write!(f, "transcript[transcriptType=\"final\"]"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
