// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions, type NormalizedClientOptions } from "../../../../BaseClient.js";
import { ImdbClient as ImdbClient_ } from "../resources/imdb/client/Client.js";

export declare namespace ImdbClient {
    export type Options = BaseClientOptions;
}

export class ImdbClient {
    protected readonly _options: NormalizedClientOptions<ImdbClient.Options>;
    protected _imdb: ImdbClient_ | undefined;

    constructor(options: ImdbClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get imdb(): ImdbClient_ {
        return (this._imdb ??= new ImdbClient_(this._options));
    }
}
