# frozen_string_literal: true

require_relative "seed_examples_client/commons/types/types/metadata"

require_relative "seed_examples_client/commons/types/types/data"
require_relative "seed_examples_client/commons/types/types/event_info"
require_relative "seed_examples_client/commons/types/types/tag"
require_relative "seed_examples_client/file/service/types/filename"
require_relative "seed_examples_client/types/types/actor"
require_relative "seed_examples_client/types/types/actress"
require_relative "seed_examples_client/types/types/cast_member"
require_relative "seed_examples_client/types/types/directory"
require_relative "seed_examples_client/types/types/exception"
require_relative "seed_examples_client/types/types/exception_info"
require_relative "seed_examples_client/types/types/extended_movie"
require_relative "seed_examples_client/types/types/file"
require_relative "seed_examples_client/types/types/metadata"
require_relative "seed_examples_client/types/types/migration"
require_relative "seed_examples_client/types/types/moment"
require_relative "seed_examples_client/types/types/movie"
require_relative "seed_examples_client/types/types/movie_id"
require_relative "seed_examples_client/types/types/node"
require_relative "seed_examples_client/types/types/request"
require_relative "seed_examples_client/types/types/response"
require_relative "seed_examples_client/types/types/stunt_double"
require_relative "seed_examples_client/types/types/test"
require_relative "seed_examples_client/types/types/tree"
