export const GeneratorName = {
    TYPESCRIPT: "fernenterprise/fern-typescript",
    TYPESCRIPT_SDK: "fernenterprise/fern-typescript-sdk",
    TYPESCRIPT_NODE_SDK: "fernenterprise/fern-typescript-node-sdk",
    TYPESCRIPT_BROWSER_SDK: "fernenterprise/fern-typescript-browser-sdk",
    TYPESCRIPT_EXPRESS: "fernenterprise/fern-typescript-express",
    JAVA: "fernenterprise/fern-java",
    JAVA_MODEL: "fernenterprise/fern-java-model",
    JAVA_SDK: "fernenterprise/fern-java-sdk",
    JAVA_SPRING: "fernenterprise/fern-java-spring",
    PYTHON_FASTAPI: "fernenterprise/fern-fastapi-server",
    PYTHON_PYDANTIC: "fernenterprise/fern-pydantic-model",
    PYTHON_SDK: "fernenterprise/fern-python-sdk",
    GO_MODEL: "fernenterprise/fern-go-model",
    GO_SDK: "fernenterprise/fern-go-sdk",
    RUBY_SDK: "fernenterprise/fern-ruby-sdk",
    CSHARP_MODEL: "fernenterprise/fern-csharp-model",
    CSHARP_SDK: "fernenterprise/fern-csharp-sdk",
    SWIFT_MODEL: "fernenterprise/fern-swift-model",
    SWIFT_SDK: "fernenterprise/fern-swift-sdk",
    PHP_MODEL: "fernenterprise/fern-php-model",
    PHP_SDK: "fernenterprise/fern-php-sdk",
    RUST_MODEL: "fernenterprise/fern-rust-model",
    RUST_SDK: "fernenterprise/fern-rust-sdk",
    OPENAPI: "fernenterprise/fern-openapi",
    STOPLIGHT: "fernenterprise/fern-stoplight",
    POSTMAN: "fernenterprise/fern-postman",
    OPENAPI_PYTHON_CLIENT: "fernenterprise/openapi-python-client",
    CLI: "fernenterprise/fern-cli-generator"
} as const;

export type GeneratorName = (typeof GeneratorName)[keyof typeof GeneratorName];
