// This file was auto-generated by Fern from our API Definition.

import type * as FernIr from "../../../../../index.js";

export interface MavenRegistryConfigV2 {
    registryUrl: string;
    username: string;
    password: string;
    coordinate: string;
    signature: FernIr.generatorExec.MavenCentralSignature | undefined;
}
