// This file was auto-generated by Fern from our API Definition.

import type * as acme from "../../../index.js";

export interface TypeWithOptionalUnion {
    myUnion?: (acme.undiscriminatedUnions.MyUnion | null) | undefined;
}
