// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../../../../../../../../index";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetMetadataMetadataRequest {
    id: SeedApi.mixedFileDirectory.Id;
}
