# frozen_string_literal: true

require "json"
require "net/http"
require "securerandom"

require_relative "seed/internal/json/serializable"
require_relative "seed/internal/types/type"
require_relative "seed/internal/types/utils"
require_relative "seed/internal/types/union"
require_relative "seed/internal/errors/constraint_error"
require_relative "seed/internal/errors/type_error"
require_relative "seed/internal/http/base_request"
require_relative "seed/internal/json/request"
require_relative "seed/internal/http/raw_client"
require_relative "seed/internal/multipart/multipart_encoder"
require_relative "seed/internal/multipart/multipart_form_data_part"
require_relative "seed/internal/multipart/multipart_form_data"
require_relative "seed/internal/multipart/multipart_request"
require_relative "seed/internal/types/model/field"
require_relative "seed/internal/types/model"
require_relative "seed/internal/types/array"
require_relative "seed/internal/types/boolean"
require_relative "seed/internal/types/enum"
require_relative "seed/internal/types/hash"
require_relative "seed/internal/types/unknown"
require_relative "seed/errors/api_error"
require_relative "seed/errors/response_error"
require_relative "seed/errors/client_error"
require_relative "seed/errors/redirect_error"
require_relative "seed/errors/server_error"
require_relative "seed/errors/timeout_error"
require_relative "seed/internal/iterators/item_iterator"
require_relative "seed/internal/iterators/cursor_item_iterator"
require_relative "seed/internal/iterators/offset_item_iterator"
require_relative "seed/internal/iterators/cursor_page_iterator"
require_relative "seed/internal/iterators/offset_page_iterator"
require_relative "seed/types/basic_type"
require_relative "seed/types/complex_type"
require_relative "seed/types/type"
require_relative "seed/types/identifier"
require_relative "seed/types/type_with_single_char_property_equal_to_type_starting_letter"
require_relative "seed/types/commons_tag"
require_relative "seed/types/commons_metadata"
require_relative "seed/types/commons_event_info_zero_type"
require_relative "seed/types/commons_event_info_zero"
require_relative "seed/types/commons_event_info_type_type"
require_relative "seed/types/commons_event_info_type"
require_relative "seed/types/commons_event_info"
require_relative "seed/types/commons_data_string"
require_relative "seed/types/commons_data_base64"
require_relative "seed/types/commons_data"
require_relative "seed/types/file_filename"
require_relative "seed/types/movie_id"
require_relative "seed/types/movie_type"
require_relative "seed/types/movie"
require_relative "seed/types/actor"
require_relative "seed/types/actress"
require_relative "seed/types/stunt_double"
require_relative "seed/types/cast_member"
require_relative "seed/types/extended_movie"
require_relative "seed/types/moment"
require_relative "seed/types/file"
require_relative "seed/types/directory"
require_relative "seed/types/tree"
require_relative "seed/types/node"
require_relative "seed/types/metadata_html"
require_relative "seed/types/metadata_markdown"
require_relative "seed/types/metadata"
require_relative "seed/types/exception_zero_type"
require_relative "seed/types/exception_info"
require_relative "seed/types/exception_zero"
require_relative "seed/types/exception_type_type"
require_relative "seed/types/exception_type"
require_relative "seed/types/exception"
require_relative "seed/types/migration_status"
require_relative "seed/types/migration"
require_relative "seed/types/request"
require_relative "seed/types/response"
require_relative "seed/types/response_type"
require_relative "seed/types/test_and"
require_relative "seed/types/test_or"
require_relative "seed/types/test"
require_relative "seed/types/entity"
require_relative "seed/types/cron_job"
require_relative "seed/client"
require_relative "seed/file_notification_service/client"
require_relative "seed/file_notification_service/types/file_notification_service_get_exception_request"
require_relative "seed/file_service/client"
require_relative "seed/file_service/types/file_service_get_file_request"
require_relative "seed/health_service/client"
require_relative "seed/health_service/types/health_service_check_request"
require_relative "seed/service/client"
require_relative "seed/service/types/service_get_movie_request"
require_relative "seed/service/types/service_get_metadata_request"
require_relative "seed/service/types/big_entity"
require_relative "seed/service/types/refresh_token_request"
require_relative "seed/environment"

# Load user-defined files if present (e.g., for Sentry integration)
# Files are loaded from lib/seed/ if they exist
["seed/custom_integration", "seed/sentry_integration"].each do |relative_path|
  absolute_path = File.join(__dir__, "#{relative_path}.rb")
  require_relative relative_path if File.exist?(absolute_path)
end
