/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as FernDocsConfig from "../../../../api";
import * as core from "../../../../core";

export const JsConfig: core.serialization.Schema<serializers.JsConfig.Raw, FernDocsConfig.JsConfig> =
    core.serialization.undiscriminatedUnion([
        core.serialization.lazy(async () => (await import("../../..")).JsConfigOptions),
        core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).JsConfigOptions)),
    ]);

export declare namespace JsConfig {
    type Raw = serializers.JsConfigOptions.Raw | serializers.JsConfigOptions.Raw[];
}
