import Foundation

public enum SpecialEnum: String, Codable, Hashable, CaseIterable, Sendable {
    case empty = ""
    case helloWorld = "Hello \"World\""
    case helloNWorld = "Hello\nWorld"
    case helloRWorld = "Hello\rWorld"
    case helloTWorld = "Hello\tWorld"
    case helloFWorld = "Hello\u{000C}World"
    case helloU0008World = "Hello\u{0008}World"
    case helloVWorld = "Hello\u{000B}World"
    case helloX00World = "Hello\x00World"
    case helloU0007World = "Hello\u{0007}World"
    case helloU0001World = "Hello\u{0001}World"
    case helloU0002World = "Hello\u{0002}World"
    case helloU001FWorld = "Hello\u{001F}World"
    case helloU007FWorld = "Hello\u{007F}World"
    case helloU009FWorld = "Hello\u{009F}World"
    case line1NQuoteTTabBackslashRnLine20Null = "Line 1\n\"Quote\"\tTab\\Backslash\r\nLine 2\u{0000}Null"
    case nrtx00U0008Fvu0007 = "\n\r\t\x00\u{0008}\u{000C}\u{000B}\u{0007}"
    case hello世界 = "Hello 世界"
    case cafe = "café"
    case 🚀
    case n = "\\n"
    case  = "\\"
    case nameJohnAge30CityNewYork = "{\"name\": \"John\", \"age\": 30, \"city\": \"New York\"}"
    case selectFromUsersWhereNameJohnOReilly = "SELECT * FROM users WHERE name = 'John O\\'Reilly'"
    case cUsersJohnDocumentsFileTxt = "C:\\Users\\John\\Documents\\file.txt"
    case usrLocalBinApp = "/usr/local/bin/app"
    case d3D2D4 = "\\d{3}-\\d{2}-\\d{4}"
    case azaz09Azaz09Azaz2 = "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
    case transcriptTranscriptTypeFinal = "transcript[transcriptType=\"final\"]"
}