import Foundation

public enum SpecialEnum: String, Codable, Hashable, CaseIterable, Sendable {
    case a = ""
    case b = "Hello \\\"World\\\""
    case c = "Hello 'World'"
    case d = "Hello\\\\World"
    case e = "Hello\\nWorld"
    case f = "Hello\\rWorld"
    case h = "Hello\\tWorld"
    case i = "Hello\\fWorld"
    case j = "Hello\\u0008World"
    case k = "Hello\\vWorld"
    case l = "Hello\\x00World"
    case m = "Hello\\u0007World"
    case n = "Hello\\u0001World"
    case o = "Hello\\u0002World"
    case p = "Hello\\u001FWorld"
    case q = "Hello\\u007FWorld"
    case r = "Hello\\u009FWorld"
    case s = "Line 1\\n\"Quote\"\\tTab\\\\Backslash\\r\\nLine 2\\0Null"
    case t = "\\n\\r\\t\\x00\\u0008\\f\\v\\u0007"
    case u = "Hello 世界"
    case v = "café"
    case w = "🚀"
    case x = "\\\\n"
    case y = "\\\\"
    case z = "{\"name\": \"John\", \"age\": 30, \"city\": \"New York\"}"
    case aa = "SELECT * FROM users WHERE name = 'John O\\\\'Reilly'"
    case bb = "C:\\\\Users\\\\John\\\\Documents\\\\file.txt"
    case cc = "/usr/local/bin/app"
    case dd = "\\\\d{3}-\\\\d{2}-\\\\d{4}"
    case ee = "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}"
    case ff = "transcript[transcriptType=\"final\"]"
    case gg = "transcript[transcriptType='final']"
}