// This file was auto-generated by Fern from our API Definition.

import { SeedApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SeedApiClient", () => {
    test("streamProtocolNoCollision", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = "event: heartbeat\ndata: {}\n\n";

        server
            .mockEndpoint()
            .post("/stream/protocol-no-collision")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.streamProtocolNoCollision({});
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                event: "heartbeat",
            },
        ]);
    });

    test("streamProtocolCollision", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = "event: heartbeat\ndata: {}\n\n";

        server
            .mockEndpoint()
            .post("/stream/protocol-collision")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.streamProtocolCollision({});
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                event: "heartbeat",
            },
        ]);
    });

    test("streamDataContext", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = 'event: \ndata: {"timestamp":"2024-01-15T09:30:00Z","event":"heartbeat"}\n\n';

        server
            .mockEndpoint()
            .post("/stream/data-context")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.streamDataContext({});
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                event: "heartbeat",
                timestamp: "2024-01-15T09:30:00Z",
            },
        ]);
    });

    test("streamNoContext", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = 'event: \ndata: {"timestamp":"2024-01-15T09:30:00Z","event":"heartbeat"}\n\n';

        server
            .mockEndpoint()
            .post("/stream/no-context")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.streamNoContext({});
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                event: "heartbeat",
                timestamp: "2024-01-15T09:30:00Z",
            },
        ]);
    });

    test("streamProtocolWithFlatSchema", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = 'event: heartbeat\ndata: {"timestamp":"2024-01-15T09:30:00Z"}\n\n';

        server
            .mockEndpoint()
            .post("/stream/protocol-with-flat-schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.streamProtocolWithFlatSchema({});
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                event: "heartbeat",
                timestamp: "2024-01-15T09:30:00Z",
            },
        ]);
    });

    test("streamDataContextWithEnvelopeSchema", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = 'event: \ndata: {"event":"heartbeat"}\n\n';

        server
            .mockEndpoint()
            .post("/stream/data-context-with-envelope-schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.streamDataContextWithEnvelopeSchema({});
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                event: "heartbeat",
            },
        ]);
    });

    test("streamOasSpecNative", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = 'event: \ndata: {"data":"data","event":"event","id":"id","retry":1}\n\n';

        server
            .mockEndpoint()
            .post("/stream/oas-spec-native")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.streamOasSpecNative({});
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                data: "data",
                event: "event",
                id: "id",
                retry: 1,
            },
        ]);
    });

    test("streamXFernStreamingCondition", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { query: "query", stream: false };
        const rawResponseBody = { answer: "answer", finishReason: "complete" };

        server
            .mockEndpoint()
            .post("/stream/x-fern-streaming-condition")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.streamXFernStreamingCondition({
            query: "query",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("streamXFernStreamingSharedSchema", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt", model: "model", stream: false };
        const rawResponseBody = { answer: "answer", finishReason: "complete" };

        server
            .mockEndpoint()
            .post("/stream/x-fern-streaming-shared-schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.streamXFernStreamingSharedSchema({
            prompt: "prompt",
            model: "model",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("validateCompletion", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt", model: "model" };
        const rawResponseBody = { answer: "answer", finishReason: "complete" };

        server
            .mockEndpoint()
            .post("/validate-completion")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.validateCompletion({
            prompt: "prompt",
            model: "model",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("streamXFernStreamingUnion", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { type: "message", stream_response: false, prompt: "prompt", message: "message" };
        const rawResponseBody = { answer: "answer", finishReason: "complete" };

        server
            .mockEndpoint()
            .post("/stream/x-fern-streaming-union")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.streamXFernStreamingUnion({
            type: "message",
            prompt: "prompt",
            message: "message",
            stream_response: false,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("validateUnionRequest", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt" };
        const rawResponseBody = { valid: true };

        server
            .mockEndpoint()
            .post("/validate-union-request")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.validateUnionRequest({
            prompt: "prompt",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("streamXFernStreamingNullableCondition", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { query: "query", stream: false };
        const rawResponseBody = { answer: "answer", finishReason: "complete" };

        server
            .mockEndpoint()
            .post("/stream/x-fern-streaming-nullable-condition")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.streamXFernStreamingNullableCondition({
            query: "query",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("streamXFernStreamingSseOnly", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = 'event: \ndata: "string"\n\n';

        server
            .mockEndpoint()
            .post("/stream/x-fern-streaming-sse-only")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.streamXFernStreamingSseOnly({});
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual(["string"]);
    });
});
