/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.unknown.post.Response.Raw, any[]> = core.serialization.list(core.serialization.any());

export declare namespace Response {
    type Raw = any[];
}


