// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import type * as acme from "../../../../../index.js";

export declare namespace SimpleFhirClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SimpleFhirClient {
    protected readonly _options: NormalizedClientOptions<SimpleFhirClient.Options>;

    constructor(options: SimpleFhirClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {acme.simpleFhir.GetAccountRequest} request
     * @param {SimpleFhirClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.simpleFhir.simpleFhir.getAccount({
     *         account_id: "account_id"
     *     })
     */
    public getAccount(
        request: acme.simpleFhir.GetAccountRequest,
        requestOptions?: SimpleFhirClient.RequestOptions,
    ): core.HttpResponsePromise<acme.simpleFhir.Account> {
        return core.HttpResponsePromise.fromPromise(this.__getAccount(request, requestOptions));
    }

    private async __getAccount(
        request: acme.simpleFhir.GetAccountRequest,
        requestOptions?: SimpleFhirClient.RequestOptions,
    ): Promise<core.WithRawResponse<acme.simpleFhir.Account>> {
        const { account_id: accountId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Version": requestOptions?.apiVersion ?? this._options?.apiVersion ?? "2024-02-08",
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.AcmeEnvironment.Production)
                        .base,
                `account/${core.url.encodePathParam(accountId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as acme.simpleFhir.Account, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AcmeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/account/{account_id}");
    }
}
