// This file was auto-generated by Fern from our API Definition.

export const GetTokenRequestAudience = {
    HttpsApiExampleCom: "https://api.example.com",
} as const;
export type GetTokenRequestAudience = (typeof GetTokenRequestAudience)[keyof typeof GetTokenRequestAudience] | string;
