# frozen_string_literal: true

require_relative "seed_undiscriminated_union_with_response_property_client/types/union_response"
require_relative "seed_undiscriminated_union_with_response_property_client/types/union_list_response"
require_relative "seed_undiscriminated_union_with_response_property_client/types/variant_a"
require_relative "seed_undiscriminated_union_with_response_property_client/types/variant_b"
require_relative "seed_undiscriminated_union_with_response_property_client/types/variant_c"
require_relative "seed_undiscriminated_union_with_response_property_client/types/my_union"
