openapi: 3.0.1
info:
  title: version-no-default
  version: ''
paths:
  /users/{userId}:
    get:
      operationId: user_getuser
      tags:
        - User
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UserId'
          example: userId
          examples:
            Example1:
              value: userId
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Example1:
                  value:
                    id: id
                    name: name
components:
  schemas:
    UserId:
      title: UserId
      type: string
    User:
      title: User
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        name:
          type: string
          example: name
      required:
        - id
        - name
  securitySchemes: {}
