// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../../api/index";
import * as core from "../../../../core";
import * as serializers from "../../../index";

export const Animal: core.serialization.Schema<serializers.Animal.Raw, SeedApi.Animal> =
    core.serialization.undiscriminatedUnion([
        core.serialization.lazyObject(() => serializers.Cat),
        core.serialization.lazyObject(() => serializers.Dog),
    ]);

export declare namespace Animal {
    export type Raw = serializers.Cat.Raw | serializers.Dog.Raw;
}
