// Code generated by Fern. DO NOT EDIT.

package endpointsunion

import (
	context "context"

	fern "github.com/exhaustive/fern"
	core "github.com/exhaustive/fern/core"
	internal "github.com/exhaustive/fern/internal"
	option "github.com/exhaustive/fern/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) EndpointsUnionGetAndReturnUnion(
	ctx context.Context,
	request *fern.TypesAnimal,
	opts ...option.RequestOption,
) (*fern.TypesAnimal, error) {
	response, err := c.WithRawResponse.EndpointsUnionGetAndReturnUnion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
