[package]
name = "basic_auth_cli_types"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]

[dependencies.basic_auth_cli_types_core]
path = "crates/basic-auth-cli-types-core"

[dependencies.basic_auth_cli_types_system]
path = "crates/basic-auth-cli-types-system"

[dependencies.basic_auth_cli_types_widgets]
path = "crates/basic-auth-cli-types-widgets"
