export enum AsIsFiles {
    // Internal files.
    ExtraProperties = "internal/extra_properties.go_",
    ExtraPropertiesTest = "internal/extra_properties_test.go_",
    Stringer = "internal/stringer.go_",
    Time = "internal/time.go_",
    HttpInternal = "internal/http.go_",
    Query = "internal/query.go_",
    QueryTest = "internal/query_test.go_",
    Multipart = "internal/multipart.go_",
    MultipartTest = "internal/multipart_test.go_",
    MainTest = "test/main_test.go_",
    ErrorCodes = "error_codes.go_",
    ErrorDecoder = "internal/error_decoder.go_",
    ErrorDecoderTest = "internal/error_decoder_test.go_",
    Caller = "internal/caller.go_",
    CallerTest = "internal/caller_test.go_",
    Retrier = "internal/retrier.go_",
    RetrierTest = "internal/retrier_test.go_",
    Page = "core/page.go_",
    Pager = "internal/pager.go_",
    PagerTest = "internal/pager_test.go_",
    Stream = "core/stream.go_",
    Streamer = "internal/streamer.go_",
    // Core files.
    HttpCore = "core/http.go_",
    // Root files.
    FileParam = "file_param.go_"
}
