export const AsIsFiles = {
    CiYaml: "github-ci.yml",
    Constants: "Constants.Template.cs",
    CustomProps: "Custom.props.Template",
    EditorConfig: ".editorconfig.Template",
    ExceptionHandler: "ExceptionHandler.Template.cs",
    Extensions: "Extensions.cs",
    FileParameter: "FileParameter.Template.cs",
    GitIgnore: ".gitignore.Template",
    StringEnum: "StringEnum.Template.cs",
    StringEnumExtensions: "StringEnumExtensions.Template.cs",
    TemplateCsProj: "Template.csproj",
    UsingCs: "Using.cs",
    ValueConvert: "ValueConvert.Template.cs",
    // Grpc
    GrpcRequestOptions: "GrpcRequestOptions.Template.cs",
    ProtoAnyMapper: "ProtoAnyMapper.Template.cs",
    RawGrpcClient: "RawGrpcClient.Template.cs",
    // Pagination
    CustomPager: "CustomPager.Template.cs",
    CustomPagerContext: "CustomPagerContext.Template.cs",
    Page: "Page.Template.cs",
    Pager: "Pager.Template.cs",
    // HTTP
    ApiResponse: "ApiResponse.Template.cs",
    BaseRequest: "BaseRequest.Template.cs",
    EmptyRequest: "EmptyRequest.Template.cs",
    EncodingCache: "EncodingCache.Template.cs",
    FormUrlEncoder: "FormUrlEncoder.Template.cs",
    Headers: "Headers.Template.cs",
    HeaderValue: "HeaderValue.Template.cs",
    HttpMethodExtensions: "HttpMethodExtensions.cs",
    IIsRetryableContent: "IIsRetryableContent.Template.cs",
    JsonRequest: "JsonRequest.Template.cs",
    FormRequest: "FormRequest.Template.cs",
    MultipartFormRequest: "MultipartFormRequest.Template.cs",
    NdJsonContent: "NdJsonContent.Template.cs",
    NdJsonRequest: "NdJsonRequest.Template.cs",
    QueryStringBuilder: "QueryStringBuilder.Template.cs",
    QueryStringConverter: "QueryStringConverter.Template.cs",
    RawClient: "RawClient.Template.cs",
    RawResponse: "RawResponse.Template.cs",
    ResponseHeaders: "ResponseHeaders.Template.cs",
    StreamRequest: "StreamRequest.Template.cs",
    WithRawResponse: "WithRawResponse.Template.cs",
    WithRawResponseTask: "WithRawResponseTask.Template.cs",
    WebSockets: {
        AsyncLock: "WebSockets/AsyncLock.Template.cs",
        Closed: "WebSockets/Closed.Template.cs",
        Connected: "WebSockets/Connected.Template.cs",
        ConnectionStatus: "WebSockets/ConnectionStatus.Template.cs",
        DisconnectionInfo: "WebSockets/DisconnectionInfo.Template.cs",
        DisconnectionType: "WebSockets/DisconnectionType.Template.cs",
        Event: "WebSockets/Event.Template.cs",
        Query: "WebSockets/Query.Template.cs",
        ReconnectionInfo: "WebSockets/ReconnectionInfo.Template.cs",
        ReconnectionType: "WebSockets/ReconnectionType.Template.cs",
        RequestMessage: "WebSockets/RequestMessage.Template.cs",
        WebSocketClient: "WebSockets/WebSocketClient.Template.cs",
        WebSocketConnection: "WebSockets/WebSocketConnection.Template.cs",
        WebSocketConnectionSending: "WebSockets/WebSocketConnection.Sending.Template.cs",
        WebsocketException: "WebSockets/WebsocketException.Template.cs"
    },
    Json: {
        AdditionalProperties: "AdditionalProperties.Template.cs",
        CollectionItemSerializer: "CollectionItemSerializer.Template.cs",
        DateOnlyConverter: "DateOnlyConverter.Template.cs",
        DateTimeSerializer: "DateTimeSerializer.Template.cs",
        EnumConverter: "EnumConverter.Template.cs",
        EnumSerializer: "EnumSerializer.Template.cs",
        JsonAccessAttribute: "JsonAccessAttribute.Template.cs",
        JsonConfiguration: "JsonConfiguration.Template.cs",
        Nullable: "NullableAttribute.Template.cs",
        OneOfSerializer: "OneOfSerializer.Template.cs",
        Optional: "Optional.Template.cs",
        OptionalAttribute: "OptionalAttribute.Template.cs",
        StringEnumSerializer: "StringEnumSerializer.Template.cs"
    },
    Test: {
        QueryStringBuilderTests: "test/QueryStringBuilderTests.Template.cs",
        QueryStringConverterTests: "test/QueryStringConverterTests.Template.cs",
        TemplateTestClientCs: "test/TemplateTestClient.cs",
        TemplateTestCsProj: "test/Template.Test.csproj",
        TestCustomProps: "test/Test.Custom.props.Template",
        WithRawResponseTests: "test/WithRawResponseTests.Template.cs",
        RawClientTests: {
            AdditionalHeadersTests: "test/RawClientTests/AdditionalHeadersTests.Template.cs",
            AdditionalParametersTests: "test/RawClientTests/AdditionalParametersTests.Template.cs",
            MultipartFormTests: "test/RawClientTests/MultipartFormTests.Template.cs",
            RetriesTests: "test/RawClientTests/RetriesTests.Template.cs",
            QueryParameterTests: "test/RawClientTests/QueryParameterTests.Template.cs",
            IdempotentHeadersTests: "test/RawClientTests/IdempotentHeadersTests.Template.cs"
        },
        Utils: {
            JsonElementComparer: "test/Utils/JsonElementComparer.Template.cs",
            NUnitExtensions: "test/Utils/NUnitExtensions.Template.cs",
            OneOfComparer: "test/Utils/OneOfComparer.Template.cs",
            OptionalComparer: "test/Utils/OptionalComparer.Template.cs",
            ReadOnlyMemoryComparer: "test/Utils/ReadOnlyMemoryComparer.Template.cs"
        },
        Pagination: [
            "test/Pagination/GuidCursorTest.Template.cs",
            "test/Pagination/HasNextPageOffsetTest.Template.cs",
            "test/Pagination/IntOffsetTest.Template.cs",
            "test/Pagination/LongOffsetTest.Template.cs",
            "test/Pagination/NoRequestCursorTest.Template.cs",
            "test/Pagination/NoRequestOffsetTest.Template.cs",
            "test/Pagination/StepOffsetTest.Template.cs",
            "test/Pagination/StringCursorTest.Template.cs"
        ],
        Json: {
            AdditionalPropertiesTests: "test/Json/AdditionalPropertiesTests.Template.cs",
            DateOnlyJsonTests: "test/Json/DateOnlyJsonTests.Template.cs",
            DateTimeJsonTests: "test/Json/DateTimeJsonTests.Template.cs",
            EnumSerializerTests: "test/Json/EnumSerializerTests.Template.cs",
            JsonAccessAttributeTests: "test/Json/JsonAccessAttributeTests.Template.cs",
            OneOfSerializerTests: "test/Json/OneOfSerializerTests.Template.cs",
            StringEnumSerializerTests: "test/Json/StringEnumSerializerTests.Template.cs"
        }
    }
};
