// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import type * as acme from "../../../../../index.js";

export declare namespace PropertyAccessClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PropertyAccessClient {
    protected readonly _options: NormalizedClientOptions<PropertyAccessClient.Options>;

    constructor(options: PropertyAccessClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {acme.propertyAccess.User} request
     * @param {PropertyAccessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.propertyAccess.propertyAccess.createUser({
     *         id: "id",
     *         email: "email",
     *         password: "password",
     *         profile: {
     *             name: "name",
     *             verification: {
     *                 verified: "verified"
     *             },
     *             ssn: "ssn"
     *         }
     *     })
     */
    public createUser(
        request: acme.propertyAccess.User,
        requestOptions?: PropertyAccessClient.RequestOptions,
    ): core.HttpResponsePromise<acme.propertyAccess.User> {
        return core.HttpResponsePromise.fromPromise(this.__createUser(request, requestOptions));
    }

    private async __createUser(
        request: acme.propertyAccess.User,
        requestOptions?: PropertyAccessClient.RequestOptions,
    ): Promise<core.WithRawResponse<acme.propertyAccess.User>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Version": requestOptions?.apiVersion ?? this._options?.apiVersion ?? "2024-02-08",
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.AcmeEnvironment.Production)
                        .base,
                "users",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as acme.propertyAccess.User, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AcmeError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/users");
    }
}
