"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SeedObjectError = void 0;
class SeedObjectError extends Error {
    constructor(errorName) {
        super();
        this.errorName = errorName;
        Object.setPrototypeOf(this, SeedObjectError.prototype);
    }
}
exports.SeedObjectError = SeedObjectError;
