/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types.object;

import java.lang.Object;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

@RestControllerAdvice
public final class ObjectWithRequiredFieldErrorExceptionHandler {
  @ExceptionHandler(ObjectWithRequiredFieldError.class)
  ResponseEntity<Object> handle(ObjectWithRequiredFieldError objectWithRequiredFieldError) {
    return new ResponseEntity<>(objectWithRequiredFieldError.getBody(), null, ObjectWithRequiredFieldError.STATUS_CODE);
  }
}
