// This file was auto-generated by Fern from our API Definition.

import type * as FernIr from "../../../index.js";

export interface QueryParameter extends FernIr.Declaration {
    name: FernIr.NameAndWireValueOrString;
    valueType: FernIr.TypeReference;
    allowMultiple: boolean;
    /**
     * A client-side default value for this query parameter. When present,
     * the parameter is optional in the generated SDK and this literal value
     * is sent when the caller does not provide one. Populated from the
     * `x-fern-default` OpenAPI extension.
     */
    clientDefault: FernIr.Literal | undefined;
    /**
     * The documentation default value for this query parameter. Populated
     * from the OpenAPI `default` field. Used by docs to render "Defaults
     * to ..." metadata. Unlike `clientDefault`, this supports arbitrary
     * JSON values (e.g. arrays) and does not affect SDK behavior.
     */
    defaultValue: unknown | undefined;
    v2Examples: FernIr.V2SchemaExamples | undefined;
    explode: boolean | undefined;
}
