// This file was auto-generated by Fern from our API Definition.

import type * as FernIr from "../../../index.js";

export interface SdkRequest {
    /** The request property that controls whether or not the response is streamed. */
    streamParameter: FernIr.RequestProperty | undefined;
    requestParameterName: FernIr.NameOrString;
    shape: FernIr.SdkRequestShape;
}
