# This file was auto-generated by Fern from our API Definition.

from ....core.pydantic_utilities import UniversalBaseModel
from .movie_id import MovieId
import pydantic.v1
class Movie(UniversalBaseModel):
    id: MovieId
    title: str
    rating: float = pydantic.v1.Field()
    """
    The rating scale is one to five stars
    """
    
    
    class Config:
        extra = pydantic.v1.Extra.forbid
