export * as endpoints from "./endpoints";
export * as endpointsHttpMethods from "./endpointsHttpMethods";
export * from "./endpointsHttpMethods/client/requests";
export * as endpointsUrLs from "./endpointsUrLs";
export * as inlinedRequests from "./inlinedRequests";
export * from "./inlinedRequests/client/requests";
export * as noAuth from "./noAuth";
export * as noReqBody from "./noReqBody";
export * as reqWithHeaders from "./reqWithHeaders";
export * from "./reqWithHeaders/client/requests";
