// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../index.js";

export type UnionWithOptionalTime =
    | SeedApi.unionsWithLocalDate.UnionWithOptionalTime.Date
    | SeedApi.unionsWithLocalDate.UnionWithOptionalTime.Datetime
    | SeedApi.unionsWithLocalDate.UnionWithOptionalTime._Unknown;

export namespace UnionWithOptionalTime {
    export interface Date {
        type: "date";
        value?: (string | null) | undefined;
    }

    export interface Datetime {
        type: "datetime";
        value?: (string | null) | undefined;
    }

    export interface _Unknown {
        type: string;
    }
}
