/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SeedTrace from "../../../../api";
import * as core from "../../../../core";

export const VariableValue: core.serialization.Schema<serializers.VariableValue.Raw, SeedTrace.VariableValue> =
    core.serialization
        .union("type", {
            integerValue: core.serialization.object({
                value: core.serialization.number(),
            }),
            booleanValue: core.serialization.object({
                value: core.serialization.boolean(),
            }),
            doubleValue: core.serialization.object({
                value: core.serialization.number(),
            }),
            stringValue: core.serialization.object({
                value: core.serialization.string(),
            }),
            charValue: core.serialization.object({
                value: core.serialization.string(),
            }),
            mapValue: core.serialization.lazyObject(async () => (await import("../../..")).MapValue),
            listValue: core.serialization.object({
                value: core.serialization.list(
                    core.serialization.lazy(async () => (await import("../../..")).VariableValue)
                ),
            }),
            binaryTreeValue: core.serialization.lazyObject(async () => (await import("../../..")).BinaryTreeValue),
            singlyLinkedListValue: core.serialization.lazyObject(
                async () => (await import("../../..")).SinglyLinkedListValue
            ),
            doublyLinkedListValue: core.serialization.lazyObject(
                async () => (await import("../../..")).DoublyLinkedListValue
            ),
            nullValue: core.serialization.object({}),
        })
        .transform<SeedTrace.VariableValue>({
            transform: (value) => {
                switch (value.type) {
                    case "integerValue":
                        return SeedTrace.VariableValue.integerValue(value.value);
                    case "booleanValue":
                        return SeedTrace.VariableValue.booleanValue(value.value);
                    case "doubleValue":
                        return SeedTrace.VariableValue.doubleValue(value.value);
                    case "stringValue":
                        return SeedTrace.VariableValue.stringValue(value.value);
                    case "charValue":
                        return SeedTrace.VariableValue.charValue(value.value);
                    case "mapValue":
                        return SeedTrace.VariableValue.mapValue(value);
                    case "listValue":
                        return SeedTrace.VariableValue.listValue(value.value);
                    case "binaryTreeValue":
                        return SeedTrace.VariableValue.binaryTreeValue(value);
                    case "singlyLinkedListValue":
                        return SeedTrace.VariableValue.singlyLinkedListValue(value);
                    case "doublyLinkedListValue":
                        return SeedTrace.VariableValue.doublyLinkedListValue(value);
                    case "nullValue":
                        return SeedTrace.VariableValue.nullValue();
                    default:
                        return SeedTrace.VariableValue._unknown(value);
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace VariableValue {
    type Raw =
        | VariableValue.IntegerValue
        | VariableValue.BooleanValue
        | VariableValue.DoubleValue
        | VariableValue.StringValue
        | VariableValue.CharValue
        | VariableValue.MapValue
        | VariableValue.ListValue
        | VariableValue.BinaryTreeValue
        | VariableValue.SinglyLinkedListValue
        | VariableValue.DoublyLinkedListValue
        | VariableValue.NullValue;

    interface IntegerValue {
        type: "integerValue";
        value: number;
    }

    interface BooleanValue {
        type: "booleanValue";
        value: boolean;
    }

    interface DoubleValue {
        type: "doubleValue";
        value: number;
    }

    interface StringValue {
        type: "stringValue";
        value: string;
    }

    interface CharValue {
        type: "charValue";
        value: string;
    }

    interface MapValue extends serializers.MapValue.Raw {
        type: "mapValue";
    }

    interface ListValue {
        type: "listValue";
        value: serializers.VariableValue.Raw[];
    }

    interface BinaryTreeValue extends serializers.BinaryTreeValue.Raw {
        type: "binaryTreeValue";
    }

    interface SinglyLinkedListValue extends serializers.SinglyLinkedListValue.Raw {
        type: "singlyLinkedListValue";
    }

    interface DoublyLinkedListValue extends serializers.DoublyLinkedListValue.Raw {
        type: "doublyLinkedListValue";
    }

    interface NullValue {
        type: "nullValue";
    }
}
