export const RESPONSE_VARIABLE_NAME = "response";
export const QUERY_PARAMETERS_VARIABLE_NAME = "queryParameters";

export const FETCHER_REQUEST_URL_PARAMETER_NAME = "url";
export const FETCHER_REQUEST_METHOD_PARAMETER_NAME = "method";
export const FETCHER_REQUEST_HEADER_PARAMETER_NAME = "headers";
export const FETCHER_REQUEST_QUERY_PARAMS_PARAMETER_NAME = "queryParameters";

export const FETCHER_REQUEST_BODY_PROPERTY_NAME = "body";
export const FETCHER_REQUEST_BODY_CONTENT_PROPERTY_NAME = "content";
export const FETCHER_REQUEST_BODY_CONTENT_TYPE_PROPERTY_NAME = "contentType";

export const FETCHER_REQUEST_TOKEN_PROPERTY_NAME = "token";
export const FETCHER_RESPONSE_STATUS_CODE_PROPERTY_NAME = "statusCode";
export const FETCHER_RESPONSE_BODY_PROPERTY_NAME = "body";
