# frozen_string_literal: true

require_relative "fern_query_parameters_openapi_as_objects/types/user"
require_relative "fern_query_parameters_openapi_as_objects/types/nested_user"
require_relative "fern_query_parameters_openapi_as_objects/types/search_request_neighbor"
require_relative "fern_query_parameters_openapi_as_objects/types/search_request_neighbor_required"
require_relative "fern_query_parameters_openapi_as_objects/types/search_response"
