// Code generated by Fern. DO NOT EDIT.

package gopaginationoffsetitemindex

import (
	internal "github.com/go-pagination-offset-item-index/fern/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{}
