// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../index.js";

export interface PaginatedConversationResponse {
    conversations: SeedApi.pagination.Conversation[];
    pages?: (SeedApi.pagination.CursorPages | null) | undefined;
    total_count: number;
    type: PaginatedConversationResponse.Type;
}

export namespace PaginatedConversationResponse {
    export const Type = {
        ConversationList: "conversation.list",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
