export { FernIr as V62, FernIr as V61 } from "@fern-api/ir-sdk";
export * as V1 from "@fern-fern/ir-v1-model";
export * as V2 from "@fern-fern/ir-v2-model";
export * as V3 from "@fern-fern/ir-v3-model";
export * as V4 from "@fern-fern/ir-v4-model";
export * as V5 from "@fern-fern/ir-v5-model";
export * as V6 from "@fern-fern/ir-v6-model";
export * as V7 from "@fern-fern/ir-v7-model";
export * as V8 from "@fern-fern/ir-v8-model";
export * as V9 from "@fern-fern/ir-v9-model";
export * as V10 from "@fern-fern/ir-v10-model";
export * as V11 from "@fern-fern/ir-v11-model";
export * as V12 from "@fern-fern/ir-v12-model";
export * as V13 from "@fern-fern/ir-v13-model";
export * as V14 from "@fern-fern/ir-v14-model";
export * as V15 from "@fern-fern/ir-v15-model";
export * as V16 from "@fern-fern/ir-v16-model";
export * as V17 from "@fern-fern/ir-v17-model";
export * as V18 from "@fern-fern/ir-v18-model";
export * as V19 from "@fern-fern/ir-v19-model";
export * as V20 from "@fern-fern/ir-v20-model";
export * as V21 from "@fern-fern/ir-v21-model";
export * as V22 from "@fern-fern/ir-v22-model";
export { FernIrV23 as V23 } from "@fern-fern/ir-v23-sdk";
export { FernIrV24 as V24 } from "@fern-fern/ir-v24-sdk";
export { FernIrV25 as V25 } from "@fern-fern/ir-v25-sdk";
export { FernIrV26 as V26 } from "@fern-fern/ir-v26-sdk";
export { FernIrV27 as V27 } from "@fern-fern/ir-v27-sdk";
export { FernIrV28 as V28 } from "@fern-fern/ir-v28-sdk";
export { FernIrV29 as V29 } from "@fern-fern/ir-v29-sdk";
export { FernIrV30 as V30 } from "@fern-fern/ir-v30-sdk";
export { FernIrV31 as V31 } from "@fern-fern/ir-v31-sdk";
export { FernIrV32 as V32 } from "@fern-fern/ir-v32-sdk";
export { FernIrV33 as V33 } from "@fern-fern/ir-v33-sdk";
export { FernIrV34 as V34 } from "@fern-fern/ir-v34-sdk";
export { FernIrV35 as V35 } from "@fern-fern/ir-v35-sdk";
export { FernIrV36 as V36 } from "@fern-fern/ir-v36-sdk";
export { FernIrV37 as V37 } from "@fern-fern/ir-v37-sdk";
export { FernIrV38 as V38 } from "@fern-fern/ir-v38-sdk";
export { FernIrV39 as V39 } from "@fern-fern/ir-v39-sdk";
export { FernIrV40 as V40 } from "@fern-fern/ir-v40-sdk";
export { FernIrV41 as V41 } from "@fern-fern/ir-v41-sdk";
export { FernIrV42 as V42 } from "@fern-fern/ir-v42-sdk";
export { FernIrV43 as V43 } from "@fern-fern/ir-v43-sdk";
export { FernIrV44 as V44 } from "@fern-fern/ir-v44-sdk";
export { FernIrV45 as V45 } from "@fern-fern/ir-v45-sdk";
export { FernIrV46 as V46 } from "@fern-fern/ir-v46-sdk";
export { FernIrV47 as V47 } from "@fern-fern/ir-v47-sdk";
export { FernIrV48 as V48 } from "@fern-fern/ir-v48-sdk";
export { FernIrV49 as V49 } from "@fern-fern/ir-v49-sdk";
export { FernIrV50 as V50 } from "@fern-fern/ir-v50-sdk";
export { FernIrV51 as V51 } from "@fern-fern/ir-v51-sdk";
export { FernIrV52 as V52 } from "@fern-fern/ir-v52-sdk";
export { FernIrV53 as V53 } from "@fern-fern/ir-v53-sdk";
export { FernIrV54 as V54 } from "@fern-fern/ir-v54-sdk";
export { FernIrV55 as V55 } from "@fern-fern/ir-v55-sdk";
export { FernIrV56 as V56 } from "@fern-fern/ir-v56-sdk";
export { FernIrV57 as V57 } from "@fern-fern/ir-v57-sdk";
export { FernIrV58 as V58 } from "@fern-fern/ir-v58-sdk";
export { FernIrV59 as V59 } from "@fern-fern/ir-v59-sdk";
export { FernIrV60 as V60 } from "@fern-fern/ir-v60-sdk";
