export { FernIr as V29 } from "@fern-fern/ir-sdk";
export * as V1 from "@fern-fern/ir-v1-model";
export * as V10 from "@fern-fern/ir-v10-model";
export * as V11 from "@fern-fern/ir-v11-model";
export * as V12 from "@fern-fern/ir-v12-model";
export * as V13 from "@fern-fern/ir-v13-model";
export * as V14 from "@fern-fern/ir-v14-model";
export * as V15 from "@fern-fern/ir-v15-model";
export * as V16 from "@fern-fern/ir-v16-model";
export * as V17 from "@fern-fern/ir-v17-model";
export * as V18 from "@fern-fern/ir-v18-model";
export * as V19 from "@fern-fern/ir-v19-model";
export * as V2 from "@fern-fern/ir-v2-model";
export * as V20 from "@fern-fern/ir-v20-model";
export * as V21 from "@fern-fern/ir-v21-model";
export * as V22 from "@fern-fern/ir-v22-model";
export { FernIrV23 as V23 } from "@fern-fern/ir-v23-sdk";
export { FernIrV24 as V24 } from "@fern-fern/ir-v24-sdk";
export { FernIrV25 as V25 } from "@fern-fern/ir-v25-sdk";
export { FernIrV26 as V26 } from "@fern-fern/ir-v26-sdk";
export { FernIrV27 as V27 } from "@fern-fern/ir-v27-sdk";
export { FernIrV28 as V28 } from "@fern-fern/ir-v28-sdk";
export * as V3 from "@fern-fern/ir-v3-model";
export * as V4 from "@fern-fern/ir-v4-model";
export * as V5 from "@fern-fern/ir-v5-model";
export * as V6 from "@fern-fern/ir-v6-model";
export * as V7 from "@fern-fern/ir-v7-model";
export * as V8 from "@fern-fern/ir-v8-model";
export * as V9 from "@fern-fern/ir-v9-model";
