// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "user_id",
 *         limit: 1
 *     }
 */
export interface SearchUsersRequest {
    userId: string;
    limit?: number;
}

export namespace SearchUsersRequest {
    export namespace _ {
        export function qs(request: SearchUsersRequest): Record<string, unknown> {
            return {
                limit: request.limit,
            };
        }
    }
}
