// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../index.js";

export interface UnionWithBasePropertiesZero {
    type: SeedApi.UnionWithBasePropertiesZeroType;
    value?: number;
}
