/**
 * This file was auto-generated by Fern from our API Definition.
 */

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import types.TypeId;

@RequestMapping(
    path = "/"
)
public interface RootService {
  @GetMapping(
      value = "/{typeId}",
      produces = "application/json"
  )
  void get(@PathVariable("typeId") TypeId typeId);
}
