export * as getAndReturnString from "./getAndReturnString.js";
export * as getAndReturnInt from "./getAndReturnInt.js";
export * as getAndReturnLong from "./getAndReturnLong.js";
export * as getAndReturnDouble from "./getAndReturnDouble.js";
export * as getAndReturnBool from "./getAndReturnBool.js";
export * as getAndReturnDatetime from "./getAndReturnDatetime.js";
export * as getAndReturnDate from "./getAndReturnDate.js";
export * as getAndReturnUuid from "./getAndReturnUuid.js";
export * as getAndReturnBase64 from "./getAndReturnBase64.js";
