/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SeedAudiencesClient } from "../src/Client";

const client = new SeedAudiencesClient({ environment: process.env.TESTS_BASE_URL || "test" });

describe("Foo", () => {
    test("constructor", () => {
        expect(client.foo).toBeDefined();
    });
});
