// This file was auto-generated by Fern from our API Definition.

import * as SeedPagination from "../../../index.js";

export interface Page {
    /** The current page */
    page: number;
    next?: SeedPagination.NextPage;
    per_page: number;
    total_page: number;
}
