/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FernDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { TypeReferenceDetailed } from "../../types/types/TypeReferenceDetailed";

export const HttpHeaderSchema: core.serialization.ObjectSchema<
    serializers.HttpHeaderSchema.Raw,
    FernDefinition.HttpHeaderSchema
> = core.serialization
    .object({
        env: core.serialization.string().optional(),
    })
    .extend(TypeReferenceDetailed);

export declare namespace HttpHeaderSchema {
    interface Raw extends TypeReferenceDetailed.Raw {
        env?: string | null;
    }
}
