// This file was auto-generated by Fern from our API Definition.

import type * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ResponseError } from "./ResponseError.js";

export const ResponseErrorsSchema: core.serialization.Schema<
    serializers.ResponseErrorsSchema.Raw,
    FernDefinition.ResponseErrorsSchema
> = core.serialization.list(ResponseError);

export declare namespace ResponseErrorsSchema {
    export type Raw = ResponseError.Raw[];
}
