/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.nullable.resources.nullable;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.seed.nullable.core.ClientOptions;
import com.seed.nullable.core.MediaTypes;
import com.seed.nullable.core.ObjectMappers;
import com.seed.nullable.core.QueryStringMapper;
import com.seed.nullable.core.RequestOptions;
import com.seed.nullable.core.SeedNullableApiException;
import com.seed.nullable.core.SeedNullableException;
import com.seed.nullable.core.SeedNullableHttpResponse;
import com.seed.nullable.resources.nullable.requests.CreateUserRequest;
import com.seed.nullable.resources.nullable.requests.DeleteUserRequest;
import com.seed.nullable.resources.nullable.requests.GetUsersRequest;
import com.seed.nullable.resources.nullable.types.User;
import java.io.IOException;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawNullableClient {
    protected final ClientOptions clientOptions;

    public RawNullableClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public SeedNullableHttpResponse<List<User>> getUsers() {
        return getUsers(GetUsersRequest.builder().build());
    }

    public SeedNullableHttpResponse<List<User>> getUsers(GetUsersRequest request) {
        return getUsers(request, null);
    }

    public SeedNullableHttpResponse<List<User>> getUsers(GetUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users");
        if (request.getAvatar().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "avatar", request.getAvatar().get(), false);
        }
        if (request.getExtra().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "extra", request.getExtra().get(), false);
        }
        if (request.getUsernames().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "usernames", request.getUsernames().get(), true);
        }
        if (request.getActivated().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "activated", request.getActivated().get(), true);
        }
        if (request.getTags().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "tags", request.getTags().get(), true);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new SeedNullableHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<List<User>>() {}),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new SeedNullableApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new SeedNullableException("Network error executing HTTP request", e);
        }
    }

    public SeedNullableHttpResponse<User> createUser(CreateUserRequest request) {
        return createUser(request, null);
    }

    public SeedNullableHttpResponse<User> createUser(CreateUserRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new SeedNullableException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new SeedNullableHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), User.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new SeedNullableApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new SeedNullableException("Network error executing HTTP request", e);
        }
    }

    public SeedNullableHttpResponse<Boolean> deleteUser() {
        return deleteUser(DeleteUserRequest.builder().build());
    }

    public SeedNullableHttpResponse<Boolean> deleteUser(DeleteUserRequest request) {
        return deleteUser(request, null);
    }

    public SeedNullableHttpResponse<Boolean> deleteUser(DeleteUserRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new SeedNullableException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new SeedNullableHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), boolean.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new SeedNullableApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new SeedNullableException("Network error executing HTTP request", e);
        }
    }
}
