*
!generators/typescript/asIs/
!generators/typescript/utils/core-utilities/**/src/
!generators/typescript/utils/core-utilities/**/tests/
!generators/typescript/sdk/features.yml
!generators/typescript/sdk/cli/node-docker/dist/nodeCli.cjs