// This file was auto-generated by Fern from our API Definition.

import type * as acme from "../../../../../../index.js";

/**
 * @example
 *     {
 *         actionId: "actionId",
 *         id: "id",
 *         body: {}
 *     }
 */
export interface SendOptionalNullableWithAllOptionalPropertiesOptionalRequest {
    actionId: string;
    id: string;
    body: acme.optional.DeployParams | null;
}
