// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { ServiceClient } from "../resources/service/client/Client.js";

export declare namespace HealthClient {
    export type Options = BaseClientOptions;
}

export class HealthClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<HealthClient.Options>;
    protected _service: ServiceClient | undefined;

    constructor(options: HealthClient.Options) {


                        this._options = normalizeClientOptionsWithAuth(options);
                    
    }

    public get service(): ServiceClient {
        return (this._service ??= new ServiceClient(this._options));
    }
}
