openapi: 3.1.0
info:
  title: api
  version: 0.0.0
paths:
  /movies/create-movie:
    post:
      description: Add a movie to the database using the movies/* /... path.
      operationId: imdb_createMovie
      tags:
        - Imdb
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieId'
      x-fern-availability: pre-release
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMovieRequest'
  /movies/{movieId}:
    get:
      operationId: imdb_getMovie
      tags:
        - Imdb
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/MovieId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: MovieDoesNotExistError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieId'
      x-fern-availability: deprecated
components:
  schemas:
    MovieId:
      title: MovieId
      type: string
    Movie:
      title: Movie
      type: object
      properties:
        id:
          $ref: '#/components/schemas/MovieId'
        title:
          type: string
        rating:
          type: number
          format: double
          description: The rating scale is one to five stars
          x-fern-availability: deprecated
      required:
        - id
        - title
        - rating
      x-fern-availability: generally-available
    CreateMovieRequest:
      title: CreateMovieRequest
      type: object
      properties:
        title:
          type: string
        rating:
          type: number
          format: double
      required:
        - title
        - rating
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
