pub use crate::prelude::*;

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SpecialEnum {
    A,
    B,
    C,
    D,
    E,
    F,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Aa,
    Bb,
    Cc,
    Dd,
    Ee,
    Ff,
    Gg,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for SpecialEnum {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::A => serializer.serialize_str(""),
            Self::B => serializer.serialize_str("Hello \\\"World\\\""),
            Self::C => serializer.serialize_str("Hello 'World'"),
            Self::D => serializer.serialize_str("Hello\\\\World"),
            Self::E => serializer.serialize_str("Hello\\nWorld"),
            Self::F => serializer.serialize_str("Hello\\rWorld"),
            Self::H => serializer.serialize_str("Hello\\tWorld"),
            Self::I => serializer.serialize_str("Hello\\fWorld"),
            Self::J => serializer.serialize_str("Hello\\u0008World"),
            Self::K => serializer.serialize_str("Hello\\vWorld"),
            Self::L => serializer.serialize_str("Hello\\x00World"),
            Self::M => serializer.serialize_str("Hello\\u0007World"),
            Self::N => serializer.serialize_str("Hello\\u0001World"),
            Self::O => serializer.serialize_str("Hello\\u0002World"),
            Self::P => serializer.serialize_str("Hello\\u001FWorld"),
            Self::Q => serializer.serialize_str("Hello\\u007FWorld"),
            Self::R => serializer.serialize_str("Hello\\u009FWorld"),
            Self::S => serializer.serialize_str("Line 1\\n\"Quote\"\\tTab\\\\Backslash\\r\\nLine 2\\0Null"),
            Self::T => serializer.serialize_str("\\n\\r\\t\\x00\\u0008\\f\\v\\u0007"),
            Self::U => serializer.serialize_str("Hello 世界"),
            Self::V => serializer.serialize_str("café"),
            Self::W => serializer.serialize_str("🚀"),
            Self::X => serializer.serialize_str("\\\\n"),
            Self::Y => serializer.serialize_str("\\\\"),
            Self::Z => serializer.serialize_str("{\"name\": \"John\", \"age\": 30, \"city\": \"New York\"}"),
            Self::Aa => serializer.serialize_str("SELECT * FROM users WHERE name = 'John O\\\\'Reilly'"),
            Self::Bb => serializer.serialize_str("C:\\\\Users\\\\John\\\\Documents\\\\file.txt"),
            Self::Cc => serializer.serialize_str("/usr/local/bin/app"),
            Self::Dd => serializer.serialize_str("\\\\d{3}-\\\\d{2}-\\\\d{4}"),
            Self::Ee => serializer.serialize_str("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}"),
            Self::Ff => serializer.serialize_str("transcript[transcriptType=\"final\"]"),
            Self::Gg => serializer.serialize_str("transcript[transcriptType='final']"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for SpecialEnum {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "" => Ok(Self::A),
            "Hello \\\"World\\\"" => Ok(Self::B),
            "Hello 'World'" => Ok(Self::C),
            "Hello\\\\World" => Ok(Self::D),
            "Hello\\nWorld" => Ok(Self::E),
            "Hello\\rWorld" => Ok(Self::F),
            "Hello\\tWorld" => Ok(Self::H),
            "Hello\\fWorld" => Ok(Self::I),
            "Hello\\u0008World" => Ok(Self::J),
            "Hello\\vWorld" => Ok(Self::K),
            "Hello\\x00World" => Ok(Self::L),
            "Hello\\u0007World" => Ok(Self::M),
            "Hello\\u0001World" => Ok(Self::N),
            "Hello\\u0002World" => Ok(Self::O),
            "Hello\\u001FWorld" => Ok(Self::P),
            "Hello\\u007FWorld" => Ok(Self::Q),
            "Hello\\u009FWorld" => Ok(Self::R),
            "Line 1\\n\"Quote\"\\tTab\\\\Backslash\\r\\nLine 2\\0Null" => Ok(Self::S),
            "\\n\\r\\t\\x00\\u0008\\f\\v\\u0007" => Ok(Self::T),
            "Hello 世界" => Ok(Self::U),
            "café" => Ok(Self::V),
            "🚀" => Ok(Self::W),
            "\\\\n" => Ok(Self::X),
            "\\\\" => Ok(Self::Y),
            "{\"name\": \"John\", \"age\": 30, \"city\": \"New York\"}" => Ok(Self::Z),
            "SELECT * FROM users WHERE name = 'John O\\\\'Reilly'" => Ok(Self::Aa),
            "C:\\\\Users\\\\John\\\\Documents\\\\file.txt" => Ok(Self::Bb),
            "/usr/local/bin/app" => Ok(Self::Cc),
            "\\\\d{3}-\\\\d{2}-\\\\d{4}" => Ok(Self::Dd),
            "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}" => Ok(Self::Ee),
            "transcript[transcriptType=\"final\"]" => Ok(Self::Ff),
            "transcript[transcriptType='final']" => Ok(Self::Gg),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for SpecialEnum {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::A => write!(f, ""),
            Self::B => write!(f, "Hello \\\"World\\\""),
            Self::C => write!(f, "Hello 'World'"),
            Self::D => write!(f, "Hello\\\\World"),
            Self::E => write!(f, "Hello\\nWorld"),
            Self::F => write!(f, "Hello\\rWorld"),
            Self::H => write!(f, "Hello\\tWorld"),
            Self::I => write!(f, "Hello\\fWorld"),
            Self::J => write!(f, "Hello\\u0008World"),
            Self::K => write!(f, "Hello\\vWorld"),
            Self::L => write!(f, "Hello\\x00World"),
            Self::M => write!(f, "Hello\\u0007World"),
            Self::N => write!(f, "Hello\\u0001World"),
            Self::O => write!(f, "Hello\\u0002World"),
            Self::P => write!(f, "Hello\\u001FWorld"),
            Self::Q => write!(f, "Hello\\u007FWorld"),
            Self::R => write!(f, "Hello\\u009FWorld"),
            Self::S => write!(f, "Line 1\\n\"Quote\"\\tTab\\\\Backslash\\r\\nLine 2\\0Null"),
            Self::T => write!(f, "\\n\\r\\t\\x00\\u0008\\f\\v\\u0007"),
            Self::U => write!(f, "Hello 世界"),
            Self::V => write!(f, "café"),
            Self::W => write!(f, "🚀"),
            Self::X => write!(f, "\\\\n"),
            Self::Y => write!(f, "\\\\"),
            Self::Z => write!(f, "{\"name\": \"John\", \"age\": 30, \"city\": \"New York\"}"),
            Self::Aa => write!(f, "SELECT * FROM users WHERE name = 'John O\\\\'Reilly'"),
            Self::Bb => write!(f, "C:\\\\Users\\\\John\\\\Documents\\\\file.txt"),
            Self::Cc => write!(f, "/usr/local/bin/app"),
            Self::Dd => write!(f, "\\\\d{3}-\\\\d{2}-\\\\d{4}"),
            Self::Ee => write!(f, "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}"),
            Self::Ff => write!(f, "transcript[transcriptType=\"final\"]"),
            Self::Gg => write!(f, "transcript[transcriptType='final']"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
