# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "minitest", "~> 5.0"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.21"

gem "dotenv", "~> 2.1"
gem "faraday", ">= 0.20.0", "> 0.17.3"
