// This file was auto-generated by Fern from our API Definition.

import express from "express";
import * as errors from "../../../../errors/index";
import * as serializers from "../../../../serialization/index";
import type * as SeedPagination from "../../../index";

export interface UsersServiceMethods {
    listWithCursorPagination(
        req: express.Request<
            never,
            SeedPagination.ListUsersPaginationResponse,
            never,
            {
                page?: number;
                per_page?: number;
                order?: SeedPagination.Order;
                starting_after?: string;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithMixedTypeCursorPagination(
        req: express.Request<
            never,
            SeedPagination.ListUsersMixedTypePaginationResponse,
            never,
            {
                cursor?: string;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersMixedTypePaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithBodyCursorPagination(
        req: express.Request<
            never,
            SeedPagination.ListUsersPaginationResponse,
            SeedPagination.ListUsersBodyCursorPaginationRequest,
            never
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithOffsetPagination(
        req: express.Request<
            never,
            SeedPagination.ListUsersPaginationResponse,
            never,
            {
                page?: number;
                per_page?: number;
                order?: SeedPagination.Order;
                starting_after?: string;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithDoubleOffsetPagination(
        req: express.Request<
            never,
            SeedPagination.ListUsersPaginationResponse,
            never,
            {
                page?: number;
                per_page?: number;
                order?: SeedPagination.Order;
                starting_after?: string;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithBodyOffsetPagination(
        req: express.Request<
            never,
            SeedPagination.ListUsersPaginationResponse,
            SeedPagination.ListUsersBodyOffsetPaginationRequest,
            never
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithOffsetStepPagination(
        req: express.Request<
            never,
            SeedPagination.ListUsersPaginationResponse,
            never,
            {
                page?: number;
                limit?: number;
                order?: SeedPagination.Order;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithOffsetPaginationHasNextPage(
        req: express.Request<
            never,
            SeedPagination.ListUsersPaginationResponse,
            never,
            {
                page?: number;
                limit?: number;
                order?: SeedPagination.Order;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersPaginationResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithExtendedResults(
        req: express.Request<
            never,
            SeedPagination.ListUsersExtendedResponse,
            never,
            {
                cursor?: string;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersExtendedResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithExtendedResultsAndOptionalData(
        req: express.Request<
            never,
            SeedPagination.ListUsersExtendedOptionalListResponse,
            never,
            {
                cursor?: string;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.ListUsersExtendedOptionalListResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listUsernames(
        req: express.Request<
            never,
            SeedPagination.UsernameCursor,
            never,
            {
                starting_after?: string;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.UsernameCursor) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    listWithGlobalConfig(
        req: express.Request<
            never,
            SeedPagination.UsernameContainer,
            never,
            {
                offset?: number;
            }
        >,
        res: {
            send: (responseBody: SeedPagination.UsernameContainer) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
}

export class UsersService {
    private router;

    constructor(
        private readonly methods: UsersServiceMethods,
        middleware: express.RequestHandler[] = [],
    ) {
        this.router = express.Router({ mergeParams: true }).use(
            express.json({
                strict: false,
            }),
            ...middleware,
        );
    }

    public addMiddleware(handler: express.RequestHandler): this {
        this.router.use(handler);
        return this;
    }

    public toRouter(): express.Router {
        this.router.get("", async (req, res, next) => {
            try {
                await this.methods.listWithCursorPagination(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.ListUsersPaginationResponse.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithCursorPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        this.router.post("", async (req, res, next) => {
            try {
                await this.methods.listWithMixedTypeCursorPagination(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.ListUsersMixedTypePaginationResponse.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithMixedTypeCursorPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        this.router.post("", async (req, res, next) => {
            const request = serializers.ListUsersBodyCursorPaginationRequest.parse(req.body);
            if (request.ok) {
                req.body = request.value;
                try {
                    await this.methods.listWithBodyCursorPagination(
                        req as any,
                        {
                            send: async (responseBody) => {
                                res.json(
                                    serializers.ListUsersPaginationResponse.jsonOrThrow(responseBody, {
                                        unrecognizedObjectKeys: "strip",
                                    }),
                                );
                            },
                            cookie: res.cookie.bind(res),
                            locals: res.locals,
                        },
                        next,
                    );
                    if (!res.writableEnded) {
                        next();
                    }
                } catch (error) {
                    if (error instanceof errors.SeedPaginationError) {
                        console.warn(
                            `Endpoint 'listWithBodyCursorPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        await error.send(res);
                    } else {
                        res.status(500).json("Internal Server Error");
                    }
                    next(error);
                }
            } else {
                res.status(422).json({
                    errors: request.errors.map(
                        (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                    ),
                });
                next(request.errors);
            }
        });
        this.router.get("", async (req, res, next) => {
            try {
                await this.methods.listWithOffsetPagination(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.ListUsersPaginationResponse.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithOffsetPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        this.router.get("", async (req, res, next) => {
            try {
                await this.methods.listWithDoubleOffsetPagination(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.ListUsersPaginationResponse.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithDoubleOffsetPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        this.router.post("", async (req, res, next) => {
            const request = serializers.ListUsersBodyOffsetPaginationRequest.parse(req.body);
            if (request.ok) {
                req.body = request.value;
                try {
                    await this.methods.listWithBodyOffsetPagination(
                        req as any,
                        {
                            send: async (responseBody) => {
                                res.json(
                                    serializers.ListUsersPaginationResponse.jsonOrThrow(responseBody, {
                                        unrecognizedObjectKeys: "strip",
                                    }),
                                );
                            },
                            cookie: res.cookie.bind(res),
                            locals: res.locals,
                        },
                        next,
                    );
                    if (!res.writableEnded) {
                        next();
                    }
                } catch (error) {
                    if (error instanceof errors.SeedPaginationError) {
                        console.warn(
                            `Endpoint 'listWithBodyOffsetPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                        );
                        await error.send(res);
                    } else {
                        res.status(500).json("Internal Server Error");
                    }
                    next(error);
                }
            } else {
                res.status(422).json({
                    errors: request.errors.map(
                        (error) => `${["request", ...error.path].join(" -> ")}: ${error.message}`,
                    ),
                });
                next(request.errors);
            }
        });
        this.router.get("", async (req, res, next) => {
            try {
                await this.methods.listWithOffsetStepPagination(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.ListUsersPaginationResponse.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithOffsetStepPagination' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        this.router.get("", async (req, res, next) => {
            try {
                await this.methods.listWithOffsetPaginationHasNextPage(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.ListUsersPaginationResponse.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithOffsetPaginationHasNextPage' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        this.router.get("", async (req, res, next) => {
            try {
                await this.methods.listWithExtendedResults(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.ListUsersExtendedResponse.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithExtendedResults' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        this.router.get("", async (req, res, next) => {
            try {
                await this.methods.listWithExtendedResultsAndOptionalData(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.ListUsersExtendedOptionalListResponse.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithExtendedResultsAndOptionalData' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        this.router.get("", async (req, res, next) => {
            try {
                await this.methods.listUsernames(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.UsernameCursor.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listUsernames' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        this.router.get("", async (req, res, next) => {
            try {
                await this.methods.listWithGlobalConfig(
                    req as any,
                    {
                        send: async (responseBody) => {
                            res.json(
                                serializers.UsernameContainer.jsonOrThrow(responseBody, {
                                    unrecognizedObjectKeys: "strip",
                                }),
                            );
                        },
                        cookie: res.cookie.bind(res),
                        locals: res.locals,
                    },
                    next,
                );
                if (!res.writableEnded) {
                    next();
                }
            } catch (error) {
                if (error instanceof errors.SeedPaginationError) {
                    console.warn(
                        `Endpoint 'listWithGlobalConfig' unexpectedly threw ${error.constructor.name}. If this was intentional, please add ${error.constructor.name} to the endpoint's errors list in your Fern Definition.`,
                    );
                    await error.send(res);
                } else {
                    res.status(500).json("Internal Server Error");
                }
                next(error);
            }
        });
        return this.router;
    }
}
