/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CodeExecutionUpdateOneType {
    public static final CodeExecutionUpdateOneType RUNNING = new CodeExecutionUpdateOneType(Value.RUNNING, "running");

    private final Value value;

    private final String string;

    CodeExecutionUpdateOneType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CodeExecutionUpdateOneType
                        && this.string.equals(((CodeExecutionUpdateOneType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case RUNNING:
                return visitor.visitRunning();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CodeExecutionUpdateOneType valueOf(String value) {
        switch (value) {
            case "running":
                return RUNNING;
            default:
                return new CodeExecutionUpdateOneType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        RUNNING,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitRunning();

        T visitUnknown(String unknownType);
    }
}
