/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SubmissionStatusForTestCaseTypeType {
    public static final SubmissionStatusForTestCaseTypeType GRADED_V2 =
            new SubmissionStatusForTestCaseTypeType(Value.GRADED_V2, "gradedV2");

    private final Value value;

    private final String string;

    SubmissionStatusForTestCaseTypeType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SubmissionStatusForTestCaseTypeType
                        && this.string.equals(((SubmissionStatusForTestCaseTypeType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case GRADED_V2:
                return visitor.visitGradedV2();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SubmissionStatusForTestCaseTypeType valueOf(String value) {
        switch (value) {
            case "gradedV2":
                return GRADED_V2;
            default:
                return new SubmissionStatusForTestCaseTypeType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        GRADED_V2,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitGradedV2();

        T visitUnknown(String unknownType);
    }
}
