/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SubmissionStatusV2ZeroType {
    public static final SubmissionStatusV2ZeroType TEST = new SubmissionStatusV2ZeroType(Value.TEST, "test");

    private final Value value;

    private final String string;

    SubmissionStatusV2ZeroType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SubmissionStatusV2ZeroType
                        && this.string.equals(((SubmissionStatusV2ZeroType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TEST:
                return visitor.visitTest();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SubmissionStatusV2ZeroType valueOf(String value) {
        switch (value) {
            case "test":
                return TEST;
            default:
                return new SubmissionStatusV2ZeroType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        TEST,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitTest();

        T visitUnknown(String unknownType);
    }
}
