/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.service;

import core.ApiKey;
import java.lang.String;
import java.security.Principal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;

@RequestMapping(
    path = "/"
)
public interface ServiceService {
  @GetMapping(
      value = "/apiKey",
      produces = "application/json"
  )
  String getWithApiKey(@RequestHeader("X-FERN-API-KEY") ApiKey auth, Principal principal,
      @RequestHeader("X-Another-Header") String xAnotherHeader);

  @GetMapping(
      value = "/apiKeyInHeader",
      produces = "application/json"
  )
  String getWithHeader(@RequestHeader("X-Another-Header") String xAnotherHeader,
      @RequestHeader("X-Endpoint-Header") String xEndpointHeader);
}
