FROM node:22.12-alpine3.20

RUN apk --no-cache add git

RUN corepack enable

ENV PNPM_STORE_PATH=/.pnpm-cache
ENV YARN_CACHE_FOLDER=/.yarn-cache
ENV PNPM_HOME=/.pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN npm install -g pnpm@10.20.0 --force
RUN npm install -g yarn@1.22.22 --force
RUN pnpm add -g typescript@~5.7.2 \
  @types/node@^18.19.70 \
  vitest@^3.2.4
