// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	core "github.com/nullable-request-body/fern/core"
)

// Validation Error
type UnprocessableEntityError struct {
	*core.APIError
	Body *PlainObject
}

func (u *UnprocessableEntityError) UnmarshalJSON(data []byte) error {
	var body *PlainObject
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 422
	u.Body = body
	return nil
}

func (u *UnprocessableEntityError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnprocessableEntityError) Unwrap() error {
	return u.APIError
}
