// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import type * as SeedExhaustive from "../../../../../index.js";

export declare namespace HttpMethodsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class HttpMethodsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<HttpMethodsClient.Options>;
    protected readonly _client: core.HttpClient;

    constructor(options: HttpMethodsClient.Options, client?: core.HttpClient) {
        this._options = normalizeClientOptionsWithAuth(options);
        this._client =
            client ??
            new core.HttpClient(
                this._options,
                (args) => new errors.SeedExhaustiveError(args),
                handleNonStatusCodeError,
            );
    }

    /**
     * @param {string} id
     * @param {HttpMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.endpoints.httpMethods.testGet("id")
     */
    public testGet(id: string, requestOptions?: HttpMethodsClient.RequestOptions): core.HttpResponsePromise<string> {
        return this._client.request<string>({
            method: "GET",
            path: `/http-methods/${core.url.encodePathParam(id)}`,
            queryParameters: requestOptions?.queryParams,
            requestOptions,
        });
    }

    /**
     * @deprecated
     *
     * @param {SeedExhaustive.types.ObjectWithRequiredField} request
     * @param {HttpMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.endpoints.httpMethods.testPost({
     *         string: "string"
     *     })
     */
    public testPost(
        request: SeedExhaustive.types.ObjectWithRequiredField,
        requestOptions?: HttpMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<SeedExhaustive.types.ObjectWithOptionalField> {
        return this._client.request<SeedExhaustive.types.ObjectWithOptionalField>({
            method: "POST",
            path: "/http-methods",
            body: request,
            contentType: "application/json",
            requestType: "json",
            queryParameters: requestOptions?.queryParams,
            requestOptions,
        });
    }

    /**
     * @deprecated Use testPatch instead.
     *
     * @param {string} id
     * @param {SeedExhaustive.types.ObjectWithRequiredField} request
     * @param {HttpMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.endpoints.httpMethods.testPut("id", {
     *         string: "string"
     *     })
     */
    public testPut(
        id: string,
        request: SeedExhaustive.types.ObjectWithRequiredField,
        requestOptions?: HttpMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<SeedExhaustive.types.ObjectWithOptionalField> {
        return this._client.request<SeedExhaustive.types.ObjectWithOptionalField>({
            method: "PUT",
            path: `/http-methods/${core.url.encodePathParam(id)}`,
            body: request,
            contentType: "application/json",
            requestType: "json",
            queryParameters: requestOptions?.queryParams,
            requestOptions,
        });
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * @param {string} id
     * @param {SeedExhaustive.types.ObjectWithOptionalField} request
     * @param {HttpMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.endpoints.httpMethods.testPatch("id", {
     *         string: "string",
     *         integer: 1,
     *         long: BigInt("1000000"),
     *         double: 1.1,
     *         bool: true,
     *         datetime: "2024-01-15T09:30:00Z",
     *         date: "2023-01-15",
     *         uuid: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
     *         base64: "SGVsbG8gd29ybGQh",
     *         list: ["list", "list"],
     *         set: ["set"],
     *         map: {
     *             1: "map"
     *         },
     *         bigint: BigInt("1000000")
     *     })
     */
    public testPatch(
        id: string,
        request: SeedExhaustive.types.ObjectWithOptionalField,
        requestOptions?: HttpMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<SeedExhaustive.types.ObjectWithOptionalField> {
        return this._client.request<SeedExhaustive.types.ObjectWithOptionalField>({
            method: "PATCH",
            path: `/http-methods/${core.url.encodePathParam(id)}`,
            body: request,
            contentType: "application/json",
            requestType: "json",
            queryParameters: requestOptions?.queryParams,
            requestOptions,
        });
    }

    /**
     * @beta This endpoint is in development and may change.
     *
     * @param {string} id
     * @param {HttpMethodsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.endpoints.httpMethods.testDelete("id")
     */
    public testDelete(
        id: string,
        requestOptions?: HttpMethodsClient.RequestOptions,
    ): core.HttpResponsePromise<boolean> {
        return this._client.request<boolean>({
            method: "DELETE",
            path: `/http-methods/${core.url.encodePathParam(id)}`,
            queryParameters: requestOptions?.queryParams,
            requestOptions,
        });
    }
}
