import path from "path";

export const DOCKER_FERN_DIRECTORY = "/fern";
export const CODEGEN_OUTPUT_DIRECTORY_NAME = "output";
export const GENERATOR_CONFIG_FILENAME = "config.json";
export const IR_FILENAME = "ir.json";
export const SNIPPET_FILENAME = "snippet.json";
export const SNIPPET_TEMPLATES_FILENAME = "snippet-templates.json";
export const GENERATORS_DIRECTORY_NAME = "generators";
export const SOURCES_DIRECTORY_NAME = "sources";

export const DOCKER_CODEGEN_OUTPUT_DIRECTORY: string = path.join(DOCKER_FERN_DIRECTORY, CODEGEN_OUTPUT_DIRECTORY_NAME);
export const DOCKER_GENERATOR_CONFIG_PATH: string = path.join(DOCKER_FERN_DIRECTORY, GENERATOR_CONFIG_FILENAME);
export const DOCKER_PATH_TO_IR: string = path.join(DOCKER_FERN_DIRECTORY, IR_FILENAME);
export const DOCKER_PATH_TO_SNIPPET: string = path.join(DOCKER_FERN_DIRECTORY, SNIPPET_FILENAME);
export const DOCKER_PATH_TO_SNIPPET_TEMPLATES: string = path.join(DOCKER_FERN_DIRECTORY, SNIPPET_TEMPLATES_FILENAME);
export const DOCKER_GENERATORS_DIRECTORY: string = path.join(DOCKER_FERN_DIRECTORY, GENERATORS_DIRECTORY_NAME);
export const DOCKER_SOURCES_DIRECTORY: string = path.join(DOCKER_FERN_DIRECTORY, SOURCES_DIRECTORY_NAME);

export const CONTAINER_FERN_DIRECTORY: "/fern" = DOCKER_FERN_DIRECTORY;
export const CONTAINER_CODEGEN_OUTPUT_DIRECTORY: string = DOCKER_CODEGEN_OUTPUT_DIRECTORY;
export const CONTAINER_GENERATOR_CONFIG_PATH: string = DOCKER_GENERATOR_CONFIG_PATH;
export const CONTAINER_PATH_TO_IR: string = DOCKER_PATH_TO_IR;
export const CONTAINER_PATH_TO_SNIPPET: string = DOCKER_PATH_TO_SNIPPET;
export const CONTAINER_PATH_TO_SNIPPET_TEMPLATES: string = DOCKER_PATH_TO_SNIPPET_TEMPLATES;
export const CONTAINER_GENERATORS_DIRECTORY: string = DOCKER_GENERATORS_DIRECTORY;
export const CONTAINER_SOURCES_DIRECTORY: string = DOCKER_SOURCES_DIRECTORY;

export const DEFAULT_NODE_DEBUG_PORT = "9229";
