// This file was auto-generated by Fern from our API Definition.

import { ServiceClient } from "./api/resources/service/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import * as core from "./core/index.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";

export declare namespace SeedFileUploadClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SeedFileUploadClient {
    protected readonly _options: NormalizedClientOptions<SeedFileUploadClient.Options>;
    protected readonly _client: core.HttpClient;
    protected _service: ServiceClient | undefined;

    constructor(options: SeedFileUploadClient.Options) {
        this._options = normalizeClientOptions(options);
        this._client = new core.HttpClient(
            this._options,
            (args) => new errors.SeedFileUploadError(args),
            handleNonStatusCodeError,
        );
    }

    public get service(): ServiceClient {
        return (this._service ??= new ServiceClient(this._options, this._client));
    }
}
