openapi: 3.0.1
info:
  title: mixed-case
  version: ''
paths:
  /resource/{ResourceID}:
    get:
      operationId: service_getresource
      tags:
        - Service
      parameters:
        - name: ResourceID
          in: path
          required: true
          schema:
            type: string
          example: ResourceID
          examples:
            Example1:
              value: ResourceID
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
              examples:
                Example1:
                  value:
                    userName: userName
                    metadata_tags:
                      - metadata_tags
                    EXTRA_PROPERTIES:
                      key: value
                    resource_type: user
  /resource:
    get:
      operationId: service_listresources
      tags:
        - Service
      parameters:
        - name: page_limit
          in: query
          required: true
          schema:
            type: integer
          example: 1
          examples:
            Example1:
              value: 1
        - name: beforeDate
          in: query
          required: true
          schema:
            type: string
            format: date
          example: '2023-01-15'
          examples:
            Example1:
              value: '2023-01-15'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
              examples:
                Example1:
                  value:
                    - userName: userName
                      metadata_tags:
                        - metadata_tags
                      EXTRA_PROPERTIES:
                        key: value
                      resource_type: user
components:
  schemas:
    Organization:
      title: Organization
      type: object
      properties:
        name:
          type: string
      required:
        - name
    User:
      title: User
      type: object
      properties:
        userName:
          type: string
        metadata_tags:
          type: array
          items:
            type: string
        EXTRA_PROPERTIES:
          type: object
          additionalProperties:
            type: string
      required:
        - userName
        - metadata_tags
        - EXTRA_PROPERTIES
    NestedUser:
      title: NestedUser
      type: object
      properties:
        Name:
          type: string
        NestedUser:
          $ref: '#/components/schemas/User'
      required:
        - Name
        - NestedUser
    ResourceStatus:
      title: ResourceStatus
      type: string
      enum:
        - ACTIVE
        - INACTIVE
    ResourceZeroResourceType:
      title: ResourceZeroResourceType
      type: string
      enum:
        - user
    ResourceZero:
      title: ResourceZero
      type: object
      properties:
        resource_type:
          $ref: '#/components/schemas/ResourceZeroResourceType'
      required:
        - resource_type
      allOf:
        - $ref: '#/components/schemas/User'
    ResourceOneResourceType:
      title: ResourceOneResourceType
      type: string
      enum:
        - Organization
    ResourceOne:
      title: ResourceOne
      type: object
      properties:
        resource_type:
          $ref: '#/components/schemas/ResourceOneResourceType'
      required:
        - resource_type
      allOf:
        - $ref: '#/components/schemas/Organization'
    Resource:
      title: Resource
      oneOf:
        - $ref: '#/components/schemas/ResourceZero'
        - $ref: '#/components/schemas/ResourceOne'
  securitySchemes: {}
