# frozen_string_literal: true

require_relative "seed_api_client/types/importing_a"
require_relative "seed_api_client/types/root_type"
require_relative "seed_api_client/a/types/a"
require_relative "seed_api_client/ast/types/cat"
require_relative "seed_api_client/ast/types/dog"
require_relative "seed_api_client/ast/types/animal"
require_relative "seed_api_client/ast/types/acai"
require_relative "seed_api_client/ast/types/fig"
require_relative "seed_api_client/ast/types/fruit"
require_relative "seed_api_client/ast/types/container_value"
require_relative "seed_api_client/ast/types/primitive_value"
require_relative "seed_api_client/ast/types/object_value"
require_relative "seed_api_client/ast/types/field_value"
require_relative "seed_api_client/ast/types/object_field_value"
