openapi: 3.1.0
info:
  title: bytes-upload
  version: 0.0.0
paths:
  /upload-content:
    post:
      operationId: service_upload
      tags:
        - Service
      parameters: []
      responses:
        '204':
          description: No content
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
  /upload-content-with-query-params:
    post:
      operationId: service_uploadWithQueryParams
      tags:
        - Service
      parameters:
        - name: model
          in: query
          description: The model to use for processing
          required: true
          schema:
            type: string
          examples:
            Example1:
              value: nova-2
        - name: language
          in: query
          description: The language of the content
          required: false
          schema:
            type:
              - string
              - 'null'
      responses:
        '204':
          description: No content
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
components:
  schemas: {}
  securitySchemes: {}
