/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.api;

import com.seed.api.core.ClientOptions;
import com.seed.api.core.Suppliers;
import com.seed.api.svc._SvcClient;
import java.util.function.Supplier;

public class Api {
    protected final ClientOptions clientOptions;

    protected final Supplier<_SvcClient> svcClient;

    public Api(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.svcClient = Suppliers.memoize(() -> new _SvcClient(clientOptions));
    }

    public _SvcClient svc() {
        return this.svcClient.get();
    }

    public static ApiBuilder builder() {
        return new ApiBuilder();
    }
}
