// Code generated by Fern. DO NOT EDIT.

package errors

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/errors/fern/internal"
)

type ErrorBody struct {
	Message string `json:"message" url:"message"`
	Code    int    `json:"code" url:"code"`

	extraProperties map[string]interface{}
}

func (e *ErrorBody) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *ErrorBody) GetCode() int {
	if e == nil {
		return 0
	}
	return e.Code
}

func (e *ErrorBody) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *ErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	return nil
}

func (e *ErrorBody) String() string {
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}
