// This file was auto-generated by Fern from our API Definition.

export interface SearchResponse {
    result: string;
}

export namespace SearchResponse {
    export type Request = Omit<SearchResponse, "result"> & {
        result: string;
    };
    export type Response = Omit<SearchResponse, "result"> & {
        result: string;
    };
}
