package com.seed.api;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.seed.api.SeedApiClient;
import com.seed.api.core.ObjectMappers;
import com.seed.api.types.Account;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import okhttp3.mockwebserver.RecordedRequest;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class ServiceWireTest {
    private MockWebServer server;
    private SeedApiClient client;
    private ObjectMapper objectMapper = ObjectMappers.JSON_MAPPER;
    @BeforeEach
    public void setup() throws Exception {
        server = new MockWebServer();
        server.start();
        client = SeedApiClient.builder()
            .url(server.url("/").toString())
            .build();
    }
    @AfterEach
    public void teardown() throws Exception {
        server.shutdown();
    }
    @Test
    public void testGetAccount() throws Exception {
        server.enqueue(new MockResponse()
            .setResponseCode(200)
            .setBody("{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[{\"resource_type\":\"Script\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},{\"resource_type\":\"Script\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}}],\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}}}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}}}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[{\"resource_type\":\"Script\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Script\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[{\"resource_type\":\"Script\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Script\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[{\"resource_type\":\"Script\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Script\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}},\"id\":\"id\",\"related_resources\":[{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}],\"memo\":{\"description\":\"description\",\"account\":{\"resource_type\":\"Account\",\"name\":\"name\",\"patient\":{\"resource_type\":\"Patient\",\"name\":\"name\",\"scripts\":[],\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"practitioner\":{\"resource_type\":\"Practitioner\",\"name\":\"name\",\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}},\"id\":\"id\",\"related_resources\":[],\"memo\":{\"description\":\"description\"}}}}}}"));
        Account response = client.getAccount("account_id");
        RecordedRequest request = server.takeRequest();
        Assertions.assertNotNull(request);
        Assertions.assertEquals("GET", request.getMethod());
        
        // Validate response body
        Assertions.assertNotNull(response, "Response should not be null");
        String actualResponseJson = objectMapper.writeValueAsString(response);
        String expectedResponseBody = ""
            + "{\n"
            + "  \"resource_type\": \"Account\",\n"
            + "  \"name\": \"name\",\n"
            + "  \"patient\": {\n"
            + "    \"resource_type\": \"Patient\",\n"
            + "    \"name\": \"name\",\n"
            + "    \"scripts\": [\n"
            + "      {\n"
            + "        \"resource_type\": \"Script\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      {\n"
            + "        \"resource_type\": \"Script\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    ],\n"
            + "    \"id\": \"id\",\n"
            + "    \"related_resources\": [\n"
            + "      {\n"
            + "        \"resource_type\": \"Account\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"patient\": {\n"
            + "          \"resource_type\": \"Patient\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"scripts\": [],\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"practitioner\": {\n"
            + "          \"resource_type\": \"Practitioner\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      {\n"
            + "        \"resource_type\": \"Account\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"patient\": {\n"
            + "          \"resource_type\": \"Patient\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"scripts\": [],\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"practitioner\": {\n"
            + "          \"resource_type\": \"Practitioner\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    ],\n"
            + "    \"memo\": {\n"
            + "      \"description\": \"description\",\n"
            + "      \"account\": {\n"
            + "        \"resource_type\": \"Account\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"patient\": {\n"
            + "          \"resource_type\": \"Patient\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"scripts\": [],\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"practitioner\": {\n"
            + "          \"resource_type\": \"Practitioner\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "  },\n"
            + "  \"practitioner\": {\n"
            + "    \"resource_type\": \"Practitioner\",\n"
            + "    \"name\": \"name\",\n"
            + "    \"id\": \"id\",\n"
            + "    \"related_resources\": [\n"
            + "      {\n"
            + "        \"resource_type\": \"Account\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"patient\": {\n"
            + "          \"resource_type\": \"Patient\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"scripts\": [],\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"practitioner\": {\n"
            + "          \"resource_type\": \"Practitioner\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      {\n"
            + "        \"resource_type\": \"Account\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"patient\": {\n"
            + "          \"resource_type\": \"Patient\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"scripts\": [],\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"practitioner\": {\n"
            + "          \"resource_type\": \"Practitioner\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    ],\n"
            + "    \"memo\": {\n"
            + "      \"description\": \"description\",\n"
            + "      \"account\": {\n"
            + "        \"resource_type\": \"Account\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"patient\": {\n"
            + "          \"resource_type\": \"Patient\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"scripts\": [],\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"practitioner\": {\n"
            + "          \"resource_type\": \"Practitioner\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "  },\n"
            + "  \"id\": \"id\",\n"
            + "  \"related_resources\": [\n"
            + "    {\n"
            + "      \"resource_type\": \"Account\",\n"
            + "      \"name\": \"name\",\n"
            + "      \"patient\": {\n"
            + "        \"resource_type\": \"Patient\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"scripts\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Script\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Script\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"practitioner\": {\n"
            + "        \"resource_type\": \"Practitioner\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"id\": \"id\",\n"
            + "      \"related_resources\": [\n"
            + "        {\n"
            + "          \"resource_type\": \"Account\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"patient\": {\n"
            + "            \"resource_type\": \"Patient\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"scripts\": [],\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"practitioner\": {\n"
            + "            \"resource_type\": \"Practitioner\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"resource_type\": \"Account\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"patient\": {\n"
            + "            \"resource_type\": \"Patient\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"scripts\": [],\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"practitioner\": {\n"
            + "            \"resource_type\": \"Practitioner\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        }\n"
            + "      ],\n"
            + "      \"memo\": {\n"
            + "        \"description\": \"description\",\n"
            + "        \"account\": {\n"
            + "          \"resource_type\": \"Account\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"patient\": {\n"
            + "            \"resource_type\": \"Patient\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"scripts\": [],\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"practitioner\": {\n"
            + "            \"resource_type\": \"Practitioner\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"resource_type\": \"Account\",\n"
            + "      \"name\": \"name\",\n"
            + "      \"patient\": {\n"
            + "        \"resource_type\": \"Patient\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"scripts\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Script\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Script\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"practitioner\": {\n"
            + "        \"resource_type\": \"Practitioner\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"id\": \"id\",\n"
            + "      \"related_resources\": [\n"
            + "        {\n"
            + "          \"resource_type\": \"Account\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"patient\": {\n"
            + "            \"resource_type\": \"Patient\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"scripts\": [],\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"practitioner\": {\n"
            + "            \"resource_type\": \"Practitioner\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"resource_type\": \"Account\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"patient\": {\n"
            + "            \"resource_type\": \"Patient\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"scripts\": [],\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"practitioner\": {\n"
            + "            \"resource_type\": \"Practitioner\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        }\n"
            + "      ],\n"
            + "      \"memo\": {\n"
            + "        \"description\": \"description\",\n"
            + "        \"account\": {\n"
            + "          \"resource_type\": \"Account\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"patient\": {\n"
            + "            \"resource_type\": \"Patient\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"scripts\": [],\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"practitioner\": {\n"
            + "            \"resource_type\": \"Practitioner\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "  ],\n"
            + "  \"memo\": {\n"
            + "    \"description\": \"description\",\n"
            + "    \"account\": {\n"
            + "      \"resource_type\": \"Account\",\n"
            + "      \"name\": \"name\",\n"
            + "      \"patient\": {\n"
            + "        \"resource_type\": \"Patient\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"scripts\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Script\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Script\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"practitioner\": {\n"
            + "        \"resource_type\": \"Practitioner\",\n"
            + "        \"name\": \"name\",\n"
            + "        \"id\": \"id\",\n"
            + "        \"related_resources\": [\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"memo\": {\n"
            + "          \"description\": \"description\",\n"
            + "          \"account\": {\n"
            + "            \"resource_type\": \"Account\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"id\": \"id\",\n"
            + "      \"related_resources\": [\n"
            + "        {\n"
            + "          \"resource_type\": \"Account\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"patient\": {\n"
            + "            \"resource_type\": \"Patient\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"scripts\": [],\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"practitioner\": {\n"
            + "            \"resource_type\": \"Practitioner\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"resource_type\": \"Account\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"patient\": {\n"
            + "            \"resource_type\": \"Patient\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"scripts\": [],\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"practitioner\": {\n"
            + "            \"resource_type\": \"Practitioner\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        }\n"
            + "      ],\n"
            + "      \"memo\": {\n"
            + "        \"description\": \"description\",\n"
            + "        \"account\": {\n"
            + "          \"resource_type\": \"Account\",\n"
            + "          \"name\": \"name\",\n"
            + "          \"patient\": {\n"
            + "            \"resource_type\": \"Patient\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"scripts\": [],\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"practitioner\": {\n"
            + "            \"resource_type\": \"Practitioner\",\n"
            + "            \"name\": \"name\",\n"
            + "            \"id\": \"id\",\n"
            + "            \"related_resources\": [],\n"
            + "            \"memo\": {\n"
            + "              \"description\": \"description\"\n"
            + "            }\n"
            + "          },\n"
            + "          \"id\": \"id\",\n"
            + "          \"related_resources\": [],\n"
            + "          \"memo\": {\n"
            + "            \"description\": \"description\"\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "  }\n"
            + "}";
        JsonNode actualResponseNode = objectMapper.readTree(actualResponseJson);
        JsonNode expectedResponseNode = objectMapper.readTree(expectedResponseBody);
        Assertions.assertEquals(expectedResponseNode, actualResponseNode, "Response body structure does not match expected");
        if (actualResponseNode.has("type") || actualResponseNode.has("_type") || actualResponseNode.has("kind")) {
            String discriminator = null;
            if (actualResponseNode.has("type")) discriminator = actualResponseNode.get("type").asText();
            else if (actualResponseNode.has("_type")) discriminator = actualResponseNode.get("_type").asText();
            else if (actualResponseNode.has("kind")) discriminator = actualResponseNode.get("kind").asText();
            Assertions.assertNotNull(discriminator, "Union type should have a discriminator field");
            Assertions.assertFalse(discriminator.isEmpty(), "Union discriminator should not be empty");
        }
        
        if (!actualResponseNode.isNull()) {
            Assertions.assertTrue(actualResponseNode.isObject() || actualResponseNode.isArray() || actualResponseNode.isValueNode(), "response should be a valid JSON value");
        }
        
        if (actualResponseNode.isArray()) {
            Assertions.assertTrue(actualResponseNode.size() >= 0, "Array should have valid size");
        }
        if (actualResponseNode.isObject()) {
            Assertions.assertTrue(actualResponseNode.size() >= 0, "Object should have valid field count");
        }
    }
}
