/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.contentTypes.resources.service;

import com.seed.contentTypes.core.ClientOptions;
import com.seed.contentTypes.core.RequestOptions;
import com.seed.contentTypes.resources.service.requests.PatchProxyRequest;

public class ServiceClient {
    protected final ClientOptions clientOptions;

    private final RawServiceClient rawClient;

    public ServiceClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawServiceClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawServiceClient withRawResponse() {
        return this.rawClient;
    }

    public void patch(PatchProxyRequest request) {
        this.rawClient.patch(request).body();
    }

    public void patch(PatchProxyRequest request, RequestOptions requestOptions) {
        this.rawClient.patch(request, requestOptions).body();
    }
}
