# frozen_string_literal: true

require "json"
require "net/http"
require "securerandom"

# Internal Types
require_relative 'seed/internal/json/serializable'
require_relative 'seed/internal/types/type'
require_relative 'seed/internal/types/utils'
require_relative 'seed/internal/types/union'
require_relative 'seed/internal/errors/constraint_error'
require_relative 'seed/internal/errors/type_error'
require_relative 'seed/internal/http/base_request'
require_relative 'seed/internal/json/request'
require_relative 'seed/internal/http/raw_client'
require_relative 'seed/internal/multipart/multipart_encoder'
require_relative 'seed/internal/multipart/multipart_form_data_part'
require_relative 'seed/internal/multipart/multipart_form_data'
require_relative 'seed/internal/multipart/multipart_request'
require_relative 'seed/internal/types/model/field'
require_relative 'seed/internal/types/model'
require_relative 'seed/internal/types/array'
require_relative 'seed/internal/types/boolean'
require_relative 'seed/internal/types/enum'
require_relative 'seed/internal/types/hash'
require_relative 'seed/internal/types/unknown'

# API Types
require_relative 'seed/endpoints/put/types/put_response'
require_relative 'seed/endpoints/put/types/error'
require_relative 'seed/endpoints/put/types/error_category'
require_relative 'seed/endpoints/put/types/error_code'
require_relative 'seed/general_errors/types/bad_object_request_info'
require_relative 'seed/types/docs/types/object_with_docs'
require_relative 'seed/types/enum/types/weather_report'
require_relative 'seed/types/object/types/object_with_optional_field'
require_relative 'seed/types/object/types/object_with_required_field'
require_relative 'seed/types/object/types/object_with_map_of_map'
require_relative 'seed/types/object/types/nested_object_with_optional_field'
require_relative 'seed/types/object/types/nested_object_with_required_field'
require_relative 'seed/types/object/types/double_optional'
require_relative 'seed/types/object/types/optional_alias'
require_relative 'seed/types/union/types/animal'
require_relative 'seed/types/union/types/dog'
require_relative 'seed/types/union/types/cat'

# Client Types
require_relative 'seed/client'
require_relative 'seed/endpoints/client'
require_relative 'seed/endpoints/container/client'
require_relative 'seed/endpoints/content_type/client'
require_relative 'seed/endpoints/enum/client'
require_relative 'seed/endpoints/http_methods/client'
require_relative 'seed/endpoints/object/client'
require_relative 'seed/endpoints/params/client'
require_relative 'seed/endpoints/params/types/get_with_inline_path'
require_relative 'seed/endpoints/params/types/get_with_query'
require_relative 'seed/endpoints/params/types/get_with_multiple_query'
require_relative 'seed/endpoints/params/types/get_with_path_and_query'
require_relative 'seed/endpoints/params/types/get_with_inline_path_and_query'
require_relative 'seed/endpoints/params/types/modify_resource_at_inlined_path'
require_relative 'seed/endpoints/primitive/client'
require_relative 'seed/endpoints/put/client'
require_relative 'seed/endpoints/put/types/put_request'
require_relative 'seed/endpoints/union/client'
require_relative 'seed/endpoints/urls/client'
require_relative 'seed/inlined_requests/client'
require_relative 'seed/inlined_requests/types/post_with_object_body'
require_relative 'seed/no_auth/client'
require_relative 'seed/no_req_body/client'
require_relative 'seed/req_with_headers/client'
require_relative 'seed/req_with_headers/types/req_with_headers'