# This file was auto-generated by Fern from our API Definition.

SignerAddress1 = str
"""
Additional line for the signer's address. If used, this must be the physical address of the signer, not a P.O. box.
"""
