// This file was auto-generated by Fern from our API Definition.

import { HeadersClient } from "./api/resources/headers/client/Client.js";
import { InlinedRequestClient } from "./api/resources/inlinedRequest/client/Client.js";
import { MultipartFormClient } from "./api/resources/multipartForm/client/Client.js";
import { PathParamClient } from "./api/resources/pathParam/client/Client.js";
import { QueryParamClient } from "./api/resources/queryParam/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import * as core from "./core/index.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";

export declare namespace SeedEnumClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SeedEnumClient {
    protected readonly _options: NormalizedClientOptions<SeedEnumClient.Options>;
    protected readonly _client: core.HttpClient;
    protected _headers: HeadersClient | undefined;
    protected _inlinedRequest: InlinedRequestClient | undefined;
    protected _multipartForm: MultipartFormClient | undefined;
    protected _pathParam: PathParamClient | undefined;
    protected _queryParam: QueryParamClient | undefined;

    constructor(options: SeedEnumClient.Options) {
        this._options = normalizeClientOptions(options);
        this._client = new core.HttpClient(
            this._options,
            (args) => new errors.SeedEnumError(args),
            handleNonStatusCodeError,
        );
    }

    public get headers(): HeadersClient {
        return (this._headers ??= new HeadersClient(this._options, this._client));
    }

    public get inlinedRequest(): InlinedRequestClient {
        return (this._inlinedRequest ??= new InlinedRequestClient(this._options, this._client));
    }

    public get multipartForm(): MultipartFormClient {
        return (this._multipartForm ??= new MultipartFormClient(this._options, this._client));
    }

    public get pathParam(): PathParamClient {
        return (this._pathParam ??= new PathParamClient(this._options, this._client));
    }

    public get queryParam(): QueryParamClient {
        return (this._queryParam ??= new QueryParamClient(this._options, this._client));
    }
}
