/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as FernOpenapiIr from "../../../../api";
import * as core from "../../../../core";

export const WebsocketHandshakeWithExample: core.serialization.ObjectSchema<
    serializers.WebsocketHandshakeWithExample.Raw,
    FernOpenapiIr.WebsocketHandshakeWithExample
> = core.serialization.objectWithoutOptionalProperties({
    queryParameters: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).QueryParameterWithExample)
    ),
    headers: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).HeaderWithExample)
    ),
});

export declare namespace WebsocketHandshakeWithExample {
    interface Raw {
        queryParameters: serializers.QueryParameterWithExample.Raw[];
        headers: serializers.HeaderWithExample.Raw[];
    }
}
