// This file was auto-generated by Fern from our API Definition.

import type * as SeedUndiscriminatedUnions from "../../../index.js";

/**
 * Nested layer 1.
 */
export type NestedUnionL1 = number | string[] | string[] | SeedUndiscriminatedUnions.NestedUnionL2;
