// This file was auto-generated by Fern from our API Definition.

export interface HoarseMouse {
    value: string;
}

export namespace HoarseMouse {
    export type Request = Omit<HoarseMouse, "value"> & {
        value: string;
    };
    export type Response = Omit<HoarseMouse, "value"> & {
        value: string;
    };
}
