/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FernDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { EnumSchema } from "./EnumSchema";

export const InlinedEnumSchema: core.serialization.ObjectSchema<
    serializers.InlinedEnumSchema.Raw,
    FernDefinition.InlinedEnumSchema
> = core.serialization
    .object({
        name: core.serialization.string(),
    })
    .extend(EnumSchema);

export declare namespace InlinedEnumSchema {
    interface Raw extends EnumSchema.Raw {
        name: string;
    }
}
