export * as aliasedObjectUnion from "./aliasedObjectUnion.js";
export * as call from "./call.js";
export * as duplicateTypesUnion from "./duplicateTypesUnion.js";
export * as get from "./get.js";
export * as getMetadata from "./getMetadata.js";
export * as getWithBaseProperties from "./getWithBaseProperties.js";
export * as nestedObjectUnions from "./nestedObjectUnions.js";
export * as nestedUnions from "./nestedUnions.js";
export * from "./requests/index.js";
export * as testCamelCaseProperties from "./testCamelCaseProperties.js";
export * as updateMetadata from "./updateMetadata.js";
