FROM python:3.8.19-slim-bookworm

# renovate: datasource=pypi depName=poetry versioning=semver
ENV POETRY_VERSION 2.2.1

RUN set -ex; pip install --no-cache-dir poetry==$POETRY_VERSION;


RUN apt update && apt upgrade -y
RUN apt install nodejs npm -y
RUN npm install -g fern-api

CMD [ "poetry" ]