FROM python:3.13.9-slim-bookworm

RUN pip install --no-cache-dir uv==0.8.23

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y nodejs npm
RUN npm install -g fern-api@latest
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

CMD [ "uv" ]
