/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seed.api;

import com.seed.api.core.ClientOptions;
import com.seed.api.core.RequestOptions;
import com.seed.api.requests.PostSubmitRequest;
import com.seed.api.types.PostSubmitResponse;
import com.seed.api.types.TokenRequest;
import com.seed.api.types.TokenResponse;

public class SeedApiClient {
    protected final ClientOptions clientOptions;

    private final RawSeedApiClient rawClient;

    public SeedApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSeedApiClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSeedApiClient withRawResponse() {
        return this.rawClient;
    }

    public PostSubmitResponse submitFormData(PostSubmitRequest request) {
        return this.rawClient.submitFormData(request).body();
    }

    public PostSubmitResponse submitFormData(PostSubmitRequest request, RequestOptions requestOptions) {
        return this.rawClient.submitFormData(request, requestOptions).body();
    }

    public TokenResponse getToken(TokenRequest request) {
        return this.rawClient.getToken(request).body();
    }

    public TokenResponse getToken(TokenRequest request, RequestOptions requestOptions) {
        return this.rawClient.getToken(request, requestOptions).body();
    }

    public static SeedApiClientBuilder builder() {
        return new SeedApiClientBuilder();
    }
}
