name: Publish @fern-api/snippets-core

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the library to publish."
        required: true
        type: string

env:
  DO_NOT_TRACK: "1"
  PACKAGE_NAME: "@fern-api/snippets-core"
  GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ inputs.version != null }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-tags: true

      - name: 📥 Install
        uses: ./.github/actions/install

      - name: Update npm
        run: npm install -g npm@latest

      - uses: bufbuild/buf-setup-action@v1.34.0
        with:
          github_token: ${{ github.token }}

      - uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Install protoc-gen-openapi
        run: go install github.com/fern-api/protoc-gen-openapi/cmd/protoc-gen-openapi@latest

      - name: 🧪 Build
        run: pnpm turbo run compile --filter=${{ env.PACKAGE_NAME }}

      - name: 🧪 Test
        run: pnpm turbo run test --filter=${{ env.PACKAGE_NAME }}

      - name: Publish @fern-api/snippets-core
        run: |
          cd packages/snippets/core
          pnpm turbo run dist --filter=${{ env.PACKAGE_NAME }} -- ${{ inputs.version }}
          cd dist
          npx -y npm@latest publish --access public --tag latest
