name: Update Test

on:
  workflow_dispatch:

# Cancel previous workflows on previous push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DO_NOT_TRACK: "1"
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"
  TURBO_REMOTE_CACHE_TIMEOUT: 10
  TURBO_NO_UPDATE_NOTIFIER: "1"
  TURBO_DAEMON: "false"

jobs:
  update-test:
    if: github.repository == 'fern-api/fern' && github.ref != 'refs/heads/main'
    runs-on: Test
    timeout-minutes: 90
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Install
        uses: ./.github/actions/install

      - uses: bufbuild/buf-setup-action@v1.50.0
        with:
          github_token: ${{ github.token }}

      - name: Verify buf
        run: buf --version

      - uses: actions/setup-go@v6
        with:
          go-version: "stable"
          cache-dependency-path: generators/go/go.sum

      - name: Install protoc-gen-openapi
        run: go install github.com/fern-api/protoc-gen-openapi/cmd/protoc-gen-openapi@latest

      - name: Run test:update
        run: pnpm test:update

      - name: Run test:ete:update
        timeout-minutes: 30
        env:
          FERN_ORG_TOKEN_DEV: ${{ secrets.FERN_ORG_TOKEN_DEV }}
        run: FERN_TOKEN=${{ secrets.FERN_ORG_TOKEN_DEV }} pnpm test:ete:update

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "chore: update test snapshots"
            git push
          else
            echo "No snapshot changes to commit"
          fi
